### ISSUE TITLE
'FirebaseCore/FirebaseCore.h' file not found -- only on iOS Release config

### ISSUE THREAD

**Issue by azraelx23** [invertase/react-native-firebase#1166]
### Issue

Build failed on Release configuration when trying to Archive, however works fine on Debug configuration on Run. Already tried delete Pods and node_modules, reinstall over and over again, same result. Moving to earlier RNFirebase version 4.1.0 ( with pod 'Firebase/Core', '~> 4.13.0' ) , is not an option since the Firebase/Functions module has runtime error on that particular version, even though the Archive/Release is successful using that version

Build error: 
```
'FirebaseCore/FirebaseCore.h' file not found
```

Podfile

```
target 'App' do
  use_frameworks!

  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Functions'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'

end
```

### Environment

1. Application Target Platform: iOS
2. Development Operating System: macOS High Sierra 10.13.4
3. Build Tools: XCode 9.4
4. React Native version: 0.55.3
5. RNFirebase Version: 4.2.0
6. Firebase Module: Core, Functions, Auth, Firestore, Messaging

<img width="1132" alt="screen shot 2018-06-01 at 17 44 30" src="https://user-images.githubusercontent.com/950254/40837166-b7d6bb2a-65c3-11e8-9fe8-912b39712344.png">

**Comment by chrisbianca** [comment]
Looks like this is a `use_frameworks` issue.  Either comment this out, or you'll have to explicitly set some dependencies as per the instructions here: https://github.com/invertase/react-native-firebase/releases/tag/v3.2.2

**Comment by azraelx23** [comment]
@chrisbianca I did as was suggested on the link to no avail, I needed to use 'use_frameworks' for some of the other libraries, and looks to me it's not finding the headers for some reason, and the other strange thing is that it always works on Debug config. Is there any other suggestions?

<img width="805" alt="screen shot 2018-06-04 at 01 47 04" src="https://user-images.githubusercontent.com/950254/40889968-3d5c2b3c-6799-11e8-85e2-e5284f9bba09.png">

**Comment by osiloke** [comment]
Having this same issue since I upgraded to the latest firebase version

**Comment by chrisbianca** [comment]
@azraelx23 try taking a look at the header, library and framework search paths for your project and see how release compares to the debug settings? It could be that something has got out of sync in your project.

**Comment by DMRE** [comment]
I have the same issue any solution?

**Comment by azraelx23** [comment]
@chrisbianca checking differences between the two schemes was the first thing I did since I have also been developing iOS apps for several years, did not find any kind of differences between the two. Can you consider reopening this issue since more people also experienced the same thing using the latest build?

**Comment by azraelx23** [comment]
https://github.com/invertase/react-native-firebase/issues/1106
might be related

**Comment by oferRounds** [comment]
Is there any solution? Facing the same issue

**Comment by oferRounds** [comment]
@azraelx23 did you find some solution? I also need the `use_frameworks`

**Comment by oferRounds** [comment]
@chrisbianca facing the same issue, tried also your workaround but no luck... Any idea?

**Comment by azraelx23** [comment]
@oferRounds for now, I ended up moving back to RNFirebase 4.1.0, specifically:
on package.json:
```
"react-native-firebase": "4.1.0",
```

and then on podfile:
```
  pod 'Firebase/Core', '~> 4.13.0'
```

delete all node_modules, Pods folder, xcworkspace file
do clean build on xcode, delete all derived data
do npm install, then pod install
try a build, it should work. Firebase functions do not work though, so for that I had to resort to use https request instead of using the callable method.

**Comment by oferRounds** [comment]
@azraelx23 thanks! The thing is that I’d like to use the _Messaging_, which is available only on 4.2+...

@chrisbianca I literally tried every clean, restart, delete, including the linking my pods as suggested. All in vail..
Any idea/workaround?

**Comment by okuzenko** [comment]
I am facing the same issue. Appreciate any help.

**Comment by oferRounds** [comment]
Did someone found any solution (for using the latest version)?

**Comment by Benjuari** [comment]
I have been trying all day to resolve this issue, if anybody has an update on this please let us know!

**Comment by oferRounds** [comment]
can we please re-open this issue?

**Comment by abe732** [comment]
Having same issue, would also vote to re-open this issue

**Comment by djneely** [comment]
Seeing the same issue. Had everything good to go till I added in Firestore and updated the packages. Now its failing.

**Comment by djneely** [comment]
Wound up resolving my issue with this bey removing the Pods directory and the Podfile.lock and re-installing.

**Comment by AnitaVPN** [comment]
Having same issue when run with device , did anyone has any solutions ?

**Comment by aaronkchsu** [comment]
Same issue here too!

**Comment by lyair1** [comment]
Same issue here, on this for 3 days, makes me think if I should take dependency on React Native Firebase in my app.

Please find a solution.

**Comment by oferRounds** [comment]
Any solution? @Salakar perhaps you have any workaround?

**Comment by evelynccordner** [comment]
I was able to work around this issue by commenting out the 'use_frameworks' line in the podfile and adding `:modular_headers => true` for imported pods e.g. `import @FirebaseAuth;`

Podfile: 
```
target 'App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase', '~> 5.0.1'
  pod 'FirebaseAuth', :modular_headers => true
  pod 'FirebaseFirestore'
  pod 'FirebaseFunctions'

  pod 'FBSDKCoreKit', :modular_headers => true
  pod 'FBSDKLoginKit', :modular_headers => true
```

**Comment by raff90** [comment]
having same issue! its been a day and i am still stuck

**Comment by oferRounds** [comment]
@raff90 I was manage to solve it, finally!
https://github.com/invertase/react-native-firebase/issues/1106#issuecomment-405030305

**Comment by zcoon** [comment]
Hey @chrisbianca thanks for your suggestion [here](https://github.com/invertase/react-native-firebase/issues/1166#issuecomment-394162920). It helped to build in release mode to device (couldn't before that), but when `archiving` the app, we get the issue described in the Title of this issue again..  Are you aware of any solutions that might make the header files available during the `archive` process that may not be found when building to device?

**Comment by cayleyh** [comment]
@zcoon I was having the exact same issue as you. I wasn't able to get it working with the `modular_headers` suggestions above. However, I ended up resolving it by explicitly setting library and header search paths for the archive build locations, as described https://stackoverflow.com/questions/5543854/xcode-4-cant-locate-public-header-files-from-static-library-dependency#9509786.

The answer there has a great description of how the paths are different for archived builds vs. regular builds. Hopefully that can help fix the issues you're have as well.

**Comment by abdullahceylan** [comment]
https://github.com/invertase/react-native-firebase/issues/1106#issuecomment-430029295 is should guide you to solve.

**Comment by marceh** [comment]
I had the same error code. I removed all "other linker flags" in build settings and entered $(inherited) instead. Then i did these steps: https://stackoverflow.com/a/44486792/9126507. Still didn't work for me.

I noticed that the briefcase symbol for "Linked frameworks and Libraries" under general was transparent. Checking into my project structure the corresponding framework under Products were red. Instead of building for my iphone6 as I did before, I build the project for the Generoc iOS Device. The build succeded and the briefcase symbol was no longer transparent and the files weren't red. Now I could build the app and run it to my iPhone6.

Don't know if that will fix your issue, but I had the same error.

**Comment by cayleyh** [comment]
Here's a step-by-step for everyone who is not able to either remove `use_frameworks!` or replace it with `:modular_headers => true` as mentioned above.

This assumes that you import the native Firebase libraries via Cocoapods, your Podfile has `use_frameworks!` (you're not able to remove this because of other pod requirements), and you're installing RNFirebase via npm/yarn and manually linking to your Xcode project as per normal rn library.

EVERY TIME you do a `pod install`, update the RNFirebase node module, or re-add RNFirebase to your xcode project, you will need to:

1. Explicitly set your pod framework as a build dependency with the `RNFirebase` target (as per https://github.com/invertase/react-native-firebase/releases/tag/v3.2.2).

2. Add the correct archive header path to the `Release` part of both `Framework Search Paths` and `Header Search Paths` in the `RNFirebase` project build settings.

#1 will fix the header not found issue for debug builds, #2 is required for building archives.

**Comment by manjuy124** [comment]
@cayleyh 
Can you give me example for your second point. In RNFirebase build settings, I do have like this.

<img width="524" alt="frameworksearchpath" src="https://user-images.githubusercontent.com/29254928/48931536-e54dbd00-ef1c-11e8-84ed-7ce855482fb2.png">
Framework search path

<img width="509" alt="headersearchpaths" src="https://user-images.githubusercontent.com/29254928/48931542-ee3e8e80-ef1c-11e8-8016-f536f8ec8068.png">
Header search path

Can you please help me. I stuck with this issue from almost 2 days.

**Comment by cayleyh** [comment]
@manjuy124 as stated, you need to add the path above to both those search paths under your release build in order to search in the correct release build path:

![screen shot 2018-11-23 at 9 48 52 am](https://user-images.githubusercontent.com/118396/48955924-1621f800-ef05-11e8-813c-43b7aa03c5f4.png)
![screen_shot_2018-11-23_at_9_47_19_am](https://user-images.githubusercontent.com/118396/48955926-17ebbb80-ef05-11e8-9c22-4774c8e09a10.jpg)

This is ONLY for the Release Builds as release builds build to a different spot that debug build path that is inherited.

Also, If you've set a custom build file location in your build schemes, you'll have to use whatever output directory you've configured there instead of the one I've provided.

**Comment by manjuy124** [comment]
@cayleyh 
Its working perfectly now. Thank u so much!

**Comment by turtec** [comment]
@cayleyh 
you saved my day ! Thanks!

**Comment by timt** [comment]
@cayleyh Thanks, you rock!

**Comment by solonifer** [comment]
@cayleyh Thank you 🙏

**Comment by 1omarsaid** [comment]
@cayleyh I dont have the RNFirebase target 
<img width="278" alt="screen shot 2019-01-03 at 8 17 20 am" src="https://user-images.githubusercontent.com/32044422/50639617-1a8ff680-0f30-11e9-936b-37d1538e1a10.png">

**Comment by cayleyh** [comment]
@1omarsaid My fix only applies if you're installing RNFirebase via npm/yarn and manually linking to your Xcode project as per a normal RN library. If you're trying to use RNFirebase via Pods somehow I can't help :(

**Comment by asolorzano1504** [comment]
I just had the same issue. What I had to do was:

Close Xcode
Restart Xcode and made sure I opened the .xcworkspace project file.
Ran a Build on the project.
After that I had no more Firebase error messages.

**Comment by dineshsharmaskycore** [comment]
Hi,
I am working on integration firebase ML vision kit without using the cocoa pods:

I am able to integrate the firebase’s analytics frameworks(there are 8 frameworks)in demo project and project build successfully.
I was trying same things with required firebase MLVision (there are 7 frameworks) and MLVisionTextModel (there are 3 frameworks with 1 resource folder).
I am getting below error as
ld: framework not found FirebaseMLVisionTextModel
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The framework FirebaseMLVisionTextModel doesn't have FirebaseMLVisionTextModel.h file. It doesn't exist header folder which is missing in FirebaseMLVisionTextModel framework:
```
Firebase.h : FirebaseMLVisionTextModel.h file deceleration:
#if __has_include(<FirebaseMLVisionTextModel/FirebaseMLVisionTextModel.h>)
#import <FirebaseMLVisionTextModel/FirebaseMLVisionTextModel.h>
#endif
```
Pls suggest how do I fix this problem.

Xcode version: 10.1
Firebase SDK version: 5.20.2
Firebase Component: ML Kit (text recognition)
Component version:

I raised this issue separate thread:
https://github.com/firebase/firebase-ios-sdk/issues/2848

**Comment by Sarathphd** [comment]
Hi, I am also face this issue. But I have fixed error. First goto project folder in ios folder and open profile file you just Commit **use_framework**. Then delete projectName.xcworkspace, pod folders and profile.lock file. And pod update, pod install finally open project to xcode and build. Easy to solve this issue and fixed.

**Comment by Ulanmax** [comment]
@asolorzano1504 
Thank you. You saved my day.

**Comment by king3andre** [comment]
@cayleyh dude, I owe you a beer! You saved my weekend. I spent 10 hrs on this to no avail. Until I came across your solution. Thanks for sharing, it worked for me.

**Comment by Linganna** [comment]
https://github.com/invertase/react-native-firebase/issues/1166#issuecomment-441294884
@cayleyh, it's working thank you

**Comment by iosiappmemes** [comment]
Hi, i am facing this issue . But i have this fixed error now. Go to Pod file and add "**pod 'Firebase/Core',  :modular_header => true** and "pod '**Firebase/Core',  :modular_header => true**
![Screenshot 2019-12-19 at 11 26 32 AM](https://user-images.githubusercontent.com/54673061/71149529-da1aad00-2254-11ea-9fbe-23a113f0a20b.png)

**Comment by TajinderSinghBai** [comment]
Hi, i am facing this issue . But i have this fixed error now. Go to Pod file and add "pod 'Firebase/Core', :modular_header => true and "pod 'Firebase/Core', :modular_header => true
![Screenshot 2019-12-19 at 11 26 32 AM](https://user-images.githubusercontent.com/26810588/71150583-d9374a80-2257-11ea-9253-115d9429a1a6.png)

**Comment by mikehardy** [comment]
Careful with the podfile advice, people have different situations based on whether they are using frameworks or not etc.

**Comment by rezasazesh** [comment]
This is still very problematic, the solution @cayleyh provides helped me with one project before but with a new project I realised that I cannot have the `Pods_{Project Name}.framework` since I cannot have `use_frameworks!` and seems that having the `use_frameworks!` makes the `Pods_{Project Name}.framework` file available in the project

**Comment by ardalahmet** [comment]
You can combine @cayleyh 's solution with https://github.com/ds300/patch-package/ then you won't need to apply the changes each time you update something.

**Comment by vijaykholiya** [comment]
Hey, for me this worked, I hope it might also work for you,
https://github.com/flutter/flutter/issues/22071#issuecomment-425048680

**Comment by ianspryn** [comment]
I had this issue and spent 2 days trying to solve it. None of the above suggestions helped, and I only had this issue with one of my schemes. If this helps anyone, that's great. This is for a Flutter project I am working on.

Recently I had created an additional scheme, `dev`. With this addition, I wanted to rename my already existing scheme to `prod` to make a clear difference. After all of this, I renamed my three Build Configurations, `Debug`, `Profile`, and `Release`, so that they would be `Debug-dev`, `Debug-prod`, and so on for the other two. This gave me a total of 6 unique Build Configurations.

Here is my mistake. When I click my scheme in the top left of Xcode (for me it says either `dev` or `prod`,  right next to the play and stop button), and then click "edit scheme," my Build Configuration for every mode (Run/Test/Profile/Analyze/Archive on the left-hand side of the menu) was still set to `Debug`, `Profile`, or `Release`, which DID NOT EXIST ANYMORE. They were renamed with an extension of either `-dev` or `-prod`. As a result, every time I tried to run my application it was looking for a Build Configuration that no longer existed, resulting in this `FirebaseCore/FirebaseCore.h file not found` error. So, I went through every mode and selected the new Build Configuration I had created with the new name.

**Make sure your Build Configuration selection for every mode in your scheme points to a name that actually exists. This does not automatically change if you rename your Build Configurations under Project --> Info --> Configurations!**

**Comment by eliaweiss** [comment]
Make sure you are opening the .xcworkspace file instead of the .xcodeproj file.

I was troubleshooting for at least an hour before I determined this was my mistake, so hopefully this answer will save you some time!

https://stackoverflow.com/a/58838520/1406269

**Comment by bookwarmdev** [comment]
Make sure you are opening the .xcworkspace file instead of the .xcodeproj file.

I was troubleshooting for days before I determined this was my mistake opining the wrong file.

**Comment by Mai-sudo** [comment]
Just open your .xcworkspace file after commands “pod install”

**Comment by ayhanhakan** [comment]
i tried a lots of things but when i change simulator its fixed now its work fine

**Comment by baycode** [comment]
When you open your project just open .xcworkspace file. If you open the .xcodeproj file probably you'll get this mistake.

**Comment by rammesaran** [comment]
@ianspryn  You saved my Life!!!! thanks a lot
