### ISSUE TITLE
createUserAndRetrieveDataWithEmailAndPassword and Promise Rejection

### ISSUE THREAD

**Issue by luco** [invertase/react-native-firebase#1198]
### Issue

I'm trying to make an user registration with `createUserAndRetrieveDataWithEmailAndPassword`, but it returns this:

![image](https://user-images.githubusercontent.com/246373/41197233-ce5f315a-6c2c-11e8-96f3-2b53a7c3c704.png)

My code:

```
firebase.auth().createUserAndRetrieveDataWithEmailAndPassword(currentData.email, currentData.password).then(function(user){
			
		})
```

### Environment

iOS (Didn't test on Android)

1. Application Target Platform:

macOS High Sierra

2. Development Operating System:

iOS 11.3

3. Build Tools:

N/D

4. React Native version:

0.55.3

5. RNFirebase Version:

4.2.0

6. Firebase Module:

auth

**Comment by flasd** [comment]
This most likely is due to bad Email/Password strings. Try debugging the error in the console:

```javascript
import firebase from 'react-native-firebase';

const auth = firebase.auth();

auth.createUserAndRetrieveDataWithEmailAndPassword(email, password)
    .then(function(user) { /* do your stuff */ })
    .catch(function(error) { console.log(error) });
```
Don't forget to enable `Debug JS Remotely` on the [React Native Dev Menu](https://facebook.github.io/react-native/docs/debugging.html#accessing-the-in-app-developer-menu) to be able to see console logs.

Check out [Firebase's docs](https://firebase.google.com/docs/reference/js/firebase.auth.Auth?hl=pt-br#createUserAndRetrieveDataWithEmailAndPassword) for better understanding error codes.

Best of luck.

**Comment by luco** [comment]
@flasd It gives me the same error:

![image](https://user-images.githubusercontent.com/246373/41197921-45b7bf6e-6c42-11e8-8b18-24dab0c732e9.png)

And I don't think it's about bad email/pwd since I'm using simple strings:

![image](https://user-images.githubusercontent.com/246373/41197925-59e1b95e-6c42-11e8-8ed4-ae918bc45e4b.png)

**Comment by luco** [comment]
I also dig on this:

```
const auth = NativeModules.RNFirebaseAuth;
auth.createUserAndRetrieveDataWithEmailAndPassword('test@test.com', '2y1t287sbb78')
    .then(function(user) { /* do your stuff */ })
    .catch(function(error) { console.log(error) });
```

![image](https://user-images.githubusercontent.com/246373/41198011-697ffb58-6c44-11e8-928c-a62d7546c0f4.png)

**Comment by flasd** [comment]
@luco You are still getting the `Unhandled Promise Rejection Error` even after changing the code? What's the console output?

Btw, `1234` as password will trigger an `auth/weak-password` error.

The deprecation warning is probably a issue all by itself. I think, since Firebase deprecated a bunch of `signInWith` methods in favor of the `signInAndRetriveDataWith`, maybe their team got confused and flipped things around for the `createAccountWith` method or the confusion happened with the RNF team.

I don't think you should use the NativeModule API in this case.

**Comment by luco** [comment]
@flasd Yes, I am. I tried to change the password to an stronger one but it still getting me error.

**Comment by chrisbianca** [comment]
Have you enabled email/password authentication in the Firebase console?

**Comment by luco** [comment]
@chrisbianca Yes, I did.

Even trying with a lower version of Firebase (v4), it doesn't work. Gives me the same internal error.

**Comment by luco** [comment]
@chrisbianca @Salakar Thoughts?

**Comment by luco** [comment]
So, I created an another Firebase project to test and it worked. I don't know what's wrong with the project I was testing. Anyway, thanks for your time!

**Comment by MacKentoch** [comment]
Please open back this issue.

Upper solution is not a suitable solution.
In my case, I can't use another fresh Firebase project, I have to use the existing one that works well on web.

When I console.log the error in catch:

<img width="606" alt="capture d ecran 2018-08-09 a 11 38 03" src="https://user-images.githubusercontent.com/11223428/43891080-c32677dc-9bc8-11e8-89b4-a75b33b84ec8.png">

Switching to `createUserAndRetrieveDataWithEmailAndPassword` throws equivalent error.


My versions:

- react: 16.3.1
- react-native: 0.55.4
- react-native-firebase: 4.2.0
