### ISSUE TITLE
Plans to support multi location updates ?

### ISSUE THREAD

**Issue by nico1510** [invertase/react-native-firebase#123]
I'm currently evaluating if I should use this library or firebase's web SDK and I'm wondering if there are plans to support [multi location updates](https://firebase.googleblog.com/2015/09/introducing-multi-location-updates-and_86.html) ?

**Comment by Ehesp** [comment]
Hi, if you mean something like:

```js
var updatedUserData = {};
updatedUserData["user/posts/" + newPostKey] = true;
updatedUserData["posts/" + newPostKey] = {
  title: "New Post",
  content: "Here is my new post!"
};
// Do a deep-path update
ref.update(updatedUserData, function(error) {
  if (error) {
    console.log("Error updating data:", error);
  }
});
```

I believe this is already supported.

**Comment by nico1510** [comment]
Yes that's what I meant. I couldn't find it in the docs here but it looks like it is indeed [supported](https://github.com/invertase/react-native-firebase/blob/master/lib/modules/database/reference.js#L99) thank you 😉

**Comment by jsm** [comment]
Except the typescript definitions cause a syntax error when calling ref.(), since the path isn't optional?

**Comment by chrisbianca** [comment]
@jsm The Typescript definitions were submitted as part of this https://github.com/invertase/react-native-firebase/pull/16. 

I personally use Flow rather than Typescript, and I don't think either @Salakar or @Ehesp are using Typescript either.  Please feel free to submit a PR to correct the definition if it's causing you problems.

**Comment by Ehesp** [comment]
cc @taljacobson
