### ISSUE TITLE
Scheduled notifications not being rescheduled on phone reboot

### ISSUE THREAD

**Issue by damienix** [invertase/react-native-firebase#1308]
### Issue

In the commit https://github.com/invertase/react-native-firebase/commit/dbc5a2d54e2c43f9e812fe81823a1981534475d1 scheduled notifications were broken on Android.

As described in the comment attached to the commit https://github.com/invertase/react-native-firebase/commit/d193c6b688850bf72ba321b3238b39f463ae38be, `getDouble("fireDate")` won't load any value (as it's saved as `Long`) and will default as instructed to `-1.0`.

@liamheneghan do you remember why `getDouble` is used as backup call?
@dluksza did you intend to reverse `getDouble` and `getLong` order? IMO it just doesn't work (at least on Android 5) as it returns no value (which defaults to -1 here) and doesn't throw `ClassCaseException` too. `getLong` works properly in this case.

### Environment

1. Application Target Platform: Android
2. `React Native Firebase` Version: Since 4.2.0, see https://github.com/invertase/react-native-firebase/commit/dbc5a2d54e2c43f9e812fe81823a1981534475d1
3. `Firebase` Module: notifications

**Comment by liamheneghan** [comment]
@damienix as far as I can remember scheduling notifications had 2 paths.

1. `scheduleNotification(ReadableMap notification, Promise promise)` called directly when scheduling a notification from React Native.
2. `rescheduleNotifications()` called when the device has rebooted.

Each use a different method to build their `Bundle` for `scheduleNotification(Bundle notification, @Nullable Promise promise)`. 

When rescheduling notifications the `fireDate` is stored as a Long in the bundle. When scheduling a notification directly a Double is stored in the bundle which is why the `getDouble` is used.

**Comment by dluksza** [comment]
I've proposed https://github.com/invertase/react-native-firebase/commit/dbc5a2d54e2c43f9e812fe81823a1981534475d1 because I've got `ClassCastException` during my testing. It was on android 8.0 (AFAIR), didn't verified this on 5.0 therefore can't say how it is behaving. I also don't get any complains from my users so I assume that everything works fine.

**Comment by damienix** [comment]
@liamheneghan thanks for the helpful information. Your comment was there already :) I've just improved it a little bit. The PR is incoming in a few minutes!

In short, the original code was jus fine.

@dluksza correct me if I'm wrong, IMO your `try-catch` did absolutely nothing because `ClassCastException` is an internal warning from `Bundle.parseLong` while parsing `Double` type. In addition to this, you've changed the order of parsing which broke rescheduling notifications as `schedule.getLong()` was never called (dead `catch` clause).

So perhaps your users don't use notifications or don't reboot their phones as your assumption is wrong. Sorry for being semi-rude but I'm just wasting the 3rd night on it.

**Comment by damienix** [comment]
Sorry for being picky but @dluksza's last PR related to THIS have introduced this bug, not a fix :( His other recent PRs are not related to this I believe.

Thank you for merging my PR though.
Cheers

**Comment by Salakar** [comment]
@damienix just a little picky 😄 no worries. To clarify I meant [this PR](https://github.com/invertase/react-native-firebase/pull/1294) and it's related in terms of it being on the topic scheduling.

Thanks
