### ISSUE TITLE
hasPermission is not a function 

### ISSUE THREAD

**Issue by mishroom** [invertase/react-native-firebase#1334]
### Issue

I'm getting an error saying hasPermission is not a function. As per Issue #916 , I updated my react-native-firebase package to 4.0.0, and am now getting this error on my console:

![image](https://user-images.githubusercontent.com/16855482/43097253-56ae446e-8e70-11e8-96ab-b6c716325c18.png)

'RNFirebaseDatabase.on was called with 3 arguments but expects 2 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away',

as well as these issues trying to build on Xcode
![image](https://user-images.githubusercontent.com/16855482/43097121-f5c75fb4-8e6f-11e8-982d-c71a050d8cfa.png)

### Environment

1. Application Target Platform:

iOS

2. Development Operating System:

macOS High Sierra

3. Build Tools:

Xcode Version 9.4.1

4. `React Native` version:

  https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz

5. `React Native Firebase` Version:

^4.0.0

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

No

**Comment by erandagan** [comment]
The error you're getting on the device is caused by the fact you're unable to build your xcode project with the new native dependencies, thus having a mismatch between your JS RNFirebase and the native modules.

As for the issues with building your project, are you sure you're using the right pod version for firebase? Perhaps you're using newer pods than RNF 4.0 supports?

- Check your pod lock file for installed firebase versions and make sure you're not using v5 pods along with RNF 4.0.x

- Consider upgrading to RNF 4.3.x which supports newer firebase pods (v5)
