### ISSUE TITLE
onSnapshot not work when back online

### ISSUE THREAD

**Issue by warteruzannan** [invertase/react-native-firebase#1452]
Hi
After I put the phone in plane mode and go online again the _firestore_ does not receive updates made while in airplane mode.
To receive the updates I have to restart the application.

```
firebase.firestore().doc("somepath").onSnapshot((querySnapshot) => {
     /**not receive data***/
})
```

react-native-firebase: "^4.3.8"

classpath 'com.android.tools.build:gradle:3.1.3' 
classpath 'com.google.gms:google-services:4.0.1'   

implementation project(':react-native-firebase')

implementation "com.google.android.gms:play-services-base:15.0.1"
implementation "com.google.firebase:firebase-core:16.0.1"
implementation "com.google.firebase:firebase-auth:16.0.2"
implementation "com.google.firebase:firebase-firestore:17.0.2"
implementation "com.google.firebase:firebase-database:16.0.1"
implementation "com.google.firebase:firebase-storage:16.0.1"

**Comment by Ehesp** [comment]
Hey, can you setup a network listener in React Native, and when online add in https://rnfirebase.io/docs/v4.3.x/firestore/reference/firestore#enableNetwork

**Comment by warteruzannan** [comment]
@Ehesp, it did not work either...

**Comment by Salakar** [comment]
This looks like an issue that has been fixed in the latest firebase sdks for iOS, see: https://firebase.google.com/support/release-notes/ios 

Specifically:
![image](https://user-images.githubusercontent.com/5347038/46044569-0eb3bd80-c113-11e8-9c79-8b67e8c3af0e.png)

v5 of RNFB (released tomorrow) has the latest SDK's supported. Please try this out when it's released and let us know if this is not still the case.

Thanks
