### ISSUE TITLE
Usage of Vulnerable Libraries

### ISSUE THREAD

**Issue by scrodrig** [invertase/react-native-firebase#1508]
### Issue

According to security checker, RNFirebase 4.3.8 (latest version at this moment), uses old dependencies of Firebase. 

Latest version is 5.8.1 in [iOS](https://firebase.google.com/support/releases) and 16.x.x or 17.x.x for [Android](https://firebase.google.com/support/release-notes/android#latest_sdk_versions) and 5.5.0 in [javascript](https://firebase.google.com/support/releases)

![FirebaseInstanceIdService](https://user-images.githubusercontent.com/5466692/45779658-34c3f400-bc21-11e8-99b0-db368911442e.png)

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS High Sierra

3. Build Tools: Xcode 9.4.1 (9f2000), Android Studio 3.1

4. `React Native` version: 0.55.4

5. `React Native Firebase` Version: 4.3.8

6. `Firebase` Module: messaging, analytics, crashlytics 

7. Are you using `typescript`? No

**Comment by Salakar** [comment]
@scrodrig upcoming v5 is using the latest SDK's - unfortunately we can't always apply updated Firebase SDKs to older RNFirebase release due to breaking changes - so we major version release them.

`react-native-firebase@5.0.0-rc3` - is the latest 'stable' version of v5 if you'd like to update now - otherwise, the full release will be out soon-ish.

Thanks
---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
