### ISSUE TITLE
Preventing select push notifications from being shown?

### ISSUE THREAD

**Issue by mcampsall** [invertase/react-native-firebase#152]
Is there a way to intercept push notifications and prevent them from being shown if the app decides to silence them?

Ex. Could I intercept the push notification and then schedule local notifications for the ones i want to show?

`getInitialNotification()` seems like it is after the fact (unless we can push 'silent' notifications and handle them in the background)

I also see that `createLocalNotification(notification: Object)` is not implemented in V1 yet either, but I am assuming it is possible

**Comment by chrisbianca** [comment]
@mcampsall I *think* you can do this by just sending a `data` payload in the FCM message rather than including the `notification` payload.  This will bypass the build in OS notification and will just be received by the `getInitialNotification()` method, or `onMessage` depending on whether your app was running when the notification arrives.

My only question is whether or not the OS will pass the notification on to the app without a `notification` payload...

I'm going to close this as it's not an issue per se, but please let me know if it does/doesn't work!

**Comment by iadcg** [comment]
Hi @chrisbianca. Where is this `onMessage` here? is it in the javascript part? or native part?
