### ISSUE TITLE
Install without CocoaPods?

### ISSUE THREAD

**Issue by dsabatier** [invertase/react-native-firebase#153]
Hi,

 is there a way to work around CocoaPods or is it a strict requirement?

I am trying to get firebase data persistence going on an ios app which led me to this module, but I have been given some technical restrictions that include not using CocoaPods.   I looked at the docs and didn't see anything, maybe I missed it?  I already had firebase set up without pods.  I'm hoping it's just a matter of linking some things in xcode, but I am not certain I understand what CocoaPods does in its entirety.

Thanks in advance!

**Comment by chrisbianca** [comment]
@dsabatier In theory, yes.  If you've already got Firebase set up without using pods, then in theory, you should just be able to link the RNFirebase library manually and skip the Firebase pods setup that is mentioned in the documentation.

Can you let me know if this does/doesn't work?  That way we can add *another* way of setting up the project to the instructions!!

**Comment by dsabatier** [comment]
Thanks.  I'm taking a look at it now.

The issue I'm facing now is:

'Firebase.h' file not found,  in RNFirebaseError.h:9, which is being called by RNFirebaseErrors.h:1.

I had assumed it would be a matter of adding $(SRCROOT)/../../node_modules/firebase to Header Search Paths in the RNFirebase project, but that doesn't seem to do anything.

Any help would be appreciated.

For posterity, I've installed react-native-firebase as well as manually installed all of the firebase modules following the instructions here (integrate without CocoaPods):

https://firebase.google.com/docs/ios/setup

**Comment by dsabatier** [comment]
nevermind, I think I just had the path wrong.  It compiles again, but when launching if I run
`import RNFirebase from 'react-native-firebase` I get the below.

![simulator screen shot jun 9 2017 12 11 56 pm](https://user-images.githubusercontent.com/16840628/26988490-e21e73da-4d0c-11e7-8f64-fc3a38b7724c.png)

**Comment by chrisbianca** [comment]
Have you followed steps A-C from here?  It sounds like RNFirebase hasn't been setup properly to get that error.

http://invertase.io/react-native-firebase/#/installation-ios?id=_23-you39re-not-using-cocoapods-or-don39t-have-react-native-installed-as-a-pod-manual-install

**Comment by chrisbianca** [comment]
@dsabatier did you manage to get this working?

**Comment by dsabatier** [comment]
No, I haven't had time to dig further into it and likely won't have a chance for a few weeks due to shifting priorities.  I have backlogged a task for myself to revisit this and update, sorry I couldn't get further.

**Comment by DavideValdo** [comment]
Documentation to install without CocoaPods was removed, why so?
I managed to integrate this module with wix's native navigation module, but only on Android.
On iOS the only way would be to set this up without CocoaPods.

**Comment by DavideValdo** [comment]
I've tried to do it anyway but I'm not getting lucky.

When I run the application, XCode seems to let me know that Firebase'SDK was properly linked and that [FIRApp configure] works

> 2017-06-18 19:35:49.969 myapp[2224] [Firebase/Analytics][I-ACS005000] The AdSupport Framework is not currently linked. Some features will not function properly. Learn more at (stackoverflow forbids shorteners)
> 
> 2017-06-18 19:35:49.971 myapp[2224] [Firebase/Analytics][I-ACS023007] Firebase Analytics v.4001000 started

Then when bundler loads and React starts, I get a red screen saying 
"Native module cannot be null"

**Comment by DavideValdo** [comment]
@chrisbianca Sadly I wasn't able to spend much more time on this and actually choose to change routing module. Did you manage to accomplish anything? Maybe with v2?

**Comment by cladjules** [comment]
Hi there,

I managed to have it working without Pods,

because by default RNFirebase Project includes header from: "${SRCROOT}/../../../ios/Pods"

You either

- add additional header search path (and framework, but that would be erased after npm install)

- just create manually this folder, and put the folder in it, I would recommend the second solution.
 
<img width="699" alt="screen shot 2017-07-06 at 11 20 40" src="https://user-images.githubusercontent.com/7745576/27906926-6977b144-623d-11e7-94b7-58ef585e80e7.png">


Download the zip file from:
https://firebase.google.com/docs/ios/setup
Section: **Integrate without CocoaPods**

Then,
add the whole content of the folder into: RN_PROJECT/ios/Pods/Firebase

That should take in count both Frameworks and Headers.

Let me know if that doesn't work.

**Comment by dorthwein** [comment]
We ran into this issue as well - changing the reference from Firebase.h to RNFirebase.h allowed us to build.  Still working on getting everything working though

**Comment by Alex-Mann** [comment]
@cladjules This didn't work for me. Could you give a few more details on how much/little of the other parts of the install process you did?

**Comment by SamMatthewsIsACommonName** [comment]
My question is, is it possible to install WITH pods but just not the react pods specified in the documentation>? Because those are the ones that cause me problems

**Comment by cladjules** [comment]
@Alex-Mann what are the issues you have and in what project?
if the issue is now in your own project (rather than RN-Firebase), you may need to add them manually into Header Search Path (just like RN-Firebase).

In your project target:
in Header Search Path, add: $(SRCROOT)/Pods/Firebase

I forgot to mention, but did you add the directory containing the Firebase Libraries to your Xcode Project ? Just Drag and Drop the whole folder inside and make sure Copy is unchecked.

<img width="709" alt="screen shot 2017-07-18 at 12 52 02" src="https://user-images.githubusercontent.com/7745576/28315806-ffb2350c-6bb7-11e7-8763-45505558bedf.png">
<img width="302" alt="screen shot 2017-07-18 at 12 52 11" src="https://user-images.githubusercontent.com/7745576/28315805-ffb19d9a-6bb7-11e7-8738-42cb57988c19.png">

**Comment by JackThomson2** [comment]
@cladjules thank you so much. Solved my issue!

**Comment by JCMais** [comment]
I cannot for the love of me get this to work without using CocoaPods? Is there any detailed tutorial on how to get it working? It always throws linking errors.

**Comment by JulienAtanasyan** [comment]
@JCMais can you give us some details, did you follow the two previous step?

**Comment by JCMais** [comment]
I got it to work. It was some conflicts between another modules I had installed, to be more specific, `react-native-fcm` and `react-native-google-signin`.

**Comment by AndreiCalazans** [comment]
For anyone else trying to do it manually I commented on this issue the steps I took that worked for me, hope it helps.

https://github.com/invertase/react-native-firebase/issues/1016

**Comment by ArsalanReal** [comment]
> I got it to work. It was some conflicts between another modules I had installed, to be more specific, `react-native-fcm` and `react-native-google-signin`.

Oh sigh. Thanks for this great idea.
Already spent a week on it. Don't know what the hack with google for linking its own libraries.
in my case i was using both libs.

**Comment by mtx62** [comment]
I created a Folder "Firebase" in IOS folder and paste all needed frameworks + Firebase.h
and everything is working fine now.
