### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method setChannelId

### ISSUE THREAD

**Issue by gifary** [invertase/react-native-firebase#1550]
### Issue
I am getting this error when in foreground when calling function firebase.notifications().displayNotification(notification)

 FATAL EXCEPTION: Firebase-RNFirebaseMessagingService
                                                                        Process: com.hellobeauty.vendor, PID: 31477
                                                                        java.lang.NoSuchMethodError: No virtual method setChannelId(Ljava/lang/String;)Landroid/support/v4/app/NotificationCompat$Builder; in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.hellobeauty.vendor-l4ba-tSygCqU4J4gnmJX1Q==/base.apk:classes2.dex)
                                                                            at com.google.firebase.messaging.zza.zzh(Unknown Source:187)
                                                                            at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:57)
                                                                            at com.google.firebase.iid.zzc.run(Unknown Source:2)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                            at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
                                                                            at java.lang.Thread.run(Thread.java:764)

## This is my dependecies

dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    implementation project(':react-native-firebase')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-snackbar')
    compile project(':react-native-spinkit')
    compile project(':react-native-image-picker')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile 'com.android.support:multidex:1.0.1'
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.3"
    implementation "com.google.firebase:firebase-messaging:17.3.2"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'

}

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
Mac OS siera 10.13

3. Build Tools:
via terimnal using react-native run android

4. `React Native` version:
0.56

5. `React Native Firebase` Version:
^5.0.0

6. `Firebase` Module:
Firebase messaging

7. Are you using `typescript`?
No

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by gifary** [comment]
@Salakar How it's going with this issue, I am still getting this issue after update to latest version ?

Thanks

**Comment by Salakar** [comment]
Hey, the issue here is that `"com.android.support:support-v4"` needs to be version v26 or higher as that's the version most of these API's that are causing crashes were introduced. I'd imagine it was being set to a version less than this which is why removing those lines made it work.

You can see [here](https://developer.android.com/reference/android/app/Notification.Builder#setChannelId(java.lang.String)) that this method specifically was only introduced in version 26 of the dependency and is being called by Firebase internally but it doesn't exist in that version.

We do add checks in the code for build versions e.g. `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {` (26) but if the methods don't exist in the library because the version is out of date it would have crashed.

I've just added some try catches around all the methods that we've used that were introduced in v26 of the library - so it should now gracefully continue to work on v24-25 albeit without those specific notification features functioning.

However - should this error continue to keep happening then I'd suggest ensuring you're using v26 and above of the Android support library as some of these calls may be out of our control.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by gonojuarez** [comment]
the solution from them is migrate the project to androidx , that´s solve them 
you need read thats
https://developer.android.com/jetpack/androidx/migrate#migrate
