### ISSUE TITLE
firebase dependencies error

### ISSUE THREAD

**Issue by farhaantariq** [invertase/react-native-firebase#1557]
### Issue

after yesterday's update i cant build my project any more, getting this error The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

### Environment

1. Application Target Platform:
Android

2. Development Operating System:
Windows 10

3. Build Tools:
Android Studio version 3.2 AI#181.5540.7.32.5014246 built on September 17 2018

6. `Firebase` Module:
database, auth and storage

7. Are you using `typescript`?
No

**Comment by sharpercoder** [comment]
**Workaround**
I have face the same issue, it is because a recent update from firebase and play services. 
Please, update library com.google.android.gms:play-services-base: 15.0.1 to  

**compileOnly "com.google.android.gms:play-services-base:16.0.1"**

also update in app module and add at the end of file next
**com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true** 
![1](https://user-images.githubusercontent.com/37214501/46446479-8eacd980-c74a-11e8-8ab5-5c9ab313c477.png)
![2](https://user-images.githubusercontent.com/37214501/46446478-8eacd980-c74a-11e8-8b35-18a81d05dae2.png)

Notice this is not a fix, most at all if you work with CI tools like appcenter. Guys have to update libraries.

**Comment by Salakar** [comment]
The versions on master have since been updated. This will land in v5.1.0, of which I've just published the first RC for, 

`yarn add react-native-firebase@5.1.0-rc1`
