### ISSUE TITLE
Get App config

### ISSUE THREAD

**Issue by Cretezy** [invertase/react-native-firebase#164]
Using the Web SDK, this would work: `firebase.app().options.authDomain.split('.')[0]` which would return the app name (`myapp-31h2n`). How is this behavior possible in `react-native-firebase`?

**Comment by Salakar** [comment]
@Cretezy I have already done quite a bit of work in relation to `.app()` for a future release, but that's still ongoing - it's quite a big piece of work as it involves also supporting multiple app instances and firebase configuration via js side rather than the google services json/plist on the native side.

So it is in the works, but, probably not landing any time soon - August sometime most likely.

**Comment by aarongreenwald** [comment]
@Salakar this is probably something that would help me as well, depending on what you have in mind. Currently we use the web sdk, but would like to go native if possible for performance benefits. Except that we determine the firebase `projectId`, `databaseUrl`, etc dynamically* at run time so we can't have it hardcoded in a `plist` or `json` config file.

*We do this for a variety of reasons, but most importantly because we couldn't scale our app fast enough with a single project and firebase support recommended we shard into multiple projects. So we have a cluster of projects and at runtime, our apps are issued both the credentials and the config they need to connect to firebase, including the `url` and `apiKey`.

Is this something your plan would allow us to do? Something you'd like help with in the form of contributions?

By the way, great project and thanks for creating this!

**Comment by Salakar** [comment]
@aarongreenwald see my comments onwards from here: https://github.com/invertase/react-native-firebase/pull/130#issuecomment-310148642 - it's in the works

**Comment by Salakar** [comment]
@aarongreenwald we actually have an internal version of this working (but only for the iOS auth module right now - the others need some small refactoring to grab the relevant app e.g. `FIRApp * firApp = [FIRApp appNamed:appName]`) 

I'll see if i can get it up in a branch soon and open it up to contributions, currently it looks something like the below:
![image](https://user-images.githubusercontent.com/5347038/27428253-640c24d8-5739-11e7-951b-6ca669b9ce58.png)

**Comment by aarongreenwald** [comment]
@Salakar that's awesome. It would be great if you got it even partly done and available and perhaps we can help out (no promises yet, but if I have the time I'd love to help with this :-)).

**Comment by Salakar** [comment]
@aarongreenwald have started moving this over today from my internal version - will keep you updated.

**Comment by Salakar** [comment]
@aarongreenwald @Cretezy hit a SDK limitation wall with this one today. The native sdk's only seem to have multi-app support on just two of the modules - `auth` & `database` - all the other modules have no way of selecting which app is being used: 

For example: https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.html#getInstance(android.content.Context)
![image](https://user-images.githubusercontent.com/5347038/27794333-a799a37e-5ff9-11e7-8e9a-9f527717f877.png)

As you can see analytics `getInstance` does not accept an instance of `FirebaseApp` whereas `auth` does:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth.html#getInstance()
![image](https://user-images.githubusercontent.com/5347038/27794383-e68ce406-5ff9-11e7-8efb-c1892aa18e9a.png)

Not sure how to proceed on this one and if it's worth all the effort when only 2 out of the 9 modules we support can use it. Thoughts? Suggestions?

**Comment by Salakar** [comment]
Ok looked into it further, it's only just the 3 modules - storage also supports it. Have a feeling it's more of a technical limitation rather than a 'it just has not been done' issue from firebase. Have mailed a contact at firebase to clarify.

I propose we support it for the 3 modules - if you need to use the remaining modules then have them require that the default app has been initialised via plist/json file?

**Comment by aarongreenwald** [comment]
@Salakar currently, we're only using the realtime database and auth modules, so that would work for our use case. I say it's worth supporting what's possible, because it's definitely an added value.

cc @buttershub, who is now working on this on our end.

**Comment by Ehesp** [comment]
Is it worth somehow being able to detect what app the user is attempting to use on a module which doesn't support it and throw up an error if it's anything but default?

**Comment by ButtersHub** [comment]
Hi @Salaka , I saw you updated the multi-app branch, is it ready for use or it is work-in-progress?

**Comment by Salakar** [comment]
Trying to finalise this today, will report back on progress in a few hours.

**Comment by Salakar** [comment]
Almost there with this but hit a couple of firebase sdk issues again, see my comment over here: https://github.com/firebase/firebase-ios-sdk/issues/140#issuecomment-315953708

Waiting for a response before I decide to just work around the issues.

**Comment by Salakar** [comment]
Some more info of whats done:

## Examples

#### No need to js initialize natively initialized apps (plist/json) or have a singleton exported instance, import and go.
```javascript
import firebase from 'react-native-firebase';

const defaultApp = firebase.app();

defaultApp.auth().signInAnonymously().then((user) => {
  console.log('defaultApp user ->', user.toJSON());
});

// as you can see there's no need to call initializeApp for apps that have been
// initialized natively via google-services plist/json files, all natively initialized apps
// are available immediately at app run time, even if you natively initialized more apps.

// for backwards compatibility you can still call `initializeApp` for the default app - it just internally ignores initialization.
```

#### App config
```javascript
import firebase from 'react-native-firebase';

// get the default app name/options that were initialized natively
console.log("name", firebase.app().name);
console.log("apiKey", firebase.app().options.apiKey);
console.log("applicationId", firebase.app().options.appId);
console.log("databaseUrl", firebase.app().options.databaseURL);
console.log("messagingSenderId", firebase.app().options.messagingSenderId);
console.log("projectId", firebase.app().options.projectId);
console.log("storageBucket", firebase.app().options.storageBucket);
```

#### Dynamically create new firebase app instances
```javascript
import firebase from 'react-native-firebase';

const yourAppConfig = {
  clientId: 'x',
  appId: 'x',
  apiKey: 'x',
  databaseURL: 'x',
  storageBucket: 'x',
  messagingSenderId: 'x',
  projectId: 'x',
};

const anotherApp = firebase.initializeApp(yourAppConfig, 'anotherApp');

// dynamically created apps aren't available immediately due to the
// the way the react native environment works, therefore you must
// wait for an `onReady` state before calling any modules/methods
// otherwise you will most likely run into `app not initialized` exceptions
anotherApp.onReady().then((app) => {
   // --- ready ---
   // use `app` or `anotherApp` to access modules and methods
   // or you can also do:
   firebase.app('anotherApp').auth().signInAnonymously().then((user) => {
       console.log('defaultApp user ->', user.toJSON());
   });
});
```

## Notes
 - Only `auth`, `database` and `storage` modules support multiple apps on the official firebase SDK, therefore when calling a rnfirebase method on a module not listed above on any app (except for the default app) will cause an exception to be thrown.


Feedback welcome.

**Comment by Salakar** [comment]
Support for multiple apps and support for getting app config has been added in v3. Thanks for the feature request.

Will close this now. Check out the v3 change logs and docs when it lands for usage.
