### ISSUE TITLE
[expo] react-native-firebase: unable to locate React Native Android sources, ensure you have you installed React Native as a dependency and try again.

### ISSUE THREAD

**Issue by ohpax** [invertase/react-native-firebase#1697]
I have to change the location for react-native in node_module/react-native-firebase/android/build.gradle

from : 
```
    def reactNativeAndroid = new File(
      parentDir,
      'node_modules/react-native/android'
    )
```
To : 
```
    def reactNativeAndroid = new File(
      parentDir,
      'node_modules/react-native'
    )
```

otherwise I get the message in Android Studio=>
react-native-firebase: unable to locate React Native Android sources, ensure you have you installed React Native as a dependency and try again.

My package.json
```
{
    "main": "node_modules/expo/AppEntry.js",
    "private": true,
    "dependencies": {
        "apsl-react-native-button": "^3.1.1",
        "axios": "^0.18.0",
        "currency-formatter": "^1.5.3",
        "expo": "^31.0.2",
        "expokit": "^31.0.2",
        "firebase": "^4.9.1",
        "install": "^0.11.0",
        "js-base64": "^2.4.9",
        "lodash": "^4.17.5",
        "prop-types": "^15.6.2",
        "react": "16.5.0",
        "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
        "react-native-elements": "^0.19.0",
        "react-native-extended-stylesheet": "^0.9.0",
        "react-native-firebase": "^5.1.0",
        "react-native-flash-message": "^0.1.9",
        "react-native-iap": "^2.0.3",
        "react-native-keyboard-aware-scroll-view": "^0.6.0",
        "react-native-keyboard-sticky-view": "^1.0.1",
        "react-native-markdown-renderer": "^3.1.0",
        "react-native-markdown-view": "^1.1.4",
        "react-native-popup-menu": "^0.9.1",
        "react-native-radio-buttons": "^1.0.0",
        "react-native-swipeout": "^2.3.6",
        "react-navigation": "^2.18.2",
        "react-redux": "^5.0.6",
        "redux": "^3.7.2",
        "redux-form": "^7.2.3",
        "redux-thunk": "^2.2.0",
        "uuid": "^3.3.2"
    }
}
```

**Comment by Ehesp** [comment]
Assuming this is a detached expo project? Could you let us have the rest of the details please such as versions etc so we can either add to the docs or investigate.

**Comment by x86kernel** [comment]
i have same problem. it is the detached expo project with expokit.
Is this library not working with the detached expo project?

**Comment by Salakar** [comment]
@ohpax @x86kernel the custom build script I added to find Android sources (custom to allow working from mono-repos - it can go upwards multiple times until it finds RN sources) would need modifying to support the exist path and also the ExpoKit path. 

Script: https://github.com/invertase/react-native-firebase/blob/04fba7900a3ac1a6b57c149b9ade3ed7e6547f10/android/build.gradle#L85-L114


If anyone wants to make the change and send a PR over that'd be great. Otherwise it'll get looked at in due course.

Thanks

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
