### ISSUE TITLE
Installing Crashlytics on android

### ISSUE THREAD

**Issue by ShaMan123** [invertase/react-native-firebase#1884]
### Add the dependency
Add the Firebase Crashlytics dependency to `android/app/build.gradle`:
```java
dependencies {
  // ...
  implementation "com.google.android.gms:play-services-base:16.1.0" // <-- Upgrade version

  implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {  // <-- Add this dependency
    transitive = true
  }

}

```

If the build fails try adding this line at the bottom of your `android/app/build.gradle`:
```java
 // ...
 apply plugin: 'com.google.gms.google-services'
 com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true // <-- Add this line

```

**Comment by ShaMan123** [comment]
you want to edit [docs/variables.yaml](https://github.com/invertase/react-native-firebase/blob/master/docs/variables.yaml)

**Comment by Salakar** [comment]
Hey all, Crashlytics has recently had a major overhaul in https://github.com/invertase/react-native-firebase/pull/1958 - this will land as part of v6. 

As this issue no longer applies (each Firebase service, e.g. Crashlytics are now individual packages and because of this they can now manage their own dependencies internally) I will close and lock this issue.

[[The full changelog can be viewed here](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#crashlytics)]

If you have any feedback/queries relating to the PR above please ask in the `#crashlytics` discord channel or create an issue with `[v6]` in the title. 

Thanks for reporting and thanks for your patience 💛

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️
