### ISSUE TITLE
[v6] Is Auth necessary for Analytics?

### ISSUE THREAD

**Issue by JAStanton** [invertase/react-native-firebase#1955]
## Documentation Feedback

I am trying to include `@react-native-firebase/analytics` into my project but it mentions that `@react-native-firebase/app` is required in the documentation, and sure enough if I don't include the pod it will explode. Makes sense, however, `@react-native-firebase/app` appears to be bringing in Firebase Auth... I just wanted to make sure this is strictly necessary, It appears as if I were to implement this myself without this react native project I would only need to include firebase core which would give me all things analytics. 

Is including Auth strictly necessary or a remnant of how this project is organized? Is there any way to exclude this extra dependency in order to keep by the binary size smaller? 

![image](https://user-images.githubusercontent.com/645300/53902072-388fdb00-3ff5-11e9-8123-96ec04d7e9b3.png)

**Comment by JAStanton** [comment]
I would like an answer still, though I avoided this library due to the overhead, so not a blocking issue :)

**Comment by Ehesp** [comment]
Hello

The tests have just been run against this and you're right. It doesn't require the auth pod so that's a mistake on our end. We'll publish a new v6 alpha version tomorrow to sort.

**Comment by Salakar** [comment]
Hey @JAStanton thanks again for raising this issue. 

I've removed the auth pod from App and have published `6.0.0-alpha.8` to npm under the alpha tag. 

While it is labelled alpha it is far from alpha status, and is more like an RC - alpha tagged as each of the Firebase packages require all their versions to be the same and a few of the modules have not yet made it into v6. See the v6 changelog for a complete list of modules that are 'ready': https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md

For context on why the Auth pod is in their in the first place: Firebase/Core <-5.17 would fail to build without it, this was fixed in 5.19 which is now the version these are on.
