### ISSUE TITLE
Firestore multiple where clause with same field

### ISSUE THREAD

**Issue by willbrid** [invertase/react-native-firebase#2016]
Hi. 
I'm using react native firebase ^5.1.1 in my react native project (version 0.57.8). I have a problem since two days when i'm trying to query between two dates in timestamp with firestore. 
Here is my piece of code below.

`
let query = firebase.firestore().collection(path).where("createdAt", ">=", begin).where("createdAt", "<=", end).limit(limit).onSnapshot(callBackSuccess, callBackError)
`

begin and end are the timestamp dates.
I have configured react native firebase and all my other queries work very well. But with this query above, I get an empty array. I tell myself that I am doing my request badly. Please is there a better way to achieve this ? 
Please help me to solve this problem. Thank you.

**Comment by mikehardy** [comment]
Curious if maybe you updated Firestore?
https://firebase.google.com/support/release-notes/android#2019-01-25

Cloud Firestore version 18.0.0
The timestampsInSnapshotsEnabled setting is now enabled by default. Timestamp fields that read from a DocumentSnapshot are now returned as Timestamp objects instead of Date objects. This is a breaking change; developers must update any code that expects to receive a Date object. See FirebaseFirestoreSettings.Builder.setTimestampsInSnapshotsEnabled() for more details.

https://github.com/invertase/react-native-firebase/issues/1869#issuecomment-460889744

may be totally unrelated but the incompatibility is with timestamp vs date and you are in that area with createdAt...

**Comment by willbrid** [comment]
Thank you for your response. 
I do not remember having updated firestore. I just install react-native-firebase with npm and configure it.
I'm taking date like a number. Before storing date in firestore, i convert it in timestamp (client side) and then manipulate it as a usual number. So i'm not using firestore settings to do that.

**Comment by willbrid** [comment]
Hi i solved the problem. it was my fault, I used time in number in two different ways: one in millisecond for saving and another in unix for querying. My sincere apologies.
