### ISSUE TITLE
React Native 0.59

### ISSUE THREAD

**Issue by JohnnyDevX** [invertase/react-native-firebase#2062]
I can see in Supported Versions table for firebase 5.3.x that its for RN ^0.56 - ^0.58.

I have already started a project in 0.59, can I still use this library?

**Comment by salmazov** [comment]
It's very important question for me too, because I have such erro:
`Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
2019-04-16 09:52:09.723321+0300 MyApp[3767:27165] 5.9.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
2019-04-16 09:52:09.731154+0300 MyApp[3767:26898] *** Terminating app due to uncaught exception 'com.firebase.core', reason: 'Name cannot be __FIRAPP_DEFAULT.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000115b821bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011511c735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115b82015 +[NSException raise:format:] + 197
	3   MyApp                     0x000000010df16cb8 +[FIRApp configureWithName:options:] + 312
	4   MyApp                     0x000000010e1a9e33 __45-[RNFirebase initializeApp:options:callback:]_block_invoke + 1187
	5   MyApp                     0x000000010e2c0f8d __RCTUnsafeExecuteOnMainQueueSync_block_invoke + 29
	6   libdispatch.dylib                   0x0000000117587602 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00000001175957be _dispatch_async_and_wait_invoke + 176
	8   libdispatch.dylib                   0x0000000117587602 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x000000011759499a _dispatch_main_queue_callback_4CF + 1541
	10  CoreFoundation                      0x0000000115ae73e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x0000000115ae1a76 __CFRunLoopRun + 2342
	12  CoreFoundation                      0x0000000115ae0e11 CFRunLoopRunSpecific + 625
	13  GraphicsServices                    0x00000001186181dd GSEventRunModal + 62
	14  UIKitCore                           0x000000011ef1a81d UIApplicationMain + 140
	15  MyApp                     0x000000010deb2700 main + 112
	16  libdyld.dylib                       0x00000001175fd575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

When I use RNFirebase with React Native 0.59.4

**Comment by mikehardy** [comment]
Actually I'm not sure that table is correct, it appears that for react-native-firebase 5.3.1 you need 0.59.3+ based on other issues

@salmazov stop hijacking threads it is unhelpful open source behavior, log a fresh issue with your own information following the template

**Comment by Salakar** [comment]
Sorry the docs weren't correctly up to date - please see the v5.x.x docs - there shouldn't have been a v5.3.x docs branch 🙈 

![image](https://user-images.githubusercontent.com/5347038/56851258-dcff1100-6904-11e9-95b5-84f19d3fcdf2.png)
