### ISSUE TITLE
I want to show image in push notification it’s possible ?

### ISSUE THREAD

**Issue by vaibhav22c** [invertase/react-native-firebase#2070]
My all text notification working fine while app is open, background or close
But I wan’t to show image in notification.

While my app open then I set `big_picture` in my `onNotification` code so its working fine but App in background or close then image is not showing.

**Comment by RameshAmzur** [comment]
Hi @vaibhav22c  
Did you find any solution.

Thank you.

**Comment by vaibhav22c** [comment]
@RameshAmzur  No it's still pending

**Comment by mikehardy** [comment]
It is possible but the chain is: send silent push -> handler creates a rich notification -> handler posts the notification

**Comment by vaibhav22c** [comment]
when my app foreground then I manage but while close(kill) then how to handle  notification

**Comment by mikehardy** [comment]
You haven't followed the template at all so I'm not even sure what platform you mean. I will guess Android, so the only way is to use silent push notifications. That way you get a chance to handle them instead of having them go to the system tray. Then in the background headless task that handles your messages, you construct a notification and post it. This is all in the docs but it is not easy to get right. Good luck.

**Comment by vaibhav22c** [comment]
I'm using react native

**Comment by mikehardy** [comment]
Of course you are or you wouldn't be here :-), this is the template you deleted / avoided: https://github.com/invertase/react-native-firebase/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md
