### ISSUE TITLE
notifications_notification_opened not register when app is open from notification response

### ISSUE THREAD

**Issue by siggj** [invertase/react-native-firebase#2189]
## Issue

Hello, 

I missed something I guess with bridge notion and notification response.

I use action buttons and execute some code when user press on it.

When app is terminated and user press buttons in notification, the app wake up but i have a message "RCTEventEmitter sendEventWithName Sending notifications_notification_opened with no listeners registered."

It happens always when app wake up from terminated state
And the job come from "pendingEvents" in RNFirebaseNotification and is executed when js is ready

---

### iOS

<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [ ] I'm using Pods

</p>

## Environment

<p>

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  
</p>
---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You didn't really follow the template, and for something like this we'd really need to see a reproducible demo. If you could make a public repo on github with a minimal reproduction that would help. Just as a guess you haven't registered an onNotificationOpened listener, or one of the other 4-5 listeners you need for all the various ways a notification or message can be hooked

**Comment by siggj** [comment]
@mikehardy Thanks for your answer. 

I register listener like follow. Everything is working when app is foreground or background.
But when app is closed and wake up from user notification tap. I think app do not register listener. 

```
constructor(props) {
 console.log(PushControllerIOS constructor);
 super(props);
 this.configureFirebase();
}

componentWillUnmount() {
 this.notificationDisplayedListener();
 this.notificationListener();
 this.notificationOpenedListener();
}

configureFirebase() {
 console.log("Push Controller configureFirebase");
 firebase.notifications().ios.shouldAutoComplete = false;
 firebase.notifications().getInitialNotification()
   .then((notificationOpen: NotificationOpen) => {
       console.log("Push Controller getInitialNotification");
       if (notificationOpen) {
        // App was opened by a notification
        // Get the action triggered by the notification being opened
        const { action, notification } = notificationOpen;
        notification.ios.complete(() => {
          console.log("Push Controller notificationOpenedListener completed");
          });
});

this.notificationDisplayedListener = firebase.notifications().onNotificationDisplayed(async (notification: Notification) => {
      // Process your notification as required
      console.log("Push Controller onNotificationDisplayed");
});

this.notificationListener = firebase.notifications().onNotification((realNotification: Notification) => {
      // Process your notification as required
      // app si opened, foreground
      console.log("Push Controller onNotification");
      firebase.notifications().displayNotification(realNotification);
});

this.notificationOpenedListener = firebase.notifications().onNotificationOpened(async (notificationOpen: NotificationOpen) => {
      // Get the action triggered by the notification being opened
      const { action, notification } = notificationOpen;
      console.log("Push Controller notificationOpenedListener");
      notification.ios.complete(() => {
        console.log("Push Controller notificationOpenedListener completed");
      });
    });
}
```

**Comment by mikehardy** [comment]
You still did not really follow the template. Are you sure this is iOS? Because iOS really only has "foreground" and "stopped" as far as I know. Android has 3 states and you need to registerHeadlessTask to handle one of them. But without following the template or showing a reproduction (not just code in the textbox here, but an actual reproduction) I'm not sure. You can base it off this if you like - it builds a quick sample app but has no App.js code: https://github.com/mikehardy/rnfbdemo

**Comment by siggj** [comment]
Ok you are right but according to this documentation : https://rnfirebase.io/docs/v5.x.x/notifications/introduction

IOS have 3 state too.. (App in foreground - App in background - App closed).

What i guess is when app is terminated/killed/closed, getInitialNotification is populated if the notification is tapped and opens the app.

But when I click in the notification. I only see log from IOS part, not RN part.

**Comment by mikehardy** [comment]
I have had issues with getInitialNotification as well but haven't been able to pin them down - that's the whole point of that rnfbdemo repo - I'm going to have a full demo of all the notification features in there partially as a way to explore how they work (for me) and partially as a way to easily demonstrate failure (and allow for quick fixes) if I discover they aren't behaving correctly. If you have a case right now not working, please add in there - I want it to be super simple (all contained in App.js just buttons and text to make things happen and show results) and I'm just intending to have the App.js live in the project root and copy it in after example init. Should be easy to show problems.

**Comment by siggj** [comment]
@mikehardy Thanks for your time. I appreciate that.

I will adapt the rnfbdemo and push it to make it easily.

Just a question : when a user tap on a button in a notification when app is not killed. Normally, it pass in didFinishLaunchingWithOptions and then launch react-native ?

**Comment by mikehardy** [comment]
That's a good question, I'm not sure of the underlying iOS handler but it is supposed to flow like so in javascript https://rnfirebase.io/docs/v5.x.x/notifications/receiving-notifications#4)-Listen-for-a-Notification-being-opened

Chasing through the iOS code that react-native-firebase registers, and that is then registered from the firebase iOS SDK should be possible

**Comment by mikehardy** [comment]
Oh, and I will be thrilled to take pull requests that cleanly demonstrate *any* notification or messaging functionality for rnfbdemo, I'd love to have clean examples to point people too - there are so many issues opened here that are related to messaging and notifications because it's a difficult subject, and I think nothing explains things better than a working demo. Thanks!

**Comment by mikehardy** [comment]
If anyone has combined react-native-splash-screen with react-native-firebase, and they implemented the splash screen with a separate launch activity, this will happen. There are workarounds but you should use splash-screen with a single Activity and it just works. Code here: https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

**Comment by Srinidhi1561997** [comment]
I'm new to react-native, i'm developing a messaging app in that when the push notification comes if i click on that it is taking me to the home page but not to chat window. This is case only when app neither in background nor active. Please help me with this. I'm doing it in windows 10 for android.

**Comment by Srinidhi1561997** [comment]
:when the app is not in background/killed/not open, then on tapping push notification takes the user to Homescreen, need to change deeplinking logic and take the user to chatScreen

**Comment by mikehardy** [comment]
@Srinidhi1561997 have you verified that you are not having an integration issue with another module, where the react-native-firebase listener is not integrated with the java object that is set in AndroidManifest as your LAUNCHER activity? https://github.com/invertase/react-native-firebase/issues/2189#issuecomment-502406917

**Comment by Srinidhi1561997** [comment]
Hi @mikehardy, no i wasn't facing any issues for the integration purpose my app is working fine in all the androids and ios. Only issue i'm facing is when i click on the push notification it's not taking me to the chat window rather than it's taking me to the home page, this happens only when my app was killed/ inactive/ not running in background.

**Comment by mikehardy** [comment]
@Srinidhi1561997 please open a new issue following the template with full information, especially AndroidManifest.xml / MainApplication / MainActivity / package.json / both build.gradle, however I still suspect something like maybe for that case you just have to use initialNotification in order to navigate correctly on app open: https://rnfirebase.io/docs/v5.x.x/notifications/introduction#Remote-Notifications - see the case for android in the background? It doesn't happen automatically you have to code it. However, if you find that getInitialNotification is not being populated then something about the chain of click-to-launch-activity with the Intent populated correctly is broken and it is likely similar to the problem many experience with react-native-splash-screen (where tutorials leave you in a state where your launch activity is not the firebase activity, so the intent doesn't have the info to populate the initial notification)

**Comment by Srinidhi1561997** [comment]
Yeah sure

**Comment by Srinidhi1561997** [comment]
When you are free let me know please
