### ISSUE TITLE
Google Analytics fails when try to use logEvent(event, objEvent)

### ISSUE THREAD

**Issue by AugustoAleGon** [invertase/react-native-firebase#2221]
## Issue

I am using Google Analytics to track events in my app, the main problem is so far that I don't see that it is working on some cases, for Android and iOS is the same.

I have a function like this:
```
import firebase from 'react-native-firebase';

const trackEvent = (event, objEvent) => {
	try {
		firebase.analytics().logEvent(event, objEvent);
	} catch (error) {
		console.warn(`analytics_${ event }_fails`);
	}
};

export default trackEvent;
```

Describe your issue here:
---
I am getting in some parts warn logs. What is going on with the function?

## Environment

**`react-native info` output:**

```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 112.66 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: ^0.58.6 => 0.58.6
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [X ] Both
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

**Comment by mikehardy** [comment]
Sorry, this isn't quite information to go on. However, I know analytics works, I use it all the time. You can check react-native-firebase-starter or you can try https://github.com/mikehardy/rnfbdemo - both show you sample apps where analytics will work if you set up your project and add some calls. You may need to follow the firebase documentation to enable debug view so there's no lag and you can be confident it's working

https://firebase.google.com/docs/analytics/debugview

**Comment by fang0rnz** [comment]
Hey @mikehardy I'm having some problems as well that I think could be related to this issue.
I'm sending this hardcoded object to logEvent and seeing inconsistent values on firebase's DebugView. It omits multiple random properties every time I send the action, sometimes it omits a property, sometimes multiple properties, there's no clear pattern. And as I said, I'm sending a hardcoded object, nothing is changing. Could this be related to DebugView? I tried a lot of things and I'm starting to run out of ideas.

`firebase.analytics().logEvent('add_to_cart', {
    quantity: 1,
    item_name: 'Vitin',
    item_id: 'dshjfsahd',
    value: 30,
    price: 30,
    currency: 'BRL'
  });`

**Comment by mikehardy** [comment]
I updated your comment with the nifty triple-tick + language code markdown block quite trick :-)

This looks like a reasonable test, and I'm not sure why that wouldn't be working for you. Seems as simple as it can get. I hate to possibly send you on a wild goose chase but have you tried it with either the firebase JS SDK (not native), or the firebase native SDK directly? You may be able to try each quickly in your app as it's already javascript for a quick include there, and for android you can reference the native SDK APIs directly in your MainApplication just to try it.

**Comment by fang0rnz** [comment]
Thanks for your answer @mikehardy 
I just checked and it seems that the js sdk doesn't support analytics :/.
As for the native sdk, I'm not familiar with calling native methods on react native, could you point me to something I could read and learn?
Yeah it is pretty weird, I've been digging around this bug for days and haven't found a clear pattern or reason.

**Comment by mikehardy** [comment]
That's probably because for JS they just expect you to use their standard analytics package - I don't have much experience with that but it's not firebase-specific I don't think? You just need to use your firebase analytics UA code I think? For the Java side you would just cut out the react-native-firebase layer and directly hit the SDK analytics APIs - https://github.com/invertase/react-native-firebase/blob/master/packages/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java#L43

**Comment by fang0rnz** [comment]
Hi Mike!
I haven't had time to look for alternatives yet, but I did some research in order to make sure the problem wasn't at my end. I cloned https://github.com/invertase/react-native-firebase-starter and did the same thing I'm doing at my company's app and the results are exactly the same. I think either DebugView could be broken or something we don't know yet in this library.
I've recorded a video of it:
https://streamable.com/a5hlf

I could also upload the repro code if you want to investigate, but the only thing I did was change ios firebase config file stuff and call the function.

**Comment by mikehardy** [comment]
Very interesting - well it seems like you've isolated at least "your app" from the equation (though your API call was so clean already...). So that's something. I'll be curious to see if short-circuiting some of the other layers (react-native-firebase cut out by referencing the SDK API directly, or even the SDK by referencing the javascript API, or using a 3rd party google analytics client) will make a difference. You might try posting on stackoverflow if you haven't already, and/or try the firebase github - they are responsive there
