### ISSUE TITLE
Remote Notifications on IOS stop working after killing app, restarting

### ISSUE THREAD

**Issue by ElixirMike** [invertase/react-native-firebase#2401]
I have successfully setup remote notifications on both Android and IOS.. For Android, everything works as expected, no issues there.

For IOS, I have the code which checks permissions, and if not granted, requests permissions.
When I do a clean deploy to my test Iphone (physical device), the first time I log into app I receive the request for permissions and I grant it. And the notifications work great...with app in both foreground and background.

However, If I kill the app, restart it (it auto-logs me back in)...the notifications no longer work.
At this point, I'm dead in the water. Logging out, back in doesn't work. I have to uninstall app, re-install app, and get the check permission again.

I have tried to always call RequestPermission() in the ComponentDidMount, but once they have been granted, it never shows a prompt again.

Is there something I'm missing here?  Considering it works on the first deploy, it seems I have it configured correctly, but why am i losing notifications when app is restarted?

**Comment by uguraktas** [comment]
I have a some problem

**Comment by Silverdisc** [comment]
I encountered a similar issue on my end about a month ago, but it didn't seem to occur on every single install. If I remember correctly, the issue was a race condition that invalidated FCM tokens in Google's Firebase library. I'm pretty sure that updating my Podfile like the following solved the issue:

`pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/DynamicLinks', '~> 6.3.0'`

Not 100% sure if this is what you are experiencing, but if your Firebase libraries are out of date, this might be worth a shot.

**Comment by mikehardy** [comment]
note they are on 6.6.0 now, and 6.3.0 has a crash bug with iOS 13. Really appreciate any time someone reports new information based on real world experience or testing though, it helps everyone

**Comment by Silverdisc** [comment]
Ah, thanks for the heads-up! Time to update to 6.6.0 then.

I had some more time to refresh my memory- I was referring to this fix on 6.1.0:

> Fixed a race condition where checkin was deleted before writing during app start, causing notifications to not be delivered correctly. (#2438).

So if you're using an older version, give updating to the newest iOS Firebase version a shot.
