### ISSUE TITLE
AdMob Not Working On FireTV Devices

### ISSUE THREAD

**Issue by Rob2k9** [invertase/react-native-firebase#2493]
Trying To Load My AndroidTV App Onto A New Amazon Fire Stick And I Get An Error Saying The App Requires Google Play Services To Work Properly But This Was Not An Issue When Using 

React-native-admob any one else have this issue

**Comment by mikehardy** [comment]
firebase requires not just play services, but reasonably up to date play services

This is not a react-native-firebase issue, it's a requirement of the underlying SDK - you can google around for information although the main documentation doesn't say it

https://groups.google.com/forum/#!topic/firebase-talk/DSv0wUXXY0o

I'd suppose that since there is a JS library you could use instead of react-native if you needed to support non-play-services devices but that's not this module either
