### ISSUE TITLE
BoringSSL-GRPC  not installing 

### ISSUE THREAD

**Issue by usmaniqbal998** [invertase/react-native-firebase#2564]
after setting up firebase on ios side when i do "pod install" it is unable to install BoringSSL-GRPC . it takes hours to load and than shows an error that unable to install BoringSSL-GRPC

**Comment by Ehesp** [comment]
Please follow the issue template so we know what versions you're using.

**Comment by mikehardy** [comment]
Also I'd say just a network issue, plus this would actually be a cocoapods problem, nothing specific to react-native-firebase. It loads just fine for me and is not even that big (though some of the firebase ios sdk pods are) 

```
(virtualenv) mike@kunashir:~/work/Kullki/ksocialscore/packages/public-app/ios/Pods (lerna-import) % du -sh BoringSSL-GRPC/
 15M	BoringSSL-GRPC/

```

**Comment by jessalbarian** [comment]
I had the same issue after upgrading to Catalina and was able to resolve it by:

1. `brew install ruby`
2. `sudo gem install -n /usr/local/bin cocoapods`
3. Remove the versions on Firebase/Core and Firebase/Firestore:
_Before:_
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Firestore', '~> 5.20.1'
_After:_
pod 'Firebase/Core'
pod 'Firebase/Firestore'

4. Delete your Pods folder
5. Then run `pod install`

**Comment by mikehardy** [comment]
@jessalbarian that is dangerous advice, it will result in non-reproducible builds because no version is specified. I maintain a version I just use a modern one, for me that's 6.11.0 now but for react-native-firebase v6 I can't verify if pods newer than 6.9.1 work or not (they issued breaking changes to MLKit in 6.10 which don't affect react-native-firebase v5 since it had no MLKit dependencies but may affect react-native-firebase v6 if you use MLKit - I don't so I am not sure). After increasing pod versions I always like to do an `npx react-native-clean-project` to make sure I'm not going to have strange Xcode caching issues, then I'm set.

**Comment by jessalbarian** [comment]
@mikehardy  I just checked again by putting back the version numbers, and I was able to get passed the BoringSSL-GRPC stall, and you're right. I updated my answer :)

**Comment by sorxrob** [comment]
Looks like this is a region issue. Using a vpn works.

**Comment by swushi** [comment]
Just tagging on here to say that VPN is the solution for me. Specifically VPN'ed into New York.
