### ISSUE TITLE
Version 5.4.0 with 0.60

### ISSUE THREAD

**Issue by HubertRyanOfficial** [invertase/react-native-firebase#2577]
The version react native firebase it works with 0.60 react native?

**Comment by Ehesp** [comment]
Yes it does. You may want to look into https://github.com/mikehardy/jetifier for AndroidX support.

**Comment by mikehardy** [comment]
I would quickly note though that until you get to firebase iOS Pod version 6.8.1 you still might be using the deprecated iOS UIWebView symbols in any app you generate for the Apple App Store, and they are issuing "we will reject apps with these symbols" soon warnings. In order to use 6.8.1 pods, you need to upgrade to react-native-firebase v5.5.x (currently v5.5.6).
