### ISSUE TITLE
[REQUEST] Firebase Storage: putData(), download URLs without touching fs

### ISSUE THREAD

**Issue by fungilation** [invertase/react-native-firebase#260]
Great library covering all of Firebase you got here!

I'm looking for a way though, to put and get large JSON or text blobs that I want to store outside of the database. Is there a way to upload and load such text strings without involving unnecessary files on local filesystem on device?

For upload, it seems this would involve `putData` instead of `putFile` this library currently supports: https://firebase.google.com/docs/storage/ios/upload-files#upload_from_data_in_memory

For download, it could be by generating a download URL, and then running RN's fetch() for it?

Pointers welcome, if this is already possible without requiring more library support to put and get files in Firebase Storage. http://invertase.io/react-native-firebase/#/modules/storage refers to local paths, but I don't see how I can use local paths without using another library to enable such use, and I'd really like to minimize library dependency, besides writing and reading from disk when it's not necessary.

**Comment by chrisbianca** [comment]
@fungilation You're right, this isn't supported by react-native-firebase right now, partly through nobody asking for it yet and partly because we were concerned about the performance impact this might have.

Sending a large amount of JSON or text across the RN bridge between the JS code and the native code is fundamentally slow (in relation to the rest of RN) and as such a performance issue.

We will be happy to look at adding support for `putData` as part of a future release, or welcome a PR to add the functionality yourself, but I wanted to explain our rationale for not supporting it already.

**Comment by fungilation** [comment]
That's fair. And I figured it's not so bad if I can deal with local files to make it work, so I did. But I can't make `putFile` to work either, am I missing something?

I wrote my test code at https://github.com/invertase/react-native-firebase/issues/170#issuecomment-316345243

**Comment by Salakar** [comment]
@fungilation would you mind creating this request over at https://react-native-firebase.canny.io/feature-requests

And we can continue discussion on this there etc at a later date.

Thanks

**Comment by fungilation** [comment]
Done

**Comment by Salakar** [comment]
Awesome, thanks
