### ISSUE TITLE
Storing Pushed Notifications Locally?

### ISSUE THREAD

**Issue by mcampsall** [invertase/react-native-firebase#261]
Is there a way to store push notifications locally?

I just want the user to be able to see a list of all the notifications sent (Android and iOS)

**Comment by Ehesp** [comment]
You're best handling this on the server. When you trigger a push also store
it on the db and read that from the device.

**Comment by mcampsall** [comment]
So, there is no way to read the data from the notification and store it?

**Comment by Ehesp** [comment]
Yes but you cant handle that with JS if the app isn't running or they swipe
it away.

On 18 Jul 2017 5:55 pm, "Michael Campsall" <notifications@github.com> wrote:

So, there is no way to read the data from the notification and store it?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/invertase/react-native-firebase/issues/261#issuecomment-316127637>,
or mute the thread

**Comment by mcampsall** [comment]
ah ok, thanks for your response =)
