### ISSUE TITLE
🔥 Why can't we use putString(base64...) instead of putFile?

### ISSUE THREAD

**Issue by pierroo** [invertase/react-native-firebase#2625]
## Issue

I am facing lots of issues trying to get a filePath to upload to firebase storage.
it works in 99% of cases, but sometimes it just can't find a filePath (from using imagePicker for example) and it crashes the app when using putFile.

In the past, with web firebase, I could use "putString" to upload a base64 image; no more hassle trying to guess issues with filePath.

Can we no longer upload base64 image into jpeg?

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting - if the only API is truly a file path then no, that won't work reliably on Android because you are supposed to go through the ContentResolver and use a content:// URI in order to handle (for example from image picker) virtual-backed content like photos from picasa or whatever.

Can you make a link to docs on rnfirebase.io to the exact API you are using? I assume it is this? https://rnfirebase.io/docs/v5.x.x/storage/reference/Reference#putFile

If so, you might want to handle this by doing a temporary copy into your local app cache so that you can reliably convert from content to file URI - which is otherwise not recommended but once you have it in your local application storage should work?

It appears that in react-native-firebase v6 what you want is possible https://invertase.io/oss/react-native-firebase/v6/storage/reference/reference#put (though if you are using notifications and/or messaging modules, v6 won't work for you yet)

**Comment by mikehardy** [comment]
On Android the ContentResolver is the abstraction layer between what used to be just files and your code, and what became "maybe files? maybe some network resource that isn't local? maybe something dynamic from another app?" and your program. That's why you can't always resolve a "file", because the file may not be backed by bytes on disk. google up the Android docs on that one because you'll need it to make the temporary copy

You'll have to set up the streams yourself (note that files backed by content URIs and not local files can still give you an OutputStream) but here's a copy implementation I wrote and tested myself and works on 1MM+ devices inside the same API range as react-native, so I know it works well https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/compat/CompatV15.java#L225

And here's a great way to create a temp file in Android https://stackoverflow.com/a/6485850/9910298

So if you get the output stream from your maybe-not-on-disk object, and create a temp file and get an input stream to it, then do the copy, then feed the temp file's name to Storage.putFile you are all set.

Easy? not really but it is all well-understood at least. And the method you want does exist in react-native-firebase, just only in v6. If you aren't using messaging or notifications (they aren't ported to v6 yet) then maybe the time is better spent getting your app on react-native-firebase v6 and just going for it there?

**Comment by pierroo** [comment]
@mikehardy thank you for this very detailed answer.

Unfortunately, it seems like this method is written in Java, when I am using react and have absolutely zero knowledge how I should implement your method to properly get a file to upload. :(

Same for the second link on creating temp file, it doesn't seem to be written for react native.

So, if I manage to create a temp file in android, will it be enough to putFile it? Without the need for your first method?


As for v6, I don't use messaging nor firebase notification, so I could actually update to this version, I'm just scared this would break something for it seems to be a bit "beta" as of now, and I have more than half a million users monthly who would show no mercy if the app breaks somehow on some device :/

**Comment by Salakar** [comment]
> I'm just scared this would break something for it seems to be a bit "beta" as of now

v6 is actually way more tested than v5 🙃 also its not been announced yet - but the official v6.0.0 release is now published to NPM, announcement & blog post to come on Thursday

**Comment by mikehardy** [comment]
@Salakar that's cool re v6! You guys must be excited

**Comment by mrousavy** [comment]
Sorry for commenting on a closed issue, but does the `putString` function work with the newest RN Firebase version? I'm receiving base64 PNG data from an SVG (by calling the `svgRef.toDataURL()` function), and I have no idea how I could store that.

**Comment by mrousavy** [comment]
@mikehardy Sorry for commenting on a closed issue, but does the `putString` function work with the newest RN Firebase version? I'm receiving base64 PNG data from an SVG (by calling the `svgRef.toDataURL()` function), and I have no idea how I could store that.

**Comment by mikehardy** [comment]
with apologies @mrousavy I have no idea, I haven't integrated storage in my work project (yet) and wasn't involved in authoring or maintaining any part of it yet so have no direct experience with the API. I can only recommend the docs, issues list and a quick prototype test (where I can at least offer https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh). If there is any difference between docs and behavior though I'll be happy to merge PRs as ever

**Comment by mrousavy** [comment]
@mikehardy Okay I've done a lot of trial and error and found out that base64 actually works. The string was just weirdly formatted from the SVG's toDataURL function (in case anyone else is experiencing this: remove linebreaks!!)

I'll create a PR for the docs that should add some explanation when I find some time. 👍
