### ISSUE TITLE
For iOS: Notifications actions (text input and buttons)

### ISSUE THREAD

**Issue by imbudhiraja** [invertase/react-native-firebase#2735]
I want to integrate iOS notification actions similar to android but i neither found any thing related to iOS actions in react-native-firebase nor any feature request

Android Actions
https://rnfirebase.io/docs/v5.x.x/notifications/android-actions

This other package allows this:
https://github.com/evollu/react-native-fcm/pull/773

react: 16.8.6 => 16.8.6 
react-native: ^0.60.5 => 0.60.5 
react-native: ^6.0.0
Thanks

**Comment by mikehardy** [comment]
Right, and in the README there it says:

`I'm not longer able to maintain this repo. check react-native-firebase instead`

You should subscribe to #2566  and especially read: https://github.com/invertase/react-native-firebase/issues/2566#issuecomment-541109278

Which is to say, v5 notifications in react-native-firebase will not see major modifications, there are not any other really "alive looking" options, and v6 notifications is not out yet. When v6 notifications is out it will likely require a fee for use because - referencing all of the above - it's a *really* difficult API area to cover and no one that's attempted it for free has done so sustainably
