### ISSUE TITLE
Problems with methods messaging().onMessage or notifications().onNotification

### ISSUE THREAD

**Issue by SkyPeer** [invertase/react-native-firebase#2746]
Hello, 
could you help please....
after iOS13 update all push processes by callback:
firebase.messaging().onMessage 
or 
firebase.notifications().onNotification
by random! 
unfortunately, if the push is processed by firebase.messaging().onMessage, it is not displayed

on iOS12 and Android everything works correctly
we using "notifications" and "RemoteMessage" types, and all pushes are processed by callbacks depending of push type.

pod:
  pod 'Firebase/Core', > 6.3.0
  pod 'Firebase/Messaging', > 6.3.0
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

package.json:
"react-native": "^0.59.10",
"react-native-firebase": "^5.5.6",
XCode 11

**Comment by eftikharEmad** [comment]
any update ?

**Comment by mikehardy** [comment]
Not really, I scanned it but it's on an older react-native and doesn't include code or anything, notifications and messaging are notoriously difficult to support since everyone does them differently and it didn't look like it matched my code or had enough info to puzzle it out, so I took a pass, sorry. You have any update?
