### ISSUE TITLE
I've got several error for running app

### ISSUE THREAD

**Issue by jsina** [invertase/react-native-firebase#2751]
I follow the doc android installation but I've got this error:
```
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.4. If using the gradle wrapper, try editing the distributionUrl in /Users/jsinamaleki/Documents/project/hitalent/clientapp/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip
```
also after I've installed `gradle-5.1.1-all.zip` to resolve this I've got this error:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Conflicting configuration : 'armeabi-v7a,x86' in ndk abiFilters cannot be present when splits abi filters are set : x86,armeabi-v7a
```
I'm using `"react-native-firebase": "5.2.1"` and here is my react-native info:
```
 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 190.00 MB / 8.00 GB
      Shell: 2.6.0 - /usr/local/bin/fish
    Binaries:
      Node: 10.16.0 - ~/.config/fnm/bin/node
      Yarn: 1.19.1 - ~/.yarn/bin/yarn
      npm: 6.11.3 - ~/.config/fnm/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.1, 28.0.3
        API Levels: 16, 21, 23, 25, 26, 27, 28, 29
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by mikehardy** [comment]
With apologies, you did not really follow the template - so I should close this with nothing more than a comment to that effect - but from what I see you're running versions of things that aren't worth supporting - react-native-firebase less than v5.5.x is effectively worthless as the underlying SDKs have breaking changes only handled by that branch, but their most recent versions are required in order to publish to the play store, so you really must upgrade. But you can't use react-native-firebase v5.5.x unless you are on react-native 0.59.3 at least (0.59.10 is better but really getting to 0.61.2 is worth it)

it's a lot of change to ingest but staying on older underlying code doesn't work in a stack with so many layers (firebase sdks, react-native-firebase, react-native)
