### ISSUE TITLE
Background Message Handler not firing

### ISSUE THREAD

**Issue by atillabirer** [invertase/react-native-firebase#2819]
My code is something like this:

```javascript
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import firebase from "@react-native-firebase/app";
import AsyncStorage from "@react-native-community/async-storage";

const backgroundHandler = async (message) => {
    // handle your message
    console(message)
    return Promise.resolve();
}
AppRegistry.registerComponent(appName, () => App);
firebase.messaging().setBackgroundMessageHandler(backgroundHandler);


```
I am sending a notification from Firebase Console using the Notification Composer and filling the custom data fields. I saw 1 background notification processed but then never again. I tried anything from clicking all notifications to scheduling, killing restarting app etc. I am struggling to get a background notification console.log'd even though it fired one time before with the same code.

**Comment by mikehardy** [comment]
We really need you to follow the template in order to help
I register my background handlers before I register the app, for what it's worth

Also, you can format code with language tags and it's even prettier :-)

We can re-open if you fill out the template but in general I would advocate using your own test script and the REST API so you have full control over your notification. See this entire thread, note the example script, and how success was achieved: https://github.com/invertase/react-native-firebase/issues/2796
