### ISSUE TITLE
RNF Notifications V6

### ISSUE THREAD

**Issue by LukePenkava** [invertase/react-native-firebase#2878]
So since the official thread for V6 Notifications, which is linked by your website, is now locked, i didnt know what else to do than create new one.

I am planning to release app next week, and i need to get local notifications working. I was wondering if the ETA is more like 2 weeks or 2 months. I can live without local notifications for few more weeks during release and implement it a bit later with your package, but if the ETA is 2 months or so, i have to go with other solution. It would be just great to get any update on what the ETA is. Thanks.

Just a side note. Someone gave you some more or a less valid criticism on how you are handling the release of this package, you deleted his message and locked the official thread, which is linked from your Notifications package. I think that could have been handled way better and perhaps some of the concerns could have been addressed instead of shutting people down.

**Comment by Ehesp** [comment]
> I am planning to release app next week, and i need to get local notifications working.

Use an existing solution (or v5). Basing functionality on something unreleased is generally a bad idea anyway, especially given its still WIP.

> I was wondering if the ETA is more like 2 weeks or 2 months.

We're not committing to a date because it's finger in the air for us. This library (and a notifications one) is one of many projects we work on so it's a catch 22; to sustain working on a notifications library we need to work on other projects to make money, which eats into the time we can work on OSS/other projects. 

We'd love to dedicate more time into working on it, but it's not sustainable :'(

> Just a side note. Someone gave you some more or a less valid criticism on how you are handling the release of this package, you deleted his message and locked the official thread, which is linked from your Notifications package. I think that could have been handled way better and perhaps some of the concerns could have been addressed instead of shutting people down.

We don't delete comments unless they're offensive (unfortunately we get a few every now and then). I think I saw the one you're on about, but the author of it deleted it as it just vanished. If we delete them it still shows in the list as deleted.

**Comment by Ehesp** [comment]
I'll close this to reduce noise of library issues, however happy to discuss still.

**Comment by LukePenkava** [comment]
@Ehesp Thanks for clarification. I apologize if you didnt delete the message, that was my impression, because i am watching the thread, so my mistake.

 I understand it takes probably a lot of time and its honestly amazing what guys are doing for pretty much no compensation whatsoever. So thank you for that. I still think that a bit more communication would go a long way by giving few more updates so people can know what to expect. But again, its probably more work on top of working on the actual packages.
 I realy hope yo can figure out some reasonable payment model, so that you can perhaps put more resources into RNF, since its one of the key packages for RN. 
 Anyways, thanks again for your work. Best.
