### ISSUE TITLE
Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'Firebase/Messaging'" to your Podfile

### ISSUE THREAD

**Issue by motogod** [invertase/react-native-firebase#2907]
Describe your issue here

I want to use notification, as far as I know there is no notification package for V6 version now.

So I choose to use V5

Here is my environment:
"react": "16.9.0",
"react-native": "0.61.2",
"react-native-firebase": "^5.5.6",

I install it
`yarn add react-native-firebase`
`cd ios && pod install` (Install some FirebaseCore pod spec but I don't see FirebaseMessaging pod spec)

When I try the `firebaseSetting` fuction:
```
import firebase from 'react-native-firebase';

const firebaseSetting = async() => {
    // Test firebase
    const enabled = await firebase.messaging().hasPermission();
    if (enabled) {
      console.log('user has permissions')
    } else {
      console.log('user doesnot have permission')
      try {
        await firebase.messaging().requestPermission();
        // User has authorised
      } catch (error) {
        // User has rejected permissions
      }
    }
  }
```

It shows error:
`Error: You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.messaging().`

But If I use
```
yarn add @react-native-firebase/messaging
yarn add @react-native-firebase/app
```
They are V6 package not V5.

`firebaseSetting` function works on the environment:
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-firebase": "5.2.5",

I have no idea how to do next, the document doesn't say anything about FirebaseMessaging on V5.

Or should I manually add it on PodFile and `pod install` it ?

Any suggestion ? Thanks.

**Comment by Ehesp** [comment]
Try doing `cd ios && pod install --repo-update`?

**Comment by motogod** [comment]
Thanks, I tried it. There is no FirebaseMessaging

Here is my terminal message after `cd ios && pod install --repo-update
`
I paste all of the Firebase pod spec

```
Using Fabric (1.10.2)
Using Firebase (6.13.0)
Using FirebaseAnalytics (6.1.6)
Using FirebaseCore (6.4.0)
Using FirebaseCoreDiagnostics (1.1.2)
Using FirebaseCoreDiagnosticsInterop (1.1.0)
Using FirebaseInstanceID (4.2.7)
Using Folly (2018.10.22.00)
Using GTMAppAuth (1.0.0)
Using GTMSessionFetcher (1.3.0)
Using GoogleAppMeasurement (6.1.6)
Using GoogleDataTransport (3.2.0)
Using GoogleDataTransportCCTSupport (1.2.2)
Using GoogleSignIn (5.0.1)
Using GoogleUtilities (6.3.2)
Using QBImagePickerController (3.4.0)
Using RCTRequired (0.61.2)
Using RCTTypeSafety (0.61.2)
Using RNCAsyncStorage (1.6.2)
Using RNFirebase (5.5.6)

```

**Comment by mikehardy** [comment]
You haven't added the dependency correctly, each module in v5 has to be added to Podfile

Like so https://github.com/invertase/react-native-firebase/blob/v5.x.x/tests/ios/Podfile#L41

Per instructions here https://rnfirebase.io/docs/v5.x.x/crashlytics/ios

It appears this is  your first firebase module integration based on the included pods? The docs are clear on the subject of how to integrate so this shouldn't have caught you - I mention this because firebase in general is not an easy module to integrate. A back-end service with this much functionality is quite a complicated thing. Careful attention to the docs on each and every step will be vital for to integrate it successfully with any sort of velocity.

**Comment by mikehardy** [comment]
Additionally, the issue template I think specifies to include the Podfile, but you did not? https://github.com/invertase/react-native-firebase/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md#L53

Future reports please include full details of the template and it'll save that first round trip. My advice might not even be on target but I'm only guessing without the template contents

**Comment by motogod** [comment]
@mikehardy 
Thanks for your advice and help.

I used V5 before is React Native 0.57.1

Now I use 0.61.2, I am used to think It will be auto link when I type `yarn add react-native-firebase`

I know what is my problem now. Thanks.

**Comment by mikehardy** [comment]
when you upgrade to react-native-firebase v6 it will all change again, so be careful! But yes, for rnfb-v5, the *core* part of the module is auto-linked in, so that will "feel" like the typical react-native 0.60+ experience, but each and every other module needs it's own addition to Podfile and android packages list. Good luck with your project!
