### ISSUE TITLE
Analytics is required to finish creating Android Firebase app.

### ISSUE THREAD

**Issue by thefinnomenon** [invertase/react-native-firebase#2911]
## Documentation Feedback

# Problem
When following the instructions for setting up an Android app with Firebase here,

https://invertase.io/oss/react-native-firebase/quick-start/android-firebase-credentials

It gets stuck forever trying to verify the installation. 

# Solution
The Analytics module is required for Firebase to be able to verify the installation so you need to run,
`yarn add @react-native-firebase/analytics`.

# Suggestion
This should be added to the documentation since the only step before this tells you to install the App module.

**Comment by mikehardy** [comment]
I'd go the other direction. Owing to privacy concerns Firebase has worked pretty hard recently to make it so that analytics is optional. That page is only trying to positively identify that you have set up the project but it does not make the opposite statement that "you have not setup the project". If you proceed with configuration of your firebase project, it will work. Perhaps the documents should be altered in react-native-firebase to correspond with the stance that analytics is and should be optional, but if you don't include it then firebase will be unable to verify your project during initial configuration...

**Comment by thefinnomenon** [comment]
Oh I didn't know if it would work if the verification didn't complete. Yeah adding a note about that is the better solution. Thanks.

**Comment by mikehardy** [comment]
@thefinnomenon there are free internet points on offer for anyone that hits the edit button on the top of the documentation pages :-), github will guide you quickly (single page I think) the process required to get the doc edited and PR submitted
