### ISSUE TITLE
v6 docs are lacking

### ISSUE THREAD

**Issue by Tang8330** [invertase/react-native-firebase#3124]
## Documentation Feedback

Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation.

I just spent a whole day trying to get Push Notification (Cloud Messaging) trying to work on React Native for iOS and Android and kept running into a whole slew of problems around documentation. Either missing or incomplete. 

As an example https://invertase.io/oss/react-native-firebase/v6/messaging/ios-xcode-project-capabilities

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Yep! Open Source is made of humans, most of which have jobs that pay that rent since (unfortunately) open source usually does not pay at all, and if it does, not very much. There is an edit button at the top of each page where you can propose improvements and they are very very happily accepted

In addition, you can always consult the v5 site - I find using the combination of the two to be best at the moment https://rnfirebase.io/docs/v5.x.x/messaging/ios#Enable-Capabilities
