### ISSUE TITLE
@react-native-firebase/app

### ISSUE THREAD

**Issue by Marre1390** [invertase/react-native-firebase#3143]
Hello,

I am using **React-Native 0.61.5** and I want to implement React Native Firebase ..

At the beginning of the installation everything works fine.

But when doing **yarn add @react-native-firebase / app** is when I start having problems, after installing the package with yarn I go to the ios folder and I can install, but when I want to compile with react-native run-ios. .. I get the following error:

**ld: ld: framework not found nanopb**

Does anyone of you know how to fix it?

**Comment by mikehardy** [comment]
Hi there! You did not follow the template so I have no idea, but in general for install problems there are 1,000 ways for it to go wrong. Troubleshooting them is a big time-sink, so instead I've made a repo with scripts that do the install start to finish with comments. https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

Clone the repo, run that script, read the comments, and compare it with your integration. The problem is somewhere in the difference...
