### ISSUE TITLE
Is it possible to use Analytics module for GTM tracking

### ISSUE THREAD

**Issue by alex-mironov** [invertase/react-native-firebase#3255]
I didn't find actually any mentioning in the documentation if it's possible to use the Analytics module to integrate with Google Tag Manager?
Does it support it?

**Comment by Ehesp** [comment]
Not with this module, however it's fairly trivial to implement it yourself by following the Google guides, e.g: https://developers.google.com/tag-manager/android/v5/

**Comment by alex-mironov** [comment]
Got it, thank you @Ehesp. I was just wondering how to invoke the GTM methods from RN code...
But if I've read your link correctly it seems like GTM should intercept the events from Firebase Analytics. So I assume if I have RNFB Analytics integrated, after adding GTM pod everything should work just fine?

**Comment by LorandP** [comment]
@alex-mironov Not necessarily, I am currently facing some issues on iOS.
I have just added a GTM container and when I am running then the app crashes at startup. 
Others have this issue as well and it may be a conflict between Firebase versions and GTM:
https://github.com/firebase/firebase-ios-sdk/issues/2059
https://github.com/firebase/firebase-ios-sdk/issues/3921
https://stackoverflow.com/questions/46751963/ios-app-crashes-while-it-is-loading-the-googletagmanager-container

But this is just a heads up.

**Comment by kesha-antonov** [comment]
Hi guys
I need same thing
Did you succeed with this?

**Comment by vongohren** [comment]
I follow up on this @LorandP @Ehesp @alex-mironov,  any further movement on this?

**Comment by kesha-antonov** [comment]
I made it possible actually
But there's lots to explain

> I follow up on this @LorandP @Ehesp @alex-mironov, any further movement on this?

**Comment by vongohren** [comment]
@kesha-antonov haha ok. I would love to hear :P 
How would you proceede?
A short meeting?
You sharing the most important links?
Gisting some of your code?
Sharing a picture of some architecture view you have?

I just would like some breadcrumb to follow along from somone who have gotten it to work :D

**Comment by kesha-antonov** [comment]
> @kesha-antonov haha ok. I would love to hear :P
> How would you proceede?
> A short meeting?
> You sharing the most important links?
> Gisting some of your code?
> Sharing a picture of some architecture view you have?
> 
> I just would like some breadcrumb to follow along from somone who have gotten it to work :D

You need to create class in which you would call your tracking tool
On GTM website you add function to call this class with params you need
In RN you call RN-firebase - it sends event to firebase & also calls GTM
I can show it later in a few days

**Comment by vongohren** [comment]
> > @kesha-antonov haha ok. I would love to hear :P

> You need to create class in which you would call your tracking tool
> On GTM website you add function to call this class with params you need
> In RN you call RN-firebase - it sends event to firebase & also calls GTM
> I can show it later in a few days

Thanks for the leads, look forward to hear from you in a couple days

**Comment by rohit75** [comment]
I installed react-native-firebase and I want to use GTM also but I am getting any good reference how to setup GTM and trigger events from RN code.
Can anyone please share good references that would be really helpful

**Comment by kesha-antonov** [comment]
**Short instruction**
GTM is basically architectural lib. It helps you map function calls from firebase to other SDKs (**check thoughts in the end!**).

1. Add ```react-native-firebase```
2. Add ```pod 'GoogleTagManager'```
3. Open admin panel for GTM - create TAG there with events
4. In each event you need to use integration - available or custom. For custom you choose Tag Type - Function Call. Class - AppMetricaGTMTag (for example) - name of class where you import native sdk for analytics platform and send event in general method. Map params from firebase event to this event
5. Download GTM config and add it to the app
6. Add class to be called - in our example ```AppMetricaGTMTag```

```ios/GTM/AppMetricaGTMTag.h```
```
#import <Foundation/Foundation.h>
#import <GoogleTagManager/TAGCustomFunction.h>

@interface AppMetricaGTMTag : NSObject <TAGCustomFunction>

- (NSObject*)executeWithParameters:(NSDictionary*)parameters;

@end
```

```
ios/GTM/AppMetricaGTMTag.m
```

```
#import <Foundation/Foundation.h>
#import "AppMetricaGTMTag.h"
#import <YandexMobileMetrica/YandexMobileMetrica.h>

@implementation AppMetricaGTMTag

- (NSObject*)executeWithParameters:(NSDictionary*)parameters {
  // Add custom tag implementation here.
  NSLog(@"AppMetricaGTMTag: executeWithParameters");
  
  for(NSString *key in [parameters allKeys]) {
    NSLog(@"AppMetricaGTMTag dict key %@", key);
    NSLog(@"AppMetricaGTMTag dict value %@",[parameters objectForKey:key]);
  }
  
  NSString *eventName = parameters[@"event_name"];
  NSString *userId = parameters[@"user_id"];
  
  NSLog(@"AppMetricaGTMTag: event_name = %@", eventName);
  
  if(userId) {
    [YMMYandexMetrica setUserProfileID:userId];
  }

  [YMMYandexMetrica reportEvent:eventName parameters:parameters onFailure:^(NSError *error) {
       NSLog(@"AppMetricaGTMTag error: %@", [error localizedDescription]);
  }];
  
  return nil;
}

@end
```

<img width="1466" alt="Screenshot 2022-02-15 at 17 55 57" src="https://user-images.githubusercontent.com/11584712/154087417-208c3a97-f9ae-4d4d-9e21-4c683f68f43e.png">

**Thoughts on using GTM**

I think we should use GTM only if there is no react native wrapper around analytics SDK that you want to use. Otherwise, it's better to use those wrappers and send events from js.

I don't see much benefit from using GTM if analytics have RN wrappers around them. Because this way it's easier to maintain code. Also if you want to add some events - you need to ask a developer to add them in code once. With GTM you need to change the config, ask the developer to add events, and add a new config to the app.
