### ISSUE TITLE
New Native Ad Format

### ISSUE THREAD

**Issue by perrosnk** [invertase/react-native-firebase#3270]
## Documentation Feedback

According to [this](https://invertase.canny.io/react-native-firebase/p/new-native-ad-format) native ads are now supported.
Does anybody know how this can be implemented? Any documentation resource?
---

**Comment by Salakar** [comment]
Sorry this was a miscommunication, it's not currently supported - I've re-opened the feature request. Thanks

**Comment by perrosnk** [comment]
@Salakar Do you have any estimate on when it's going to be implemented? according to [this](https://github.com/invertase/react-native-firebase/issues/1403#issuecomment-519693116) it seems that it would be pretty soon

**Comment by Priyatham51** [comment]
@Salakar any idea how long would it be to support Native Ads ?

**Comment by IamMasterWayne** [comment]
+1

**Comment by Ehesp** [comment]
We've got no ETA yet. Take a look at https://github.com/ammarahm-ed/react-native-admob-native-ads/ in the meantime?

**Comment by seamive** [comment]
Do we have the support for NativeAdView in this package now?

**Comment by mikehardy** [comment]
As a general rule, if the Firebase APIs in their native SDKs do not have something, this module will not have it.

If you can point to a non-deprecated API that exists on the native SDKs that we do not wrap, then we can put it on the roadmap and get support for it.

In this case I do not believe there is any non-deprecated API from the firebase-ios-sdk / firebase-android-sdk that we are not handling, so I don't think it supports that format nor do I think it will since I think AdMob is deprecated completely out of firebase at this point - though please post a docs link from the SDKs if I'm wrong on that in any way

**Comment by seamive** [comment]
Is this one out of the box? https://www.npmjs.com/package/react-native-admob-native-ads

**Comment by mikehardy** [comment]
I do not know, I have no association with that package. I can say that similar to MLKit (which folks have been waiting patiently for, apologies to them) where the on-device ML inference APIs were evicted by Google Firebase team and we removed them here but will post as `@react-native-mlkit/<packages>`) we intend to evict the AdMob APIs from react-native-firebase to match the deprecation/removal from Google Firebase but re-post them as `@invertase/admob` where the community can take the existing + working code we have, and if there is a gap (like this one format) post PRs to keep the repo alive and relevant.
