### ISSUE TITLE
registeredHeadlessTask or registeredCancellableTask called multiple times for same key ReactNativeFirebaseMessagingHeadlessTask

### ISSUE THREAD

**Issue by angelobl** [invertase/react-native-firebase#3335]
Hi, Im getting this warning as soon as I get a Notification and setBackgroundMessageHandler is triggered. Any idea what could be causing it?

**Comment by Ehesp** [comment]
Version? Code example?

Please follow the template so we can help.

**Comment by jambanagar** [comment]
@angelobl @Ehesp 

I had this error too when I found a thread that suggested setting .registerHeadlessTask (below line) to receive messages in killed state.

AppRegistry.registerHeadlessTask('ReactNativeFirebaseMessagingHeadlessTask', ()....)

But, Looks like this is not necessary if you register the background handler early as stated below. The problem was I had this function not in App.js but another file fbase.js which is referenced in App.js initialization. Not sure why setBackgroundMessageHandler() would not be called if outside of App.js....

// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});
