### ISSUE TITLE
MultiDex needing in Android and having to remove build folder on every launch

### ISSUE THREAD

**Issue by BrianIto** [invertase/react-native-firebase#3340]
Hello everybody, I was developing a project with the version `6.3.4`.

Everytime when I run my Android project I have to remove my `android/build` to it finish the build, because if I don't I got a problem with `google-services.json`.

If anyone needs more details, I can pass it, no problem.

*Sorry, if it lack of details, I'm not an Issue Reporter, this is my first. (:

**Comment by eugustavo** [comment]
Have you encountered this problem?

```
> Task :app:transformClassesWithMultidexlistForDebug FAILED 
D8: Program type already present: io.invertase.firebase.BuildConfig

FAILURE: Build failed with an exception.

* What went wrong:
> Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives:
  Program type already present: io.invertase.firebase.BuildConfig
  Learn how to resolve the issue at > 
https://developer.android.com/studio/build/dependencies#duplicate_cl
```

I'm not able to run my application, even though I make all the changes to the native code to work with DEX

**I created a gist with my build.gradle, mainApplication and Error 👇**
https://gist.github.com/eugustavo/ec3a29277433ea30e0487a7941f8a100

**Comment by mikehardy** [comment]
@eugustavo  I have a hunch this is a problem with Android Studio 4.0

People aren't following the template so I can't say definitively, but if you can still reproduce this with Android Studio 3.4 (current *stable*, not a beta version) and gradle plugin 3.6.1 (current stable) I will be surprised

cross link: #3254

If you run my example here, which should build current stable versions of everything, I believe it still works? https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by BrianIto** [comment]
@eugustavo I had this problem before, I just removed the `build` folder at `android/app` and it worked for me. 

The main problem here, is that **everytime I launch, i need to remove this same build folder** because if I don't, it simply doesn't start.

**Comment by Mande3p** [comment]
If you have linked the package manually, then you have to disable auto-linking of specific package by creating a file *react-native.config.js* in base project folder like this:
`module.exports = {
  dependencies: {
    '@react-native-firebase/app': {
      platforms: {
        android: null
      },
    },
    '@react-native-firebase/crashlytics': {
      platforms: {
        android: null
      },
    },
 },
}`

**Comment by eugustavo** [comment]
> @eugustavo I had this problem before, I just removed the `build` folder at `android/app` and it worked for me.
> 
> The main problem here, is that **everytime I launch, I need to remove this same build folder** because if I don't, it simply doesn't start.

I found the problem in the application. It consisted that the same lib was being used 2 times in different versions.
I solved that and the application made the build, but now it always closes when it loads, I'm checking this error now. Hope this helps!
![depen](https://user-images.githubusercontent.com/25755550/78267703-a1d66c00-74dd-11ea-8f51-1eacf0ed8ea0.png)

**Comment by BrianIto** [comment]
@eugustavo I don't have this in my `package.json`, but I'm really glad you found the problem in your project. Well, I'm digging a little to found the problem in my project to erase the build folder anytime I run `react-native start`

**Comment by gotyet9** [comment]
@BrianIto 
Im also facing same issue 
and since the very start im not using react-native-firebase
All im using is 
<img width="432" alt="Screenshot 2020-04-08 at 6 36 57 PM" src="https://user-images.githubusercontent.com/15178452/78787439-fab77000-79c7-11ea-8f27-87b64327a088.png">

**Comment by Ehesp** [comment]
I've added this to the docs: https://rnfirebase.io/#android-enabling-multidex

**Comment by gotyet9** [comment]
@BrianIto Did you come across any workaround for this issue ?
For me even deleting build thing doesnt work.

It keeps on throwing the below error:

`> Task :app:transformClassesWithMultidexlistForDebug FAILED 
D8: Program type already present: io.invertase.firebase.BuildConfig

FAILURE: Build failed with an exception.

* What went wrong:
> Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives:
  Program type already present: io.invertase.firebase.BuildConfig
  Learn how to resolve the issue at > 
https://developer.android.com/studio/build/dependencies#duplicate_cl`

Also since the very start i have been using 
<img width="432" alt="Screenshot 2020-04-08 at 6 36 57 PM" src="https://user-images.githubusercontent.com/15178452/78844916-d0e06680-7a24-11ea-9582-da22f1fcad36.png">

And no other firebase package ever.
That's why i'm more shocked looking at other's solution.
they ask to remove `react-native-firebase` but i dont have any...

**Comment by rohit-ganapathy** [comment]
hey @gotyet9 did you figure out the solution to this? Cheers

**Comment by NguyenLuongVinh** [comment]
Well, finally I solved this problem by disable auto-linking.
First create a file name react-native.config.js in your root of project with the following content:
```javascript
module.exports = {
  dependencies: {
    '@react-native-firebase/app': { platforms: { android: null } },
    '@react-native-firebase/messaging': { platforms: { android: null } },
  },
};

```
After that, please link you package manually and update your project (pod, android libraries).
npx react-native run-android.

I have tried all the solutions and only this works for me. Hope this help!

**Comment by mikehardy** [comment]
I'm glad you found a solution, but disabling auto-linking is a drastic step, I would only do it as a last resort. There are thousands (a hundred thousand maybe?) users of react-native-firebase and this does not show up often, so I suspect the underlying cause is a local project misconfiguration somehow, that still bears investigation / comparison (perhaps with https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh ?) so we can reproduce the problem and fix it if so.
