### ISSUE TITLE
How to use Messaging only for Android

### ISSUE THREAD

**Issue by NiveshShastri** [invertase/react-native-firebase#3357]
Is there any way to use this library only for Android and use native code in IOS.

  "@react-native-firebase/app": "^6.3.4",
  "@react-native-firebase/messaging": "^6.3.4",
  "react": "16.9.0",
  "react-native": "0.61.5",

**Comment by mikehardy** [comment]
Sure. In your podfile, using ruby code, search (using a loop or similar) the in-memory object graph for the pods you don't want (the react-native-firebase ones I would presume) and remove them from the in memory object graph before the pod install phase, and that should stop all the auto-linking from bringing them in. There are examples online (usually from the react-native 0.59 days when integrating pods was more difficult and people wanted some things statically instead of via pods) of people doing the same
