### ISSUE TITLE
Firebase Performance Monitoring: Not able to get screen trace.

### ISSUE THREAD

**Issue by tusharthinksys** [invertase/react-native-firebase#3371]
I am getting only MainActivity screen traces but how can i get screen traces per screen in my React native app. Please help me.

**Comment by mikehardy** [comment]
#2994 #3226 

Everything in react-native runs in one activity, it's the way the whole platform works

You need to bridge the logical screen changes in your app (typically you will have some sort of hook that is called from your navigation library) into firebase (via setCurrentScreen or similar) such that navigation events results in firebase-level screen changes

**Comment by comvenger-brandon** [comment]
Using setCurrentScreen does not fix this problem. The performance library only reports "Mainactivity" for any screen.
"setCurrentScreen" is only for Analytics.

**Comment by mikehardy** [comment]
@comvenger-brandon this is a react-native-general problem. Has nothing to do with the specific module in use. It is literally fundamental to the design of react native to use a single activity and navigate within the bundle in javascript stack frames. If you have a workaround for the performance library as well, that would be interesting.

**Comment by MCervenka** [comment]
monitoring screen rendering would be really useful. Anyone found some way to implement it?

**Comment by sampsonjoliver** [comment]
Based on [this codelab](https://firebase.google.com/codelabs/measure-android-view-performance#7) from the Firebase team for running screen traces on Fragments, it seems like there is a way to start and stop screen traces programmatically, with custom names. At least for Android.

With that ScreenTrace util bundled for RN, it seems you start it on RN screen component mounts, and end it on screen component unmount. This might miss a some of the render lifecycle (between the activity create and the react mount), but you'll capture component updates well enough.

Or, for `react-navigation` users, and based on my understanding on `react-native-screens` [using Fragments under-the-hood](https://github.com/software-mansion/react-native-screens#using-createnativestacknavigator-with-react-navigation) if the Screens library could accept custom Fragment definitions then you'd just need to extend their [`ScreenFragment`](https://github.com/software-mansion/react-native-screens/blob/2918b44255dd85f00e74cc00b474b0cd7f84d4a6/android/src/main/java/com/swmansion/rnscreens/ScreenFragment.kt) and as per the codelab, start and stop a named trace on Fragment attach and detach.

**Comment by shamilovtim** [comment]
I've implemented per screen FPS profiling here (based on ad hoc start / stop via React lifecycle): #6588 

`react-native-screens` unfortunately isn't good enough because all of the Fragments are named the same and Android's Fragment API just doesn't have first class support for naming fragments. there's a clunky `getTag()` API but you can only set the tag at transaction time on the transactionManager. even if we were to use that `tag` API, implementation would be very complex and require PRs to both `firebase-android-sdk` and `react-native-screens`. there is no telling whether `firebase-android-sdk` would allow such a PR to go through. the compatibility later would be brittle and prone to breaking. also `react-native-screens` mounts 2 or 3 Fragment per screen / stack / etc (containerfragment / screenfragment / stackfragment, etc), so you'd end up having to also submit PRs to consolidate these traces. 

I think I am comfortable with the ad hoc screen rendering profiling. it's a little more code but it gives react native users control. I would also welcome bringing this functionality right into react navigation so it doesn't require any custom code from the users.  @kacperkapusciak @satya164

**Comment by gaurav5430** [comment]
a better usage example in the docs would be really helpful. Would be even better if we can include some examples with popular react native navigation libraries

**Comment by MorganTrudeau** [comment]
@shamilovtim Can you provide an code example of how you implemented your PR to successfully track screen performance? Are you using it exactly how it is shown in the docs?

**From Docs**
```
import perf from '@react-native-firebase/perf';

async function screenTrace() {
  // Define & start a screen trace
  try {
    const trace = await perf().startScreenTrace('FooScreen');
    // Stop the trace
    await trace.stop();
  } catch (e) {
    // rejects if iOS or (Android == 8 || Android == 8.1)
    // or if hardware acceleration is off
  }
}
```

Or are you doing something like...
```
const startTrace = async () => {
  try {
    const trace = await perf().startScreenTrace('FooScreen');
  } catch (e) {
    ...
  }
}

const stopTrace = async () => {
  try {
    await trace.stop();
  } catch (e) {
    ...
  }
}

useEffect(() => {
   startTrace();
   return stopTrace();
}, [])
```

Appreciate any insight you can provide. Thanks! :)

**Comment by shamilovtim** [comment]
startTrace starts the recording and stopTrace stops it. You'd stop the trace when you want to stop recording so it'd be the second example in your comment. However keep in mind that depending on how the screen exists in your navigational hierarchy there are a number of ways of when you you'd want to start or stop recording depending on when you know the screen is mounted or unmounted
