### ISSUE TITLE
Cannot install react-nativei-firebase/database. Permission denied couldn't read from remote repository. 

### ISSUE THREAD

**Issue by abhigk** [invertase/react-native-firebase#3498]
I am not able to install real-time database. It is giving me this error on install
```
npm install react-native-firebase/database
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/react-native-firebase/database.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```

**Comment by mikehardy** [comment]
That's not recommended in the docs anywhere. It is not how you install things. It's not even the right github URL. And with react-native-firebase developed in a monorepo you can't install it from git either way, you would have to use gitpkg.

Please follow the instructions in the documentation website to install the package

**Comment by abhigk** [comment]
I following official documentation, just using npm instead of yarn. 
https://rnfirebase.io/storage/usage
![Screenshot_20200421-160033__01](https://user-images.githubusercontent.com/9884510/79830942-d311d000-83e9-11ea-8c33-eeba86a7e21f.jpg)

**Comment by mikehardy** [comment]
You said:

> npm install react-native-firebase/database

Docs said:

`npm install @react-native-firebase/database`

Check that `@` sign

**Comment by HerrSensei** [comment]
I have the same error message but from a different context: after cloning the repo and running the npm install command, I get this error message: 

`npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/firebase/database.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Konnte nicht vom Remote-Repository lesen.
npm ERR! 
npm ERR! Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
npm ERR! und das Repository existiert.`

Also a reinstallation of Firebase did nothing. 
pls help

**Comment by mikehardy** [comment]
@HerrSensei - not sure why you integrate via ssh://git@github.com as your repo root, not sure why you're looking for the `firebase` organization's `database` repo, not sure at all what's going on here really.

I'm frequently unable to understand at all what people are doing when they are trying to integrate, and the methods chosen are quite inventive in my opinion, an infinite variety of ways to do things that take a ton of time to triage and reproduce.

So instead of spending scarce time untangling one off integration issues...

Here's a fully scripted reproduction of exactly how to integrate everything in firebase, and build it in a number of ways (catalyst builds, static framework builds) just read the comments and pick out the parts you need:

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by HerrSensei** [comment]
Hey @mikehardy 
Thanks for the quick reply! 
The error was due to my own stupidity - in my package.json there was (for whatever reason) an entry with "undefined: firebase/database".

I deleted it and it works now. ¯\_(ツ)_/¯

**Comment by JerodSpets** [comment]
Been searching for a solution for the same issue for an hour. Thank you so much!

**Comment by HarrisonOspina** [comment]
> Hey @mikehardy Thanks for the quick reply! The error was due to my own stupidity - in my package.json there was (for whatever reason) an entry with "undefined: firebase/database".
> 
> I deleted it and it works now. ¯_(ツ)_/¯
> 
> and thank you for the repo - i can surely make good use of it!

This was the solution for me too, that "undefined" in the package json gets created somehow and breaks everything
