### ISSUE TITLE
Why do we use fabric for crashlytics?

### ISSUE THREAD

**Issue by Acetyld** [invertase/react-native-firebase#3510]
Hello!

As the title states: "Why do we use fabric for crashlytics?" and not the new crashlytics library https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android

**Comment by Ehesp** [comment]
We haven't got around to updating the library yet to remove fabric.

**Comment by Acetyld** [comment]
So fabric is not needed? Or is the documentation wrong, or havent you implemented the firebase way yet?

**Comment by mikehardy** [comment]
Fabric is needed
The Firebase Crashlytics is still in beta.

I think the upstream Google Firebase SDK team is doing a poor job messaging this thing really.

They have put out that Fabric is out of support very shortly and you should migrate. But it is unclear to what so people are naturally very concerned, but they are all asking why we haven't migrated to a beta library. Isn't that odd?

If I understand correctly there are three crashlytics:

1) Fabric Fabric Crashlytics - from before Firebase/Google bought them. This is going away. You need to migrate
2) Firebase Fabric Crashlytics - this is the current stable thing. It's what react-native-firebase uses. I can't see how this would be going away yet since the future option is still beta?
3) Firebase Crashlytics - this is in beta. It's the future but the future isn't here yet (or it wouldn't be beta?). I understand google pushes beta stuff out widely frequently but to actually discontinue option 1 before option 3 is out of beta seems bizarre.

So I think everyone is fine for now, with option 2, and it's what react-native-firebase uses for now.

Anyone have info to the contrary? I would love to hear it

**Comment by embpdaniel** [comment]
@mikehardy Is there a diff between the Fabric service vs the Fabric SDK? My understanding is that option 2 you mentioned, uses the Fabric SDK but doesn't have to be linked with the Fabric service which is deprecated. It could be, but it's optional. Is this correct?

**Comment by mikehardy** [comment]
That's my understanding - that using Fabric SDK but with Firebase back-end, and why I'm okay with react-native-firebase using the Fabric SDK vs converting to a beta (in form of option 3 above) SDK, and why I think Firebase has some poor messaging here. This shouldn't be a question, we should all understand this clearly from their docs. Instead we have lots of worried devs thinking they're deprecated and have some action to take, when they're (I think) safely using Option 2

**Comment by r0b0t3d** [comment]
Just got an email from Fabric

![image](https://user-images.githubusercontent.com/8109285/80606832-f3cbcc80-8a5e-11ea-91cc-57be12a271bd.png)

**Comment by deecewan** [comment]
Update here:

The top of [this page](https://firebase.google.com/docs/crashlytics/get-started) now has:

![Note: The legacy Fabric SDK is now deprecated. If your app is using the Fabric SDK, read the Upgrade guide to install the official Firebase Crashlytics SDK.](https://user-images.githubusercontent.com/4755785/81702367-854f2b80-94ae-11ea-8d64-c5d1b9e52a62.png)

The [upgrade guide](https://firebase.google.com/docs/crashlytics/upgrade-sdk) now mentions to remove the `Fabric` and `Crashlytics` pods, and replace with `Firebase/Crashlytics`. I _think_ that means that it is out of beta 🤷 

But also. It was last updated on 2020-05-07 (6 days ago) so I'm not sure it's super critical

**Comment by mikehardy** [comment]
Yep - it left beta on April 21 https://firebase.google.com/support/release-notes/ios#version_6230_-_april_21_2020

And there's a PR to port to it #3580 which I think looks pretty good and is just waiting review from one of @Salakar or @Ehesp  ?

I actually think it is super critical but I use an "urgent / not urgent" axis and a "important / not important" axis to make sure the "important but not urgent" stuff doesn't get lost. This is in that quadrant - if we don't address it, we'll all be sad when it is urgent and important and not done yet :-), so I I'm hoping it gets nailed while still not urgent - I think it will

**Comment by deecewan** [comment]
yup - just found the PR and had a look through. was about to tackle it myself, but (luckily) decided to check if someone else had started first.

I guess when I said "not super critical" i was talking on the "urgent/not urgent" axis.

**Comment by mikehardy** [comment]
Thanks for reviewing it - I saw your comment over there, looked spot on. Shouldn't be long now before that's shaped up and merged either way. Cheers!

**Comment by Salakar** [comment]
Commented on the PR with more info / blockers, but I'm hoping to pickup fully on Friday.

**Comment by andersonaddo** [comment]
For anyone who stumbles upon this:
RNFB v8 now uses Firebase Crashlytics. (https://github.com/invertase/react-native-firebase/pull/3580)
![source](https://user-images.githubusercontent.com/34724755/86536957-9d916480-beb9-11ea-85a2-f459deb5d6e9.gif)

**Comment by mars-lan** [comment]
For those who are still stuck on v5 because they can't migrate their notification code to `notifee` or other libs, the good news is that you should be able to get `@react-native-firebase/crashlytics` to coexist with `react-native-firebase` v5 peacefully. The TL;DR; is 

1. Add modules
```
yarn add @react-native-firebase/app
yarn add @react-native-firebase/crashlytics
``` 

2. Clean up your Pod file & gradle build scripts using https://firebase.google.com/docs/crashlytics/upgrade-sdk
3. Update JS code using https://rnfirebase.io/migrating-to-v6#crashlytics

This works because there's no class name conflicts between v5 & v6+ on the native side for this particular package. I was also able to get `analytics` & `storage` packages to work using the same trick.

**Comment by Salakar** [comment]
@mars-lan out of interest whats holding you back from using notifee, is it the cost or is it the process of upgrading?

**Comment by mars-lan** [comment]
> @mars-lan out of interest whats holding you back from using notifee, is it the cost or is it the process of upgrading?

Actually already bought a license for it. Still waiting for time-based trigger support to be added :)

**Comment by mikehardy** [comment]
This may be an idea that goes nowhere, but you might be able to use https://github.com/transistorsoft/react-native-background-fetch as an alarm manager, set to trigger your notification - it seems like an oblique / not-great fit but still might work https://github.com/transistorsoft/react-native-background-fetch#param-integer-delay-milliseconds

**Comment by mars-lan** [comment]
> This may be an idea that goes nowhere, but you might be able to use https://github.com/transistorsoft/react-native-background-fetch as an alarm manager, set to trigger your notification - it seems like an oblique / not-great fit but still might work https://github.com/transistorsoft/react-native-background-fetch#param-integer-delay-milliseconds

That's definitely an interesting idea but would rather wait for @Salakar & co to come up with the proper implementation in notifee. After all that's why I paid for the license in the first place :P

**Comment by trglairnarra** [comment]
Hi guys, thanks for the free use and great work. Just wondering if v8 is already available and on how to migrate to v8 from v6. Thanks

**Comment by mikehardy** [comment]
@trglairnarra you will need to be quite a bit more resourceful than that :-), version information and release notes are available on main docs site rnfirebase.io which is also linked from readme

**Comment by davezrh** [comment]
> For those who are still stuck on v5 because they can't migrate their notification code to `notifee` or other libs, the good news is that you should be able to get `@react-native-firebase/crashlytics` to coexist with `react-native-firebase` v5 peacefully. The TL;DR; is
> 
> 1. Add modules
> 
> ```
> yarn add @react-native-firebase/app
> yarn add @react-native-firebase/crashlytics
> ```
> 
> 1. Clean up your Pod file & gradle build scripts using https://firebase.google.com/docs/crashlytics/upgrade-sdk
> 2. Update JS code using https://rnfirebase.io/migrating-to-v6#crashlytics
> 
> This works because there's no class name conflicts between v5 & v6+ on the native side for this particular package. I was also able to get `analytics` & `storage` packages to work using the same trick.

I tried to upgrade Crashlytics to v6 while leaving v5 for the other packages. The Podfile included the following entries:

` # Required by RNFirebase
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'Firebase/RemoteConfig', '~> 6.13.0'
  pod 'Firebase/DynamicLinks', '~> 6.13.0'
  pod 'Firebase/Performance', '~> 6.13.0'
  pod 'Firebase/Auth', '~> 6.13.0'
`

Adding `pod 'Firebase/Crashlytics'` or `pod 'Firebase/Crashlytics', '~> 6.30.0'` to the Podfile didn't work:
`
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    RNFBApp (from `../node_modules/@react-native-firebase/app`) was resolved to 8.4.5, which depends on
      Firebase/CoreOnly (~> 6.30.0)
`
Do you have more details on how you managed to make it work?

**Comment by mars-lan** [comment]
@davezrh sorry but I've long moved on to notifee since making that comment so my memory is a bit fuzzy at this point. Also note that this was prior to the [fabric to firebase/crashlytics migration](https://firebase.google.com/docs/crashlytics/migration-post-linking) so not sure if that changed anything.

**Comment by lisichka999** [comment]
Hi @mikehardy , from what version Fabric is inside crashlytics, I use 7, should I upgrade to 8?
Thanks

**Comment by mikehardy** [comment]
It's noted in the changelog on the releases. But use current stable, most recent

**Comment by lisichka999** [comment]
@mikehardy , Thanks, I think this is a problem, when can I see the change log?

**Comment by mikehardy** [comment]
Rnfirebase.io releases
Its not a problem
Ported for months now
