### ISSUE TITLE
where are the release note for 6.7.1?

### ISSUE THREAD

**Issue by ethanneff** [invertase/react-native-firebase#3539]
## Documentation Feedback

Missing release notes for v6.7.1

**Comment by mikehardy** [comment]
@Salakar a couple people have asked for this, my reply was that 6.7.1 contains the results of the messaging fixes (#3339) but that in general it went from 6.3 to 6.7 mostly because of CI auto-release tests that bumped things quickly? That said people love the release notes and they are useful to communicate what's coming in

@ethanneff  duplicate #3518 but that one is hard to find so I would have duped too :-)

**Comment by Salakar** [comment]
> but that in general it went from 6.3 to 6.7 mostly because of CI auto-release tests that bumped things quickly?

Correct, because we've switched to independent package releases now . There are now CHANGELOG.md files in each package directory - we need to add these on the site somehow still.
