### ISSUE TITLE
Not able to receive heads-up (floating) notification when app is in background or foreground

### ISSUE THREAD

**Issue by Jyotidanawale17** [invertase/react-native-firebase#3564]
Hello, I want to show heads up (floating) notification when my app receives any notification. I have set the priority of notification as HIGH, but still not able to receive heads-up notification.  
Please note: I am able to receive notification in notification tray
Kindly help.

const channel = new firebase.notifications.Android.Channel('fcm_FirebaseNotifiction_default_channel', 'Demo app name', firebase.notifications.Android.Importance.High)
            .setDescription('Demo app description')
            .setSound('sampleaudio.wav')
        firebase.notifications().android.createChannel(channel);
        
        this.notificationListener = await firebase.notifications().onNotification((notification) => {
            const { title, body } = notification;
            const localNotification = new firebase.notifications.Notification({
                sound: 'sampleaudio',
                show_in_foreground: true,
            })
                .setSound('sampleaudio.wav')
                .setNotificationId(notification.notificationId)
                .setTitle(notification.title)
                .setBody(notification.body)
                .setData(notification.data)
                .android.setAutoCancel(true)
                .android.setChannelId('fcm_FirebaseNotifiction_default_channel') 
                .android.setSmallIcon('ic_launcher')
                .android.setLargeIcon('ic_launcher')
                .android.setPriority(firebase.notifications.Android.Priority.High);
            firebase.notifications()
                .displayNotification(localNotification)
                .catch(err => console.error(err));

        });

"react-native": "0.59.8",
"react-native-firebase": "^5.5.6",

**Comment by mikehardy** [comment]
Notifications in react-native-firebase is a dead-end, support for local notification APIs was removed in react-native-firebase v6 and RNFBv5 isn't receiving support any more, it's time to upgrade react-native-firebase (and react-native if you are on 0.59), and integrate a supported notifications package (react-native-notifications or notifee or similar)

**Comment by GovindAgarwa** [comment]
Hi @mikehardy 

For Android:-
I am not receiving floating notification on the top of the screen (like a tray) but I am getting data when my app is in background or foreground using method **messaging().setBackgroundMessageHandler()**  and also my phone getting vibrate for a very small time when getting a notification at that time My app is killing mode. 

should I need to add anything in a manifest file?? because as per document I am not adding anything in my manifest file. Just I am following this way https://rnfirebase.io/

React Native version - 0.62.0,
React Version - ^16.11.0

I have searched a lot and burning my head for the last 3 days. I am looking for a response, thanks in advance.

Thanks
Govind
