### ISSUE TITLE
Add documentation or polyfill for `atob` for Firestore.

### ISSUE THREAD

**Issue by wu-hui** [invertase/react-native-firebase#3619]
Please refer to: https://github.com/firebase/firebase-js-sdk/issues/2667 for the background.

Basically newer version of Firestore is having issues due to `atob` not available. In the link above, there are a walkaround, please either document the walkaround, or better: polyfill such that user can use it directly.

**Comment by mikehardy** [comment]
I don't understand. This is the second issue you've logged, but it seems that you are trying to use the firebase JS SDK on react-native? That actually has very little to do with this module. This module wraps the **native** SDKs, and does not use the firebase-js-sdk at all. This module just attempts to **mimic** the JS SDK API so that javascript code that also uses the JS SDK for web implementations can also use this without change.

I don't think this issue is valid.

It may be that #3618 is also not valid.
