### ISSUE TITLE
Notification won't display in background and foreground

### ISSUE THREAD

**Issue by malikoum94** [invertase/react-native-firebase#365]
Hello,

I follow the guideline for IOS, all setup are good.
When the app is in foreground, i get the onMessage Event but can't display the notification popup.
And when the app is killed or in background, nothing append...
I tried to change my remote notification to local but can't display too...
And when i got a remote notification, the payload haven't _notificationType key.

Have you any idea to fix this?

1. Target Platform (e.g. iOS, Android): IOS and android but actually i work on IOS only
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode IOS 10.3
4. React Native version (e.g. 0.45.1): 0.47.1
5. RNFirebase Version (e.g. 2.0.2): 2.1.3

**Comment by chrisbianca** [comment]
@malikoum94 It sounds like either:

1) You don't have the correct permissions enabled: https://invertase.io/react-native-firebase/#/installation-ios?id=_32-enable-capabilities

2) Your remote notification message body is the wrong format.  Here's an example that's known to work:

```
const message = {
  to: to,
  priority: 'high',
  notification: {
    title: title,
    body: body,
    badge: badge,
    sound: 'default',
    color: os === 'android' ? '#84B2D9' : null,
    icon: os === 'android' ? 'ic_notification' : null,
    click_action: os === 'android' ? 'OPEN_MAIN_ACTIVITY' : null
  },
  data: data
}
```

If this doesn't help, please take a look at https://firebase.googleblog.com/2017/01/debugging-firebase-cloud-messaging-on.html for some more suggestions to identify where the issue lies.

**Comment by malikoum94** [comment]
Hi,

All permissions are set like in the documentation.
The payload notification is good because it's work with other modules.
But if i set `FirebaseAppDelegateProxyEnabled` to YES i receive remote notification but `.onMessage` event didn't work and if i set it to NO the event work but it's impossible to show notification...

So i can't handle notification in foreground but in background it works if i set `FirebaseAppDelegateProxyEnabled` to YES.

**Comment by chrisbianca** [comment]
@malikoum94 When you say it works with other modules, what do you mean?

`FirebaseAppDelegateProxyEnabled` should definitely be set to yes as this simplifies the setup.  Otherwise you need to add further methods in as explained in the Firebase documentation.

When you say you can't handle notification in foreground, are you saying that it doesn't pop up a notification? Or that the `.onMessage` method doesn't fire?

If the former, then this is expected behaviour - iOS doesn't automatically display a notification if the app is in the foreground as it's seen as a poor user experience.

**Comment by malikoum94** [comment]
in the past i use react-native-fcm and it work in booth state (background and foreground).

ok for `FirebaseAppDelegateProxyEnabled` set to YES.

And in foreground i have nothing no pop up and `.onMessage` doesn't fire.

In the past with other module i use the `.onMessage` event for display the notification in foreground but now the event doesn't fire so i can't.
