### ISSUE TITLE
Crash about google.services.json

### ISSUE THREAD

**Issue by 0gebey** [invertase/react-native-firebase#3678]
Hello , I am new with firebase , I impelement the react-native-firebase to the my project with necessary dependencies. It works fine but after some while like shut down and open computer again or re-build after some time it is crashing.I am updating the google.services.json file and it is fixing. Does anybody have any idea about it ? Thank you all.

**Comment by andersonaddo** [comment]
You're going to need to provide more info for anyone to help. Start by following the template.

**Comment by 0gebey** [comment]
Got it , I'll be here as well as I get the bug report again

**Comment by mikehardy** [comment]
It sounds like something has gone terribly wrong with your integration, unsure what as you're not providing any crash traces (from Xcode while app is running in debug, or unfiltered adb logcat for android)

Here's an example of how to generate a complete standalone running demo app though, you might inspect how it works, and what the resulting project looks like in order to see how things should look - then compare it to your project: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh

**Comment by russellwheatley** [comment]
I'm going to close this issue as there is nothing directly wrong attributed to React Native Firebase.
