### ISSUE TITLE
Admob interstitial crash continuously in application firebase 7.1.0 version

### ISSUE THREAD

**Issue by cubukcuoglu-3** [invertase/react-native-firebase#3715]
Admob interstitial crash continuously in application firebase 7.1.0 version
![Adsız](https://user-images.githubusercontent.com/47679134/83288052-6d381580-a1eb-11ea-9cd0-0fa5fba5cf97.png)
![Adsız2](https://user-images.githubusercontent.com/47679134/83288055-6dd0ac00-a1eb-11ea-8d49-e157da263ff2.png)

**Comment by mikehardy** [comment]
@cubukcuoglu-3 

- images in general are terrible for troubleshooting, please just post a link to something relevant? https://github.com/invertase/react-native-firebase/blob/71dc17371e8b5c7e3ae70feb921ac5c56dbf0484/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobInterstitialModule.java#L132
- you ignored the template completely

It looks like in certain cases the ad can fail to show:
https://github.com/invertase/react-native-firebase/blob/71dc17371e8b5c7e3ae70feb921ac5c56dbf0484/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobInterstitialModule.java#L70-L71

Which would mean that ad is not in the array of ads
Which could lead to this null pointer I think if you persist in calling show despite an error event. Are you listening for the error events? Posting code might help.

Does appear that when the ad is fetched from the ad array it should be tested from null and a nicer error message should be shown.

This issue is not likely to see high priority attention, I strongly advise you to manually go into node_modules, and manually alter the Java. I would add an import of android.util.Log at the top, and before I sent the error event I would log that it was happening, then down below I would add a null check and log the results, then do a promise reject similar to the others in the method.

You will likely be able to solve your own problem in just a few minutes effort, propose a PR to help everyone, and with https://github.com/ds300/patch-package you can easily persist your change so it's fixed permanently in your project everywhere (even CI) until your PR is merged

**Comment by ashishfeels** [comment]
@mikehardy this happened to me too also i wanted to know is there anyway to mute interstitial as it interupts the music played by my app

**Comment by mikehardy** [comment]
@ashishfeels how did it go when you followed my advice above?

> This issue is not likely to see high priority attention, I strongly advise you to manually go into node_modules, and manually alter the Java. I would add an import of android.util.Log at the top, and before I sent the error event I would log that it was happening, then down below I would add a null check and log the results, then do a promise reject similar to the others in the method.
>
> You will likely be able to solve your own problem in just a few minutes effort, propose a PR to help everyone, and with https://github.com/ds300/patch-package you can easily persist your change so it's fixed permanently in your project everywhere (even CI) until your PR is merged
