### ISSUE TITLE
TypeError: undefined is not a function near (…'this.firestore.native.collectionGet…')

### ISSUE THREAD

**Issue by safadhildev** [invertase/react-native-firebase#3749]
I've been trying to integrate Firebase Cloud Firestore into my React Native project.
I've followed the documentations from [https://rnfirebase.io/](https://rnfirebase.io/) and [ https://rnfirebase.io/firestore/usage]( https://rnfirebase.io/firestore/usage).

dependencies in `package.json`
```
"dependencies": {
    "@react-native-firebase/app": "^7.2.0",
    "@react-native-firebase/firestore": "^7.2.0",
    "react": "16.11.0",
    "react-native": "0.62.2"
  },
``` 

Here's my code

**App.js**
```
import React, {useEffect} from 'react';
import {
  SafeAreaView,
  View,
  Text,
  StatusBar,
} from 'react-native';
import firestore from '@react-native-firebase/firestore';

const App = () => {
  const getData = async () => {
    const db = await firestore().collection('stories').get();

    console.log({db});
  };

  useEffect(() => {
    getData();
  });

  return (
    <>
      <StatusBar />
      <SafeAreaView>
        <View>
          <Text>Hello There</Text>
        </View>
      </SafeAreaView>
    </>
  );
};

export default App;
```

Then, when I run the app, it gives me this error. This occurs both on Android and IOS

![Screenshot_1591506019](https://user-images.githubusercontent.com/63948700/83961022-dee62280-a8c1-11ea-8644-d0ca8e4a1c6e.png)

Here's my Firestore looks like
<img width="1166" alt="Screenshot 2020-06-07 at 13 26 19" src="https://user-images.githubusercontent.com/63948700/83961104-92e7ad80-a8c2-11ea-86e5-cf3677fd8f87.png">

It'll be great if someone can help me. thanks

**Comment by mikehardy** [comment]
You appear to have skipped most of the template.
Looks like "standard failure to correctly install the module", that is, the native module is not actually installed for some reason.
I would very very very carefully check your local integration and make sure that auto-linking is working and the native libraries are linked in and installed.

**Comment by rohit20001221** [comment]
one reason i was getting this error was due to the way I imported my functions
![Screenshot from 2023-07-31 14-36-39](https://github.com/invertase/react-native-firebase/assets/25266550/7aa40a4a-c5f3-4daa-8677-89bc6ed60a3e)
using `.` and `..`
when I changed to ./index and ../index the error was gone
![Screenshot from 2023-07-31 14-38-52](https://github.com/invertase/react-native-firebase/assets/25266550/40b82e44-a3bf-406e-bfc0-3273f0aca3c6)

i am not sure if this is the reason for error but i was able to resolve the issue by updating the import 😅 I hope this might help you someway just check your repo if you did similar kind of imports
