### ISSUE TITLE
sendEmailVerification doesn't have any listeners onVerified

### ISSUE THREAD

**Issue by Ashalbulk** [invertase/react-native-firebase#3786]
### Steps to Reproduce
1. Sign up a user via email and password
2. Call sendEmailVerification and send verify email
3. Open the email on PC or Mac and navigate to verify link

### Expected Behavior
Some listener would be triggered and we update the user in firebase.

### Actual Behavior
We don't know if the user is already verified or not. I didn't find any solution to get this information via any listeners. I tried onUserChanged, doesn't work.

### Environment

* react-native version: 0.61.2
 * @react-native-firebase/auth: 7.1.0
* iOS/Android/Windows version: latest
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
I don't believe it is technically possible. There are no listeners like this in the upstream SDKs for this library to wrap even.

In my app I listen to AppState https://reactnative.dev/docs/appstate.html and it works great though.

If the user goes to check their email by definition your app goes in the background.
When it comes back in the foreground you check to see if they are now authenticated. If they are you auto-advance.

I'm going to close this since the APIs don't exist mostly, but I also think the possible workaround above is a viable solution as it does work in practice

**Comment by Ashalbulk** [comment]
@mikehardy If we use just a mobile phone for verifying we can use deep links for redirect user to our app, it is exactly how it works now in my app. But as I said, if users click on verification link on their PC or Mac, I can't use such a logic(redirect back via deep link), cause user doesn't have my app on their PC or Mac. I'm trying to find the way to do this correctly.

**Comment by mikehardy** [comment]
If you can find an upstream firebase SDK API that we can use, then we can wrap it and do this. As far as I understand there is none.

Perhaps, maybe, lots of work, but you could have a firestore table where you track these things and you could put a listener on it for new results. That would get you an event you could listen for but there are no auth-related APIs that do this that I'm aware of
