### ISSUE TITLE
auth OTP not working on IPads

### ISSUE THREAD

**Issue by AGDVS1** [invertase/react-native-firebase#3854]
## Documentation Feedback

My app keeps getting rejected by the appstore because of the firebase phone authentication.

It is working well on IPhone and IPad simulators, even on real IPhone deveices but on real Pad devices nothing happens when publishing and testing the app on test flight. 

I think it could have something to do with the captcha.

package.json ->

"@react-native-firebase/app": "7.1.0",
"@react-native-firebase/auth": "7.1.0",
"@react-native-firebase/firestore": "7.1.0",
"@react-native-firebase/functions": "7.1.0",
"@react-native-firebase/messaging": "7.1.0",
"@react-native-firebase/storage": "7.1.0",
"react": "16.11.0",
"react-native": "0.62.1",

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
This is a sincere question: imagine you are the head of software development, and I am your programmer, I bring you this problem, how exactly can I help? I'm stumped personally. I can tell you I have an app with email, phone and social auth and it gets approved. So why not your app? Is it phone auth only? I have heard of closer troubleshooting with the approval folks so you don't have to guess - you can ask them for exactly what's going on, and even for logs of what's going on (implying you can put extra logging in a build and give it to them)

Otherwise, I have no idea how to help, sorry.

**Comment by AGDVS1** [comment]
> This is a sincere question: imagine you are the head of software development, and I am your programmer, I bring you this problem, how exactly can I help? I'm stumped personally. I can tell you I have an app with email, phone and social auth and it gets approved. So why not your app? Is it phone auth only? I have heard of closer troubleshooting with the approval folks so you don't have to guess - you can ask them for exactly what's going on, and even for logs of what's going on (implying you can put extra logging in a build and give it to them)
> 
> Otherwise, I have no idea how to help, sorry.

I understand there is no way debugging the problem I am in the same situation with appstore but I was guessing maybe there are some problems with the versions I am using or perhaps this library does not support IPad phone authentication.

**Comment by mikehardy** [comment]
I'm not exactly sure how an iPad could support phone authentication, so perhaps you could remove that feature from the interface if it's an ipad - the device-info package can help you there https://github.com/react-native-community/react-native-device-info/#getDeviceType will return 'Tablet' and is available synchronously (no async required) such that it's easy to consume very early during app bootstrap for UI configuration
