### ISSUE TITLE
Reset Password Email Code

### ISSUE THREAD

**Issue by wincod75** [invertase/react-native-firebase#3911]
## Documentation Feedback

Under the auth docs, I'm seeing ways to verify and confirm a password reset code, but seemingly the only way to perform a password reset is with `sendPasswordResetEmail ` which specifically states in the docs "Unlike the web SDK, the email will contain a password reset link rather than a code."

How does one send a reset code via email to the user's provided email, which they can then utilize methods like the ones listed below? Is this even possible and if not why do these methods exist, what purpose do they serve?

- https://rnfirebase.io/reference/auth#verifyPasswordResetCode

- https://rnfirebase.io/reference/auth#confirmPasswordReset

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by FaisalAshraf44** [comment]
@wincod75 hi, did you find any help to send a password reset code via email?

**Comment by wincod75** [comment]
@FaisalAshraf44 No, I don't believe it works this way. I was able to get password reset flow up and functional, but no code is sent to the user's email. From what I found, the user is emailed a link that will send them to a Google/Firebase screen to enter a new password which is updated in Firebase. This flow is not ideal, but it does work. I'm still puzzled as to what the two methods from my OP are for though.

**Comment by mikehardy** [comment]
There is a valid documentation question in here, so marking this for review

To the OP - not sure on the APIs you linked, but there is flexibility in the password reset flow. I believe it's documented upstream somewhere, but the main idea is that they give you out-of-the-box functionality via those password reset handlers in your project, but they are actually just web hosted files in your project that call firebase functions in your project. There is nothing stopping you from altering the files and/or the functions in order to (for example) include branding (or any semblance of design, really!) or to enforce password policy

**Comment by mikehardy** [comment]
@rhenwinch on an issue closed 3 years ago? Where all updates are visible and you see none? I am not sure what you are expecting but an update isn't a thing that should be an expectation here.

Open a new issue if you need one, carefully considering https://stackoverflow.com/help/how-to-ask - and please make sure that what you're describing is an actual bug that will result in a change in this library, not just a usage question

If it is general firebase usage questions, stackoverflow with appropriate tags should attract support
