### ISSUE TITLE
firebase.auth(...).getRedirectResult is not a function after setup (with redux)

### ISSUE THREAD

**Issue by NathHorrigan** [invertase/react-native-firebase#431]
### Issue

I get the following error ` firebase.auth(...).getRedirectResult is not a function` after following the guide to setup library - I also followed the redux setup guide.

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS Sierra

3. Build Tools: Android SDK 26.0.1

4. React Native version: 
react-native-cli: 2.0.1
react-native: 0.48.3

5. RNFirebase Version: 2.2.0

6. Firebase Module: All

**Comment by chrisbianca** [comment]
@NathHorrigan `getRedirectResult` is not supported in `react-native-firebase` as it's not possible to use redirect-based sign in flows in React Native.  Assuming you're trying to do Facebook or Google sign in, you'll need to get the credential using a third party library, e.g. `react-native-fbsdk` or `react-native-google-signin`then use the `signInWithCredential` or `linkWithCredential` methods that `react-native-firebase` exposes.

**Comment by NathHorrigan** [comment]
But I'm not calling any auth methods. I have just setup and installed `react-native-firebase` - nothing else.

**Comment by NathHorrigan** [comment]
Must have been some sort of cached file. The problem resolved itself after I resaved and built some files. Thanks for your help anyhow!

**Comment by chrisbianca** [comment]
No probs

**Comment by NathHorrigan** [comment]
@chrisbianca Actually the error has reappeared but only when using remote JS debugging 😕

**Comment by chrisbianca** [comment]
Sounds like a weird caching issue to me, or there is something using it in the background.

As an FYI, this has prompted us to make some changes in v3 to make it clear which methods we don't support because the native SDKs don't support them.  This is one of them.

**Comment by NathHorrigan** [comment]
This is still happening on all 3 browsers that I have tested (Chrome Canary, Chrom Stable, Firefox Dev edition)

**Comment by hisokakei** [comment]
Faced the same issue if I enable Remote JS Debugging.

I didn't call any auth() method at all.

"react-native": "^0.48.3"
"react-native-firebase": "^2.2.2"

**Comment by chrisbianca** [comment]
@NathHorrigan @hisokakei This looks like it's something internal to `react-redux-firebase` as per the below:

https://github.com/prescottprue/react-redux-firebase/blob/ed6b902aee8ca225b02e307b71ff1b93b4f9f6fe/src/actions/auth.js#L268

@prescottprue `GetRedirectResult` isn't supported by the native SDKs - how can these guys work around the issue?  It looks like there's a config flag which might be possible to disable?

**Comment by prescottprue** [comment]
@chrisbianca If we can know with confidence that it is this type of environment (i.e. an instance of `react-native-firebase` instead of regular `firebase`) than we could possibly call whatever interaction `react-native-fbsdk` needs. I would need to look a little more into it.

The current [`react-native` example for v1.*.* of `react-redux-firebase`](http://react-redux-firebase.com/docs/recipes/react-native.html) uses `react-native-google-signin` along with the native firebase lib to make things work. I'm wondering if we can do something similar internally, but it would be ideal to keep it from adding dependencies for those who are not using `react-native`.

[This issue on `react-redux-firebase` may be related](https://github.com/prescottprue/react-redux-firebase/issues/260), though the explanation seems a little different, so maybe not.

Either way, since OAuth with `react-native-firebase` seems to be an ongoing issue for multiple people, I am going to prioritize it on the v2 roadmap for `react-redux-firebase`.

**Comment by NathHorrigan** [comment]
So what is the temporary fix for this?? My firebase setup itself is working - I have a working google signin (with firebase) that works when not remote debugging.

**Comment by prescottprue** [comment]
@NathHorrigan Did you provide `enableRedirectHandling: false`? If you are using the most recent `v2.0.0-*` pre-release, it shouldn't be necessary.

Since it relates to your usage with `react-redux-firebase`, lets track solving it in an issue on there so that this closed issue does not keep getting updated.

**Comment by shivanshrajpoot** [comment]
Use ```enableRedirectHandling=false``` in reduxFirebaseConfig for reactReduxFirebase function from 'react-redux-firebase'
