### ISSUE TITLE
[📚] ML package readme possibly has wrong URL

### ISSUE THREAD

**Issue by JBuijgers** [invertase/react-native-firebase#4612]
## Documentation Feedback

[This README](https://github.com/invertase/react-native-firebase/tree/master/packages/ml#ml-kit-ready-to-use-on-device-models), has a URL (under "Use the new react-native-mlkit modules") that points to https://www.npmjs.com/org/react-native-mlkit, which only shows an organization with 0 packages. Will any packages be added later or do we maybe need a different URL?

**Comment by mikehardy** [comment]
Apologies - the packages will be added later. It is on my to carry the existing "on device inference" implementations from react-native-firebase over there and get them published, but I've been called on for a couple other tasks so I have not had the time yet. Until then, if you require on-device inference you are unfortunately not able to update to the v10 releases yet (actually, the version set just before them is off limits even). I still have hopes of getting those packages up and live within the next week or two until then I can only plead for patience.

**Comment by JBuijgers** [comment]
No problem, I can completely understand :+1:  Thanks for the response and good luck with getting everything up-and-running!

**Comment by eladgel** [comment]
@mikehardy Any updates on this issue?

**Comment by mikehardy** [comment]
Still in the pipeline but nothing to show yet. Notifee had some critical issues to handle first unfortunately, but fortunately some of the lessons learned there should apply to the react-native-mlkit bring up. Rest assured when it's out we'll make announcements on Twitter plus I'll post on the relevant issues

**Comment by Yonom** [comment]
@mikehardy Any updates on this issue?

**Comment by eladgel** [comment]
@mikehardy is it still in the road map?

**Comment by mikehardy** [comment]
Hi @eladgel (and hello @Yonom!) it definitely is, Google IO was last week and we had a pile of new underlying goodies we needed to wrap for release. Still need to finish AppCheck actually. In the meantime I've been working on cleaning up the module creation template here, and our CI + coverage setup so that when I fork the repo infrastructure out to re-home the code it's in good shape. I apologize for the delay as ever - I appreciate the patience. All I can say is if you look at the commits here I've been crushing it, just not ML in particular as "it" 😅
