### ISSUE TITLE
Cloud Messaging FCM token expiring

### ISSUE THREAD

**Issue by sturrock** [invertase/react-native-firebase#4627]
Hello Everyone,

I'm having a problem where when you open a push notification on iOS in a certain order, the FCM token expiries. For instance if i send the app a message, open it, then close the app and repeat it works fine. If i send the app a message dont tap on the message but open the app, then close it and send another, it will reset the token and cant send the user another message until the new token is recognised 10 minutes later. 

Why is it resetting and how can I fix this?

**Comment by mikehardy** [comment]
Interesting - the last time someone saw token expiration / cycling in an unexpected way it turned out that for some reason their app was requesting token expiration (delete / new token) explicitly in some code path they hadn't seen until they investigated.

After fixing that, they had stable tokens and no problems

So are you absolutely, 100% sure you can reproduce this with nothing but an App.js (no external dependencies, just a minimal reproduction) that you drop into a skeleton made from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh ?

If you can, then further exploration is to dig into node_modules and instrument the calls JS / Obj-C to print out that a firebase-ios-sdk is about to happen along with it's arguments, then print out it's returns - that should clarify any flow issues / native SDK usage issues that would be the responsibility of react-native-firebase (note that you could do that directly with your existing app as a way to figure things out without trying a minimal reproduction, but if you do don't do a minimal reproduction it will be harder to fix if there is a react-native-firebase problem as we may have trouble reproducing it)

My hunch is that at this point it is going to go one of two ways:

- there is something wrong with your project's token usage
- there is something wrong with firebase-ios-sdk and you'll need to file an upstream issue based on their quickstart https://github.com/firebase/quickstart-ios/tree/master/messaging

Either way you fully skipped the template here so I can't help further, there's no information to go on

**Comment by sturrock** [comment]
Thanks Mike for the reply, I think you might have answered my problem. My app runs this code ```var fcmToken = await messaging().getToken();```  every time the app opens. Most of the time it returns the same token, but then it just randomly changes. I'll test it later today and see if that helps, but i'm pretty sure i've also had instances where i've sent the notification and not opened the app, and when i've gone to send another... its expired. 

If I can't get it working I'll put all the code and info you need here (I like to ask a question and try figure our what the problem is myself).

Thanks for your reply anyways.

**Comment by efstathiosntonas** [comment]
Hi @sturrock , I'm also calling `messaging().getToken()` on every app launch, was that the cause of the issue? Thanks
