### ISSUE TITLE
Parameters are removed from dynamic link after opening from browser in iOS platform

### ISSUE THREAD

**Issue by Shashank123sprive** [invertase/react-native-firebase#4643]
Hi @mikehardy/Team,

I'm using verification email strategy for login/register feature in my app, and the verification email contains a dynamic link(consist of destination screen, and verification token), which is used to navigate to a screen within the app installed in the user's phone.

Now the scenarios are , 

1. If a user simply clicks on the dynamic link from email, it opens the app, with no issue. In this case the links consistent and I can see following resolved dynamic link the app's listener code is : 

**https://links.sprive.com/sprive?screen=verification&verification_token=euasdasdZHDHH$qw132**

2. Whereas if the user copies and paste the dynamic link in browser(Safari) then the token & screen are lost from the that, as the dynamic link is not consistent. And I can see following resolved dynamic link in the app's listener code is : 

**https://links.sprive.com/sprive**

Would you please let me why the dynamic link is behaving in a different way when it is being copied-pasted on the browser.

Please help me to resolve this issue as soon as possible, because the register/login are the core features of my app and that  depends on the dynamic link only, I don't have a backup strategy at this point. And without workable dynamic link, my app will be of no use.

Looking forward to get the resolution on this.

**Comment by mikehardy** [comment]
Hi there!

1) in my experience, relying on dynamic link only is a recipe for failure, they are prone to breaking unexpectedly with various combinations of operating systems and clients. This will not be the last problem you see with them and you should have a fallback mechanism. The problems are in the client apps and operating systems sometimes so it's not even in firebase control. Take that as you want, but it is one of my stronger recommendations: have a fallback mechanism. 2 maybe.

2) check the debug resolution of the link https://firebase.google.com/docs/dynamic-links/debug

3) The problem will likely not be in react-native-firebase - dynamic links problems almost never are. I recommend you try a reproduction at the iOS level with the provided quickstart as a skeleton: https://github.com/firebase/quickstart-ios/tree/master/dynamiclinks in order to reproduce it. My guess is that you will reproduce it with that, implying it is not this module, at which point you can file an issue with firebase-ios-sdk repo (although I recommend searching their issues list as well for links problems etc - this is a difficult area and the older issues are educational)

My tone here is pretty stern - have a backup method! it's probably not RNFB! - but I sincerely hope this helps, it's all based on my experience in this area

**Comment by Shashank123sprive** [comment]
hi @mikehardy ,

Thanks for your valuable suggestions, I'll go through the above and come back to you if needed.
