### ISSUE TITLE
[🐛] relativePath.split is not a function. (In 'relativePath.split('/')', 'relativePath.split' is undefined)

### ISSUE THREAD

**Issue by jafar-jabr** [invertase/react-native-firebase#4689]
"@react-native-firebase/firestore": "10.3.1"
brings the above mentioned bug on update and delete documents (at least)

**Comment by mikehardy** [comment]
You skipped the template, I can't help.

**Comment by jafar-jabr** [comment]
I'm sure you will notice it by yourself, no problem, waiting for next version

**Comment by mikehardy** [comment]
No, our testing suite passes. Until someone points out a bug with details nothing will likely happen. It could be you, and that would be great + helpful, but without following the template (and ideally if you think there is a code issue, pointing out the code and including an App.js that will point it out when dropped in a clean project (like from https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh) -> nothing likely to happen because most issues raised here are actually project-specific problems
