### ISSUE TITLE
<FirebaseCore/FIRAppInternal.h> not found 

### ISSUE THREAD

**Issue by manishpandia** [invertase/react-native-firebase#4770]
I have successfully linked the firebase plugin , but getting issue while implement crashlytics 
'
Error is coming from RNFBCrashlyticsInitProvider.m file 

NOTE: I am not using pod for linking the plugin, following the old step to linking the plugin

**Comment by andersonaddo** [comment]
Template ignored, closing issue. 
Open a new issue and follow the template if ya want any help.

**Comment by mikehardy** [comment]
As a side note - there is no support for non-cocoapods integration. Cocoapods is the standard integration for react-native since 0.60 so any problems compiling that come from other integration styles will be project-specific and we will not be able to offer support

You can see a successful crashlytics integration here (so we know it works) https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh
