### ISSUE TITLE
[🐛] Analytics session start event was not sent after enabling collection on Android

### ISSUE THREAD

**Issue by nicocolascrete** [invertase/react-native-firebase#4820]
Hi everyone,

We disable analytics at the application start and we enable it when user give us authorization ( GDPR flow ). The session_start event is not sent in this case, and we can’t find session_id in our own log events. We iterate with google support on this issue and seems it come from the react-native implementation.
Did you know this issue?
Did you know if it’s possible force this event ( session_start )

Thanks, for your help.

**Firebase informations:**
        "@react-native-firebase/admob": "^10.4.1"
        "@react-native-firebase/analytics": "^10.4.1"
        "@react-native-firebase/app": "^10.4.1"
        "@react-native-firebase/auth": "^10.4.1"
        "@react-native-firebase/crashlytics": "^10.4.1"
        "@react-native-firebase/messaging": "^10.4.1"
        "@react-native-firebase/perf": "^10.4.1"
        "@react-native-firebase/remote-config": "^10.4.1"

**Build gradle:**
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0'
        classpath 'com.google.firebase:perf-plugin:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by mikehardy** [comment]
Hi there! It's software, almost anything is possible :-)
Do you have some cross-link to the related firebase-android-sdk issue so I can see history there, if they have already conclusively determined that firebase-android-sdk would do it but we are not? A lot of times upstream they will simply see you use react-native and pre-emptively close unless you can reproduce based on their quickstart https://github.com/firebase/quickstart-android/tree/master/analytics - have you already done that and it works with their pure native code?

It's difficult to say exactly what is going on in your app since you posted incomplete information vs our template. Specifically it is not clear if you have a firebase.json or not, and if you have one, what the contents are. You also skipped AndroidManifest.xml. Those two in combination would tell me how your analytics startup configuration was working and/or if you were susceptible to the issue that caused us to release 10.5.0 https://github.com/invertase/react-native-firebase/blob/master/packages/analytics/CHANGELOG.md#1050-2021-01-18

When asking for support, I'd strongly recommend actually following the guidelines for support so the conversation is more productive.

As far as I can tell, this is a trivial implementation from our perspective and we're simply calling the underlying firebase-android-sdk method as you'd expect - there is literally nothing here that could really go wrong? https://github.com/invertase/react-native-firebase/blob/c68a62c8bb5afd8d9c1f3df635a87d79f9dcefc0/packages/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java#L48-L53
