### ISSUE TITLE
🔥 [🐛] setUserId(null) does not work

### ISSUE THREAD

**Issue by anuragraina** [invertase/react-native-firebase#4931]
## Issue

`await analytics().setUserId('Some id');` works perfect.

But the issue arises when I set 

- `await analytics().setUserId(null);` or 
- `await analytics().setUserProperty('some_property', null);`

This does not work and the same old id and property is shown in events.

[This comment](https://github.com/invertase/react-native-firebase/issues/1247#issuecomment-467256666) mentions the issue exactly.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.6.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `analytics`
- **Are you using `TypeScript`?**
  - `Y` & `3.8.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Focusing on setUserId: I don't see where in the API that we attempt to mirror exactly (the Firebase JS API) setting a null is supposed to do anything? 

https://firebase.google.com/docs/reference/js/firebase.analytics.Analytics#setuserid

...but that could be a documentation issue, to travel deeper you may follow the information "Use gtag 'config' command to set 'user_id'" and see that even in the deeper information there is no mention of *clearing* a value

https://developers.google.com/analytics/devguides/collection/ga4/persistent-values

I do see how the native APIs allow a null to unset per their documentation:

https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#public-void-setuserid-string-id

https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#+setuserid:


...widening scope back out to look at User Properties, the native SDKs also seem to indicate that clearing is possible (though the JS API is again quiet on the subject)

https://firebase.google.com/docs/reference/ios/firebaseanalytics/api/reference/Classes/FIRAnalytics#+setuserpropertystring:forname:

https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setUserProperty(java.lang.String,%20java.lang.String)

So: it looks like it's possible

Have you examined in the code here (you can just reach right into node_modules `@react-native-firebase/analytics` directory... to see if the javascript (in the 'lib' sub directory) is passing the nulls down to native and/or if the ios / android sub-directories' native code is calling the firebase-ios-sdk / firebase-android-sdk APIs correctly to pass null in and clear things?

That's the next step, and if there is anything to repair there I would happily merge a PR if you posted one up!

**Comment by mikehardy** [comment]
Actually a quick scan of the code indicates it is allowing nulls through:

https://github.com/invertase/react-native-firebase/blob/d6f52cac6397d3adb5441093d5b31bc5636f71b1/packages/analytics/lib/index.js#L134

I believe the native code then will handle the null correctly if it is allowed to pass, calling the firebase SDKs correctly:

https://github.com/invertase/react-native-firebase/blob/d6f52cac6397d3adb5441093d5b31bc5636f71b1/packages/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java#L62-L87

https://github.com/invertase/react-native-firebase/blob/d6f52cac6397d3adb5441093d5b31bc5636f71b1/packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m#L70-L114

The tests even appear to be specifically checking to make sure nulls are usable

https://github.com/invertase/react-native-firebase/blob/d6f52cac6397d3adb5441093d5b31bc5636f71b1/packages/analytics/e2e/analytics.e2e.js#L61-L89

So I'm not sure what the problem is. I would definitely instrument the react-native-firebase java or objective-c code (take your pick) to log out the parameters we send to the native APIs when you send a null in and I bet we are doing the right thing here.

At which point it becomes an upstream bug and I'd advise trying the same test but **without** using react-native-firebase - you have to use the firebase SDKs directly and give the google firebase team a clean reproduction for them to triage an issue. They provide quickstarts that make that easy though: https://github.com/firebase/quickstart-android/tree/master/analytics / https://github.com/firebase/quickstart-ios/tree/master/analytics

**Comment by anuragraina** [comment]
Have been busy with work lately, apologies for delayed response.
We can proceed logging with Java.

Sure, will try testing with firebase SDK

**Comment by mikehardy** [comment]
Hi @anuragraina - just curious if you got a chance to put some printouts in the javascript -> native code to see whether react-native-firebase is sending in the nulls to clear things correctly and move this forward

**Comment by louiszawadzki** [comment]
I had the same issue with `setUserProperty` and did some debugging, so maybe it can help :)  

When trying to call `setUserProperty('usa_code', null), my XCode console would output:

```
User property must be NSString. Value: (nil)
```

After some debugging, I found out that `value` was casted as `NSNull` instead of the expected `nil` - and editing `RNFBAnalyticsModule.m` to pass `nil` instead of `value` every time worked. Now Xcode would output:

```
User property removed. Name: usa_code
```

Now I am trying to find a way to fix this.

**Comment by mikehardy** [comment]
Oh that's fantastic - looking forward to the PR, will check it and if everything looks good will be happy to merge! This one has been a sore point here. Probably a similar issue with Java (just not sending null in the right way?)

**Comment by louiszawadzki** [comment]
Java seemed to work for me (I didn't get any error log). I will get my hands on a real Android device later this week to try and see if it appears as expected in the reports :) 

As for the PR I'll try to open it by the end of the week if it really works :)

**Comment by mikehardy** [comment]
I'm going to reopen this and tag it up for review just in case since the patch exists in a comment at least

**Comment by emilioheinz** [comment]
Hey @mikehardy, we are facing the same issue. Calling `setUserId(null)` seems to do nothing. 
We have tested it on both, Android and iOS and they are not working properly. 
Is there any upcoming release that will fix this? Or should it be fixed already?

**Comment by mikehardy** [comment]
Sorry I don't have solid info but just replying since it was a direct question: there's no current work in this area, so if it is not working with current (13.0.1 IIRC), it will continue not working until it receives attention - apologies

**Comment by emilioheinz** [comment]
It's confirmed, the latest version doesn't work too. Is there any chance to give attention to this ASAP? It may be impacting others too.

**Comment by mikehardy** [comment]
Sorry @emilioheinz this is/was in my queue but obviously I haven't had time to look at it yet, apologies. I can reopen but if a PR doesn't come from someone in the community rolling up their sleeves and investigating a) is it here or native SDKs? and b) posting PR here or logging upstream, there may not be activity for a bit sadly

**Comment by emilioheinz** [comment]
I'll try to take a look at this in some weeks and update it here with my progress. If anyone falls into this issue and wants to work on it, just do it!

**Comment by bonesyblue** [comment]
Hi all 👋 I also encountered this issue in an app I am working on so I have created a PR: https://github.com/invertase/react-native-firebase/pull/6004 to fix this issue. Would love to hear your feedback on this!

**Comment by Nicolakacha** [comment]
I'm using 14.5.0 and this still happen on Android. Anyone still encounter the same issue?

**Comment by dgreasi** [comment]
Happening to me to in debug mode for iOS. I have the following dependencies:

```
"@react-native-firebase/analytics": "^19.2.2",
"@react-native-firebase/app": "^19.2.2",
```

**Comment by olitynskyi-mtb** [comment]
same issue on android, passing null do nothing, check on debug view

**Comment by olitynskyi-mtb** [comment]
<img width="608" height="627" alt="Image" src="https://github.com/user-attachments/assets/bfecd723-e6f0-4640-a6dd-51f405dab45b" />
only if set new string it change property
```
    setUserProperty(analytics, 'country_code', 'null');
    setUserId(analytics, 'null');
```
