### ISSUE TITLE
[firestore] Keeping firestore connected

### ISSUE THREAD

**Issue by DavidKuennen** [invertase/react-native-firebase#495]
I don't know whether this is an issue with firestore, firebase in general or the implementation, but I noticed the following problem: 

Whenever I disable internet access on my emulator or mobile phone while being in my app and then activate internet access again (while still being in my app), document writes are not being completed and I also don't receive updates on my listeners anymore until I kill and restart the app.

Is there some issue that prevents firebase/firestore from reconnecting after having lost the connection once or do I have to implement something myself? 

Application Target Platform: only tested on android
Development Operating System: Windows 10
Build Tools: Android Studio
React Native version: 0.48.4
RNFirebase Version: 3.0.2
Firebase Module: Firestore

**Comment by chrisbianca** [comment]
In short, I don't really know!

With the Realtime Database, we are aware of some issues with RN and it re-establishing the connection as it goes online and offline.  The way around this was to listen to the AppState and manually tell the database to `goOnline` and `goOffline`.

Unfortunately, Firestore doesn't have the same methods available to it, so the same approach wouldn't work here.  To check this isn't an issue with our code, it would be helpful for you to add some native break points on the write method callback and the listener callbacks.  This would at least allow us to prove that it's an issue with the native SDKs rather than us.  At which point you could raise an issue with Google directly...

**Comment by mongris** [comment]
FYI: https://firebase.google.com/docs/firestore/solutions/presence

> The Realtime Database has native support for presence -- that is, being able to tell when a user has come online or gone offline. While we do have a solution for Cloud Firestore, it's not quite as elegant. (from: https://firebase.googleblog.com/2017/10/cloud-firestore-for-rtdb-developers.html)

**Comment by chrisbianca** [comment]
I've just added support for `firebase.firestore().enableNetwork()` and `firebase.firestore().disableNetwork()` to the upcoming v4 release as these methods are now available in the latest versions of the native SDKs.
