### ISSUE TITLE
[🐛] Messaging onTokenRefresh inconsistencies - after deleting the token, listener triggers on iOS but not on Android

### ISSUE THREAD

**Issue by helenaford** [invertase/react-native-firebase#4997]
## Issue

There's differences in behaviour with the onTokenRefresh listener on iOS and Android. On iOS, after deleting the token, and calling getToken, the listener is triggered. I'm unable to recreate the same behaviour on Android.

I suspect this is an issue with the native Android SDK rather than RNFB (see https://github.com/firebase/firebase-android-sdk/issues/2485 why I believe this is the case), but there may be a way to fix it here in RNFB or at the very least update the docs describing the difference.

```
const refreshToken = async () => {
  await firebase.messaging().deleteToken(undefined, '*')
  await firebase.messaging().getToken()
}

function App() {
  useEffect(() => {
    const unsubscribe = messaging().onTokenRefresh(token => {
        console.debug('onTokenRefresn', token)
    });

    return unsubscribe;
  }, []);
}
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
   "@react-native-firebase/app": "^10.5.0",
    "@react-native-firebase/messaging": "^10.5.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 58.16 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 24.0.1, 24.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `Y` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Just to make sure - does this still happen when you use react-native-firebase v11.0.0 ? That included a bump of underlying sdk to firebase-android-sdk 26.6.0 https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#1100-2021-03-03

I give that a 1% chance of making a difference since you have already chased this upstream a bit

A separate 1% chance item, have you reproduced using the quickstart? https://github.com/firebase/quickstart-android/tree/master/messaging - handing a repro repo over typically gets things moving quickly :)

**Comment by mikehardy** [comment]
As for workarounds, a rough sketch?

Goal, remember in our own code that we have done a token delete, so that a subsequent token get knows to work around token refresh not being called, so we can simulate the token refresh call

1. Add state to remember whether onTokenRefresh event should be explicitly emitted about here (or could be code-local to deleteToken/getToken) ? https://github.com/invertase/react-native-firebase/blob/f3b955c0f4ea5e50920499c917576f587f149f93/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java#L30
2. if deleteToken API is called, set that state to "yes, a token refresh event should be emitted"
3. then when getToken returns, check to see if onTokenRefresh event should be explicitly emitted, if so, construct an event with the token - https://github.com/invertase/react-native-firebase/blob/f3b955c0f4ea5e50920499c917576f587f149f93/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java#L53-L57

... and do the thing that is apparently missing - that this override is not being called by firebase-android-sdk superclass - by calling this method explicitly (or copying the implementation)

https://github.com/invertase/react-native-firebase/blob/f3b955c0f4ea5e50920499c917576f587f149f93/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingService.java#L28-L31

**Comment by helenaford** [comment]
Just been thinking something like over in my head how it can be done manually. I've updated the project to use v11 and it's the same behaviour as we thought.

That would be awesome that could be added in, I don't mind working on a p/r around that... if that would be helpful?

**Comment by mikehardy** [comment]
I think you've got the reproduction case all open on your (virtual) workbench, right? I'd merge a PR like that if you know it doesn't work before, should work (e.g., behave same as iOS) and can make the changes that make it happen. Anything that looked like that sketch would be okay by me as long as it had a comment referencing this issue and the upstream issue with clickable links so they could occasionally be checked (and cleaned out) later in case we miss the github traffic

If you've never developed react-native-firebase code before there's two general pathways, one super easy get-it-done-now and one "this might take a while"

Super easy is to reach right into node_modules and work the Java code directly, then just copy that into either github web UI or a local clone of repo for eventual PR

This might take a while is pulling up the full E2E dev env https://github.com/invertase/react-native-firebase/blob/master/tests/README.md and doing test-driven-development with a new test (marked '.only' so you can just hit it over and over) against an emulator with a refresh listener add / delete / get / verify listener was called test.

The full version is the full :trophy: because it gets us an e2e test of course and greater coverage, but it requires a lot more disk and some time to get going

**Comment by mikehardy** [comment]
Appears to have a fix about to land/release https://github.com/firebase/firebase-android-sdk/issues/2485#issuecomment-812151999

**Comment by mikehardy** [comment]
Packaged in firebase-android-sdk 27.0.0, which is blocked transitively by need to forward port admob #5150 - but if you are not using `@react-native-firebase/admob` you should be able to use it via https://rnfirebase.io/#android SDK override

**Comment by mikehardy** [comment]
v12 includes the latest SDKs, this should no longer be an issue - @helenaford - might inspect downstream dependencies? I'll work downstream as well to post an update form them to v12 release and tag you there. Cheers
