### ISSUE TITLE
[🐛] Realtime Database - Transactions not working

### ISSUE THREAD

**Issue by RandomToni** [invertase/react-native-firebase#5070]
## Issue

Hello,

We're are setting up a likes counter for our app using a transaction on realtimeDb. After implementing the following code for the liking the action we can see that the counter goes up only sometimes, failing to commit all of the others. As you can see on the logs included in the attached photo, the code was ran for 3 times, resulting in an increase in the database (commited=true) only once (this is just an example, it can be X likes added in a row or none too, random). 

```javascript

const likeIdRef = this.likesDb.ref(`likes/${id}`)

        const transaction = await likeIdRef.child('likesCount').transaction(likesCount => {
            console.log("likesCount 1", likesCount)

            if (likesCount != null) likesCount++
            console.log("likesCount 2", likesCount)

            return likesCount
        }, (err, commited, snapshot) => {

            if (err) {console.log("error: ", err); return null}
            console.log("snapshot", snapshot)
            console.log("commited", commited)

        }, false)`
```

Any ideas what may be causing this issue? I've search everywhere before posting this bug.

Thank you.

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] Both
  - [ ] 
- **`react-native-firebase` version you're using that has this issue:**
"react-native": "^0.63.3"

- **`Firebase` module(s) you're using that has the issue:**
"@react-native-firebase/database": "^10.8.0",

- **Are you using `Typescript`?**
 -"typescript": "^4.0.5"

![image](https://user-images.githubusercontent.com/15729832/112517334-f4580a80-8d76-11eb-93c9-ef51979fd816.png)

**Comment by mikehardy** [comment]
Hmm - that's unexpected, database module has a fair bit of e2e testing around transactions so this is surprising.
You have omitted huge chunks of the template, but the part you did include indicates you are just a little bit out of date with the library and with the underlying SDKs. In order to triage this we'll really need a reproduction though, which settles all the "template" missing issues at the same time.

Can you post a fully self-contained App.js that reproduces the problem when dropped into the results of a clean project (ideally https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh as that's what I'll use to make the project for triage)

**Comment by mateomarconi** [comment]
@mikehardy I am not able to install your script in my computer. I got a CocoaPod error:

![image](https://user-images.githubusercontent.com/1811137/112576177-922bf380-8dd0-11eb-8c3d-7aff5e9284ad.png)
[error1.txt](https://github.com/invertase/react-native-firebase/files/6209344/error1.txt)

Then I tried to install manually as it said, but it throws another error:
[error2.txt](https://github.com/invertase/react-native-firebase/files/6209345/error2.txt)

Cocoapod version: 1.9.3
Xcode version: xcodeproj (1.14.0)

I am working at the same project so I updated react-native-firebase to 11.1.2 as the documentation said, and tried again but no success at all, I get same random behaviour:

  "@react-native-firebase/app": "^11.1.2"
  "@react-native-firebase/auth": "^11.1.2"
  "@react-native-firebase/database": "^11.1.2"
  "@react-native-firebase/firestore": "^11.1.2"
  "@react-native-firebase/functions": "^11.1.2"
  "@react-native-firebase/messaging": "^11.1.2"
  "@react-native-firebase/remote-config": "^11.1.2"
  "@react-native-firebase/storage": "^11.1.2"

This is our actual react-native version, do you know if this can be the issue?
  "react-native": "^0.63.3"

I am testing in an Iphone 11 Simulator with version 13.1.

Is there any other information that you need from our environment? 
As I didn't create the ticket I am not sure what do you need to investigate it.

I appreciate your help,
Mateo

**Comment by mikehardy** [comment]
Mmm Cocoapods 1.10 is required and ruby on my machine is 2.7.2. That Cocoapods requirement should be enforced by the podspecs I'll have to look at that

**Comment by mikehardy** [comment]
Hi there! I just posted a PR that will make it a lot more obvious (as in: it will refuse to install the pods, with a clear explanation) that we need cocoapods 1.10+ in #5126

But for this issue I'm still waiting on this:

> Can you post a fully self-contained App.js that reproduces the problem when dropped into the results of a clean project (ideally https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh as that's what I'll use to make the project for triage)

**Comment by RandomToni** [comment]
Hi Mike, I'm sorry for the delayed response, let me get to this in the weekend to give you the proper details. Thanks

**Comment by RandomToni** [comment]
Hi,

We were able to run your app without duplicating the issue. Upon finding this, we went back to our app to see what the issue was, drilling down from a basic build to our complex application.
We were able to find the problem. Apparently our environment is setting up our firebase api with a class that initializes a realtime instance for a custom db calling the method 

`firebase.app().database("https://xxx-xxxxxx.firebaseio.com/") `

And now, since we added this like functionally, we are trying to initialize a second instance (on the default db since for now we were just testing), from another class calling

`firebase.app().database() ` 
(afterwards we tried with a custom db and the result was the same 
`firebase.app().database("https://yyy-yyyyyy.firebaseio.com/") `  )

When we realized that we creating these two different instances, we commented out the fist one (xxxx) and the transaction functionality for giving a like worked like a charm.

Is it possible that by giving a specific db route on an instance we're not able to change it for targeting a different one?


Thank you for the added time !

**Comment by mateomarconi** [comment]
@mikehardy 

We fix this by removing the instantiation of the database with the url in the constructor of our class. This was generating conflicts between both database conections. We can close this one!

Thanks very much for your help and attention.

**Comment by photorouletteadmin** [comment]
@mikehardy  Transactions do indeed not work as expected when working with multiple database instances. In our experience, if first initializing multiple database instances, every subsequent transactions will get aborted (committed: false). 

```
import firebase from '@react-native-firebase/app';
import database from '@react-native-firebase/database';

const instance1 = firebase.app().database();
const instance2 = firebase
  .app()
  .database(`https://${firebase.app().options.projectId}.firebaseio.com`);
const result = await instance1.ref('/test').transaction(() => true);
console.log(result.committed); //  returns false
```

I think this is because every database instance listens to every database_transaction_event event - regardless of which database instance it is related to. When receiving an unrelated transaction event, the event handler will then abort the transaction.

The solution would be to somehow make sure DatabaseTransaction instances only respond to relevant transaction events.

**Comment by mikehardy** [comment]
@photorouletteadmin interesting - sorry to hear it's not working. I'll reopen this but to set expectations this will probably not see attention for quite some while without community attention.

That said, if you think you have a PR that would fix it I have a firm commitment to anyone proposing a PR that I will work with you to get it merged and released.

Developing a fix like this is not as hard as it would seem either, if you fork/clone the repo and examine the "tests" app and it's README https://github.com/invertase/react-native-firebase/blob/master/tests/README.md it will have you set up and running the test suite in minutes more or less.

Then if you go into the database e2e tests and [specifically the transactions area](https://github.com/invertase/react-native-firebase/blob/921bd4c7a5b3816c0538671164b8678b42da27e6/packages/database/e2e/reference/transaction.e2e.js#L23), you can rename a test group to be `describe.only` instead of `describe` and if you re-run for example `yarn tests:ios:test-reuse` it will run *just* those test with the same binary even for a lightning fast code/test cycle. `yarn tests:ios:test` reloads native code which is a little slower but still really fast.

That's how I get all the tools laid out in an area I'm going to work on, then I add a new test with just an error, run it, and I go from there. If you open the tests.xcworkspace in Xcode or the tests/android directory in Android Studio, the native code is all wired up (by symbolic links) so native editing is comfortable.

If you give it a shot and post anything I'll collaborate :pray:  :smile:

**Comment by photorouletteadmin** [comment]
Here's how we've solved it for now. This prevents the event handler from aborting unrelated transactions. But ideally I guess the events should be scoped by instance on a more fundamental level.

```
@@ export default class DatabaseTransaction {
  _handleUpdate(event) {
     let newValue;

     const { id, body } = event;
     const { value } = body;
     const { id, body } = event;
     const { value } = body;
 
+    const transaction = this._getTransaction(id);
+    if (!transaction) {
+      return;
+    }
+
     try {
-      const transaction = this._getTransaction(id);
-      if (!transaction) {
-        return;
-      }
       newValue = transaction.transactionUpdater(value);
     } finally {
       let abort = false;
       let abort = false;

       if (newValue === undefined) {
         abort = true;
       }

       this._database.native.transactionTryCommit(id, {
         value: newValue,
         abort,
       });
     }
   }
```
