### ISSUE TITLE
firestore data structure change after RNFirebase update from 3.0.2 to 3.0.3 

### ISSUE THREAD

**Issue by BCGen** [invertase/react-native-firebase#509]
### Issue

after I update RNFirebase from 3.0.2 to 3.0.3, and use firestore function add, set, and update, like under:

```
const data = { age: 22, name: 'Peter' };

firebase.firebasestore().collection('data').add(data);
firebase.firebasestore().collection('data').doc("id").set(data);
firebase.firebasestore().collection('data').doc("id").update(data);
```

the data should be

![1](https://user-images.githubusercontent.com/24768017/31558101-27c4fd8a-b07e-11e7-912b-b63a89f99929.png)

but became

![2](https://user-images.githubusercontent.com/24768017/31558182-78dea07c-b07e-11e7-91f9-c61a93331a5e.png)

### Environment

1. Application Target Platform: **Android**

2. Development Operating System: **Windows 10**

3. Build Tools: **Android Studio**

4. React Native version: **0.49.3**

5. RNFirebase Version: **3.0.3**

6. Firebase Module: **cloud firestore**

**Comment by chrisbianca** [comment]
@BCGen I think your native code might be out of sync with the client side code.  Have you definitely rebuilt your Android app since updating to 3.0.3?  Not just restart the packager?

`RNFirebaseFirestoreDocumentReference.java` should have the following line in it twice:

`Map<String, Object> map = FirestoreSerialize.parseReadableMap(RNFirebaseFirestore.getFirestoreForApp(appName), data);`

It will show once in the `set()` method and once in the `update()` method.

**Comment by BCGen** [comment]
Yes, I forgot rebuild!
after rebuild the problem was solved.
Thank you very much.
