### ISSUE TITLE
Analytics - firebase_error 21

### ISSUE THREAD

**Issue by GFean** [invertase/react-native-firebase#5115]
Hi there , I'm trying to send a nested object with key:value pairs as my event log. It seems to be working, the app doesn't give any errors or something, but it appears errored on firebase. With firebase_error 21 - which according to [Analytics Error Codes](https://firebase.google.com/docs/analytics/errors) must be 

> Event does not support array parameters

below you can see the event I'm trying to test it with and also a payload. 
Thanks for your help in advance !

 `analytics().logEvent("test_event_1", {
        data: {
          testVal: "test"
        },
        dataTwo: {
          testVal: 222
        },
        event: "TEST"
      })}`

**Comment by mikehardy** [comment]
I don't believe that's a valid event style, the firebase-js-sdk types are what we pattern off of (and are also a good expression of what google analytics can actually consume) https://github.com/firebase/firebase-js-sdk/blob/master/packages/analytics-types/index.d.ts

**Comment by RocKer004** [comment]
Hmm.. so it's not possible to pass nested objects as a payload ? 
To be more precise, the goal I'm trying to achieve is to log several informations about the user, which are located in different DTOs. For example if user clicks `removeProductFromCart` button, I want to log which product that was and this is another DTO, if user clicks `clearCart`, I want to log the list of the objects that were contained in the cart before.. 
I hope I explained it in an understandable way. So the result must look something like this : 
`analytics().logEvent('remove_from_cart`, {product: {id: 123, name:"test" ...} userInfo: {id: 123, userName: "test" ...} })`

**Comment by mikehardy** [comment]
> Hmm.. so it's not possible to pass nested objects as a payload ?

If the typings allow it, yes, if they do not, no.

I do not believe they allow it, but the link I sent is canonical - refer to it as the official answer

**Comment by RocKer004** [comment]
I posted on firebase official github as well, no answer so far.. If I send an array of items, it doesn't seem to be appearing at all - do you have any ideas about this ? officially, it should be supported to send array of items.

**Comment by mikehardy** [comment]
@RocKer004 Why *should* it be? Please post to documentation from upstream google analytics and our types that support your assertion. 

Back-end reference https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference
Types as above

**Comment by RocKer004** [comment]
Check official docs for [react-native-firebase/analytics](https://rnfirebase.io/analytics/usage), if you scroll down to custom events, you'll see this kind of sample code there : 
`import react, { useEffect } from 'react';
import { View, Button } from 'react-native';
import analytics from '@react-native-firebase/analytics';

function App() {
  return (
    <View>
      <Button
        title="Add To Basket"
        onPress={async () =>
          await analytics().logEvent('basket', {
            id: 3745092,
            item: 'mens grey t-shirt',
            description: ['round neck', 'long sleeved'],
            size: 'L',
          })
        }
      />
    </View>
  );
}`

**Comment by mikehardy** [comment]
I believe those are allowed by the typings and reference document I linked. I don't believe your nested objects are. A valid example needs to be from the two links I posted, and it may not include "like this..." it must be valid for you to say "the case I want *exactly* matches this type definition"

**Comment by RocKer004** [comment]
I believe that too, I copied the exact same code and when I trigger this event, it never appears in my firebase console. That's what I'm talking about

**Comment by mikehardy** [comment]
I feel like this conversation is unfocused, sorry

You logged an issue with a firebase error code, referencing nested objects that I think are disallowed. As a specific item, my comments there still stand and I have not seen a reference to specific typings for analytics logEvent APIs that would allow what you attempted.

As a separate item you mention you tried sample code and did not see it in your console. I *infer* that means you did not see an error from the sample code, so that is separate from your issue. If you did not see it in your console you may be subject to analytics reporting latency, network blocks on the analytics servers (lots of people put ad-blocker stuff that blocks analytics so they never see events) or you are not set up for analytics debugging which transmits them more quickly or a few other things. But all separate from the issue you logged.

I won't have much time to respond to this unless it stays focused and starts referring to actual type definitions in code, actual log messages from devices with analytics debugging set to true, actual error messages etc. Concrete things
