### ISSUE TITLE
v3 enable database logging?

### ISSUE THREAD

**Issue by minusoneman** [invertase/react-native-firebase#525]
### Issue
I'm trying to debug some listener (on/off) issues with react-redux-firebase, and would like to see firebase database debug output in the console.

In v2 a 
```javascript
{ debug: true } 
```
parameter could be sent to RNFirebase.initializeApp, but since there is no longer a need to initialize the app, where would be the appropriate place to enable console logging?

```javascript
firebase.database.enableLogging(true);
```

is a Web SDK function, so that doesn't work either.

Could I enable debug logging in the Android SDK (like persistence), and read the output directly from the android logs?

Thanks!

### Environment

1. Application Target Platform: 
Both

2. Development Operating System: 

Linux

3. Build Tools: 

4. React Native version: 

0.43.9

5. RNFirebase Version: 
3.0.0

6. Firebase Module: 
database

**Comment by Salakar** [comment]
@minusoneman thanks for flagging, have pushed up a implementation for this. Will be available in the next patch release.

**Comment by ollieh-m** [comment]
@Salakar I've called `firebase.database.enableLogging(true)`, but am not getting anything in the logs about firebase database. Is there any more detail you could give about how to enable logging - in particular I'm trying to see why database rules are violated. Many thanks!

**Comment by Salakar** [comment]
@ollieh-m if you're not already; you need to call `firebase.database.enableLogging(true)` before any usage of `database()` for it to work correctly.

I'd suggest calling it directly after importing `react-native-firebase` - outside of any classes/components.

**Comment by ollieh-m** [comment]
Thanks @Salakar,

I am calling firebase.database.enableLogging(true) as early as I can in the app lifecycle - in App.js. But I get nothing in the xcode logs about the firebase database.

I'm actually importing react-native-firebase in a couple of different places. One in a service object for managing auth, one in a service object for managing the db, and now in App.js in order to enable logging. I didn't think this would make a difference - once enableLogging has been set to true shouldn't that apply to the same, single instance imported everywhere?

Thanks for the great library by the way!
