### ISSUE TITLE
[🐛] TypeError: null is not an object (evaluating 'url.endsWith')

### ISSUE THREAD

**Issue by pramodkumar005** [invertase/react-native-firebase#5284]
## Issue
Getting error
TypeError: null is not an object (evaluating 'url.endsWith')

Whenever creating instance of Realtime database firebase.database() getting this error
![Screenshot_1620580514](https://user-images.githubusercontent.com/11612240/117581026-51860080-b118-11eb-834e-37058da38972.png)

```
import firebase from 'react-native-firebase';
const database = firebase.database();

componentDidMount(){
    // this.checkUserLoggedIn()
    this.checkCompanyExists()
  }

  checkCompanyExists(){
    
    database.ref('organization').on('value', function (snapshot) {
        console.log(snapshot.val())
    })
    .then(snapshot=>{
      console.log(snapshot)
    })
    .catch((error)=>{
              //error callback
              console.log('error ' , error)
    })
  }
```

---

### Javascript

<details><summary>Click To Expand</summary>

#### `package.json`:

{
  "name": "DemoApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-paper": "^4.8.1",
    "react-native-reanimated": "^2.1.0",
    "react-native-router-flux": "^4.3.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^8.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.14.0",
    "@babel/runtime": "^7.14.0",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.26.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
![Screenshot_1620580514](https://user-images.githubusercontent.com/11612240/117581293-b68e2600-b119-11eb-9adb-7414cb05944a.png)

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there! Sorry, this version is unsupported: ` "react-native-firebase": "^5.6.0",`

Please upgrade to current stable and report a new issue if there are still problems, thank you

**Comment by Duc333333** [comment]
[ Individual Contributor License Agreement ("Agreement") V2.0 Thank you for your [Tran van Duc ]()  in The Apache Software Foundation (the "Foundation"). In order to clarify the intellectual property license granted with Contributions from any person or entity, the Foundation must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor, indicating agreement to the license terms below. This license is for your protection as a Contributor as well as the protection of the Foundation and its users; it does not change your rights to use your own Contributions for any other purpose. If you have not already done so, please complete and sign, then scan and email a pdf file of this Agreement to secretary@apache.org. Please read this document carefully before signing and keep a copy for your records.   Full name: ______________________________________________________   (optional) Public name: _________________________________________   Postal Address: ________________________________________________                    ________________________________________________   Country:         ________________________________________________   Telephone: ______________________________________________________   E-Mail:    ______________________________________________________   (optional) preferred Apache id(s): ______________________________   (optional) notify project: ______________________________________ You accept and agree to the following terms and conditions for Your present and future Contributions submitted to the Foundation. In return, the Foundation shall not use Your Contributions in a way that is contrary to the public benefit or inconsistent with its nonprofit status and bylaws in effect at the time of the Contribution. Except for the license granted herein to the Foundation and recipients of software distributed by the Foundation, You reserve all right, title, and interest in and to Your Contributions. 1. Definitions.    "You" (or "Your") shall mean the copyright owner or legal entity    authorized by the copyright owner that is making this Agreement    with the Foundation. For legal entities, the entity making a    Contribution and all other entities that control, are controlled    by, or are under common control with that entity are considered to    be a single Contributor. For the purposes of this definition,    "control" means (i) the power, direct or indirect, to cause the    direction or management of such entity, whether by contract or    otherwise, or (ii) ownership of fifty percent (50%) or more of the    outstanding shares, or (iii) beneficial ownership of such entity.    "Contribution" shall mean any original work of authorship,    including any modifications or additions to an existing work, that    is intentionally submitted by You to the Foundation for inclusion    in, or documentation of, any of the products owned or managed by    the Foundation (the "Work"). For the purposes of this definition,    "submitted" means any form of electronic, verbal, or written              communication sent to the Foundation or its representatives,    including but not limited to communication on electronic mailing    lists, source code control systems, and issue tracking systems that    are managed by, or on behalf of, the Foundation for the purpose of    discussing and improving the Work, but excluding communication that    is conspicuously marked or otherwise designated in writing by You    as "Not a Contribution." 2. Grant of Copyright License. Subject to the terms and conditions of    this Agreement, You hereby grant to the Foundation and to    recipients of software distributed by the Foundation a perpetual,    worldwide, non-exclusive, no-charge, royalty-free, irrevocable    copyright license to reproduce, prepare derivative works of,    publicly display, publicly perform, sublicense, and distribute Your    Contributions and such derivative works. 3. Grant of Patent License. Subject to the terms and conditions of    this Agreement, You hereby grant to the Foundation and to    recipients of software distributed by the Foundation a perpetual,    worldwide, non-exclusive, no-charge, royalty-free, irrevocable    (except as stated in this section) patent license to make, have    made, use, offer to sell, sell, import, and otherwise transfer the    Work, where such license applies only to those patent claims    licensable by You that are necessarily infringed by Your    Contribution(s) alone or by combination of Your Contribution(s)    with the Work to which such Contribution(s) was submitted. If any    entity institutes patent litigation against You or any other entity    (including a cross-claim or counterclaim in a lawsuit) alleging    that your Contribution, or the Work to which you have contributed,    constitutes direct or contributory patent infringement, then any    patent licenses granted to that entity under this Agreement for    that Contribution or Work shall terminate as of the date such    litigation is filed. 4. You represent that you are legally entitled to grant the above    license. If your employer(s) has rights to intellectual property    that you create that includes your Contributions, you represent    that you have received permission to make Contributions on behalf    of that employer, that your employer has waived such rights for    your Contributions to the Foundation, or that your employer has    executed a separate Corporate CLA with the Foundation. 5. You represent that each of Your Contributions is Your original    creation (see section 7 for submissions on behalf of others).  You    represent that Your Contribution submissions include complete    details of any third-party license or other restriction (including,    but not limited to, related patents and trademarks) of which you    are personally aware and which are associated with any part of Your    Contributions. 6. You are not expected to provide support for Your Contributions,    except to the extent You desire to provide support. You may provide    support for free, for a fee, or not at all. Unless required by    applicable law or agreed to in writing, You provide Your    Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS    OF ANY KIND, either express or implied, including, without    limitation, any warranties or conditions of TITLE, NON-    INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 7. Should You wish to submit work that is not Your original creation,    You may submit it to the Foundation separately from any    Contribution, identifying the complete details of its source and of    any license or other restriction (including, but not limited to,    related patents, trademarks, and license agreements) of which you    are personally aware, and conspicuously marking the work as    "Submitted on behalf of a third-party: [named here]". 8. You agree to notify the Foundation of any facts or circumstances of    which you become aware that would make these representations    inaccurate in any respect. Please sign: __________________________________ [ Individual Contributor License Agreement ("Agreement") V2.0 Thank you for your [Tran van Duc ]()  in The Apache Software Foundation (the "Foundation"). In order to clarify the intellectual property license granted with Contributions from any person or entity, the Foundation must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor, indicating agreement to the license terms below. This license is for your protection as a Contributor as well as the protection of the Foundation and its users; it does not change your rights to use your own Contributions for any other purpose. If you have not already done so, please complete and sign, then scan and email a pdf file of this Agreement to secretary@apache.org. Please read this document carefully before signing and keep a copy for your records.   Full name: ______________________________________________________   (optional) Public name: _________________________________________   Postal Address: ________________________________________________                    ________________________________________________   Country:         ________________________________________________   Telephone: ______________________________________________________   E-Mail:    ______________________________________________________   (optional) preferred Apache id(s): ______________________________   (optional) notify project: ______________________________________ You accept and agree to the following terms and conditions for Your present and future Contributions submitted to the Foundation. In return, the Foundation shall not use Your Contributions in a way that is contrary to the public benefit or inconsistent with its nonprofit status and bylaws in effect at the time of the Contribution. Except for the license granted herein to the Foundation and recipients of software distributed by the Foundation, You reserve all right, title, and interest in and to Your Contributions. 1. Definitions.    "You" (or "Your") shall mean the copyright owner or legal entity    authorized by the copyright owner that is making this Agreement    with the Foundation. For legal entities, the entity making a    Contribution and all other entities that control, are controlled    by, or are under common control with that entity are considered to    be a single Contributor. For the purposes of this definition,    "control" means (i) the power, direct or indirect, to cause the    direction or management of such entity, whether by contract or    otherwise, or (ii) ownership of fifty percent (50%) or more of the    outstanding shares, or (iii) beneficial ownership of such entity.    "Contribution" shall mean any original work of authorship,    including any modifications or additions to an existing work, that    is intentionally submitted by You to the Foundation for inclusion    in, or documentation of, any of the products owned or managed by    the Foundation (the "Work"). For the purposes of this definition,    "submitted" means any form of electronic, verbal, or written              communication sent to the Foundation or its representatives,    including but not limited to communication on electronic mailing    lists, source code control systems, and issue tracking systems that    are managed by, or on behalf of, the Foundation for the purpose of    discussing and improving the Work, but excluding communication that    is conspicuously marked or otherwise designated in writing by You    as "Not a Contribution." 2. Grant of Copyright License. Subject to the terms and conditions of    this Agreement, You hereby grant to the Foundation and to    recipients of software distributed by the Foundation a perpetual,    worldwide, non-exclusive, no-charge, royalty-free, irrevocable    copyright license to reproduce, prepare derivative works of,    publicly display, publicly perform, sublicense, and distribute Your    Contributions and such derivative works. 3. Grant of Patent License. Subject to the terms and conditions of    this Agreement, You hereby grant to the Foundation and to    recipients of software distributed by the Foundation a perpetual,    worldwide, non-exclusive, no-charge, royalty-free, irrevocable    (except as stated in this section) patent license to make, have    made, use, offer to sell, sell, import, and otherwise transfer the    Work, where such license applies only to those patent claims    licensable by You that are necessarily infringed by Your    Contribution(s) alone or by combination of Your Contribution(s)    with the Work to which such Contribution(s) was submitted. If any    entity institutes patent litigation against You or any other entity    (including a cross-claim or counterclaim in a lawsuit) alleging    that your Contribution, or the Work to which you have contributed,    constitutes direct or contributory patent infringement, then any    patent licenses granted to that entity under this Agreement for    that Contribution or Work shall terminate as of the date such    litigation is filed. 4. You represent that you are legally entitled to grant the above    license. If your employer(s) has rights to intellectual property    that you create that includes your Contributions, you represent    that you have received permission to make Contributions on behalf    of that employer, that your employer has waived such rights for    your Contributions to the Foundation, or that your employer has    executed a separate Corporate CLA with the Foundation. 5. You represent that each of Your Contributions is Your original    creation (see section 7 for submissions on behalf of others).  You    represent that Your Contribution submissions include complete    details of any third-party license or other restriction (including,    but not limited to, related patents and trademarks) of which you    are personally aware and which are associated with any part of Your    Contributions. 6. You are not expected to provide support for Your Contributions,    except to the extent You desire to provide support. You may provide    support for free, for a fee, or not at all. Unless required by    applicable law or agreed to in writing, You provide Your    Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS    OF ANY KIND, either express or implied, including, without    limitation, any warranties or conditions of TITLE, NON-    INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. 7. Should You wish to submit work that is not Your original creation,    You may submit it to the Foundation separately from any    Contribution, identifying the complete details of its source and of    any license or other restriction (including, but not limited to,    related patents, trademarks, and license agreements) of which you    are personally aware, and conspicuously marking the work as    "Submitted on behalf of a third-party: [named here]". 8. You agree to notify the Foundation of any facts or circumstances of    which you become aware that would make these representations    inaccurate in any respect. Please sign: __________________________________ Date: ________________  ]()
