### ISSUE TITLE
🔥 [🐛] undefined props are converted to null when writing data to firestore

### ISSUE THREAD

**Issue by goleary** [invertase/react-native-firebase#5304]
## Issue

When I write a document to firestore with a prop with the value `undefined` it is converted to `null` before it's written.

This behavior is not consistent with web either [firebase](https://www.npmjs.com/package/firebase) or [firebase-admin](firebase-admin) which will both throw an error unless you have set `ignoreUndefinedProperties: true` using `firestore.settings({ ignoreUndefinedProperties: true })`.

I expect the same behavior as other versions  firebase (error thrown) & it would be awesome if `rnf` exposed the `ignoreUndefinedProps` setting because really what I want is for these undefined to result in these props being left out of the db update.

```
const testCollection = firestore().collection('test');
await testCollection.add({
  time: new Date(),
  u: undefined,
  n: null,
});
```

result in db:
![image](https://user-images.githubusercontent.com/16123225/118051203-72776d00-b335-11eb-8f15-5850b1097cdb.png)

[Here](https://github.com/invertase/react-native-firebase/blob/0217bff5cbbf233d7915efb4dbbdfe00e82dff23/packages/firestore/lib/utils/serialize.js#L108) is the line of code that appears to be converting these `undefined` props to `null` before sending them over the bridge.

---

## Project Files

Minimal repro can be found [here](https://github.com/goleary/rnfUndefinedRepro)

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "rnfundefinedrepro",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-firebase/app": "^11.5.0",
    "@react-native-firebase/firestore": "^11.5.0",
    "react": "17.0.1",
    "react-native": "0.64.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 32.66 GB / 63.74 GB
  Binaries:
    Node: 12.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 15.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `firestore`

</p>
</details>

**Comment by mikehardy** [comment]
Interesting :thinking: - thanks for the repo (w v11.5.0 hot off the presses even...)
admin can be discarded as a reference point - web is sufficient as an argument, we *intend* to operate like web so we are a drop-in (but with extra native features)

Do you have the link handy that shows how web deals with it? https://github.com/firebase/firebase-js-sdk/ - if you root around in there it shouldn't be too awful to find

Seems like the right thing based on your analysis is:
- expose the setting to ignore undefined
- throw if !ignoringUndefined && value === undefined

...assuming the firebase-js-sdk code agrees (which I'm sure it will)

**Comment by mikehardy** [comment]
Incidentally - if you have the time to propose a PR to do the thing we can merge and release extremely quickly. Following this https://github.com/invertase/react-native-firebase/blob/master/tests/README.md to get set up then setting this line to `describe.only` (vs `describe`) https://github.com/invertase/react-native-firebase/blob/0217bff5cbbf233d7915efb4dbbdfe00e82dff23/packages/firestore/e2e/firestore.e2e.js#L250 gets a really tight development iteration going, and adding a new setting value may be all in javascript-land even (though the native code isn't too hard to edit either)

Otherwise this will be in the queue behind quite a pile of other things at the moment as the underlying SDKs both just issued a big batch of breaking changes

**Comment by goleary** [comment]
Thanks for the quick response (and all your hard work on this project) @mikehardy 

>Do you have the link handy that shows how web deals with it? https://github.com/firebase/firebase-js-sdk/ - if you root around in there it shouldn't be too awful to find

[Here](https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/firestore/src/lite/user_data_reader.ts#L727) is where the `firebase-js` sdk appears to be handling `undefined` values. I believe that the `null` returned results in the property being removed and not sent to firestore.  It looks like [this](https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/firestore/src/lite/user_data_reader.ts#L889) is the line that throws when a value is `undefined` & `ignoreUndefinedProperties` is falsy.

> if you have the time to propose a PR to do the thing we can merge and release extremely quickly.

Sounds good, I'll look into the dev setup and see if I can put something together.

**Comment by mikehardy** [comment]
I followed through that code from the links and agree fully with the analysis. I think this will be a breaking change (though a relatively minor one) but I've got a breaking change release coming anyway, so the timing is good.

Also it *does* look like it's completely in javascript because the firebase-js-sdk defines this in settings:

https://github.com/firebase/firebase-js-sdk/blob/5ad7ff2ae955c297556223e6cb3ad9d4b897f664/packages/firestore/src/lite/settings.ts#L31-L38

But there is no native analog (which also explains why it wasn't implemented - probably an oversight since native didn't have it, or perhaps it was added after for JS):

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestoreSettings.Builder#public-method-summary
https://firebase.google.com/docs/reference/ios/firebasefirestore/api/reference/Classes/FIRFirestoreSettings

I just checked and it appears that the native layers will ignore keys in the settings object they are not aware of, so it should be safe to put web-only keys in there for JS processing without fear of blowing up native

So any change here would *not* be added / sent through to the native layer, the setting would have to be held in the javascript layer with javascript layer filtering same as firebase-js-sdk (though not quite as heavily engineered...)

I'm struggling a little with how best to hold javascript settings in firestore since this would be the first one, so currently they are sent to native then just dropped.

RemoteConfig holds javascript settings and might serve as a pattern https://github.com/invertase/react-native-firebase/blob/837f36c01a56440764ccf35932f9df3c0f7f6c19/packages/remote-config/lib/index.js#L54

so add a this._settings to Firestore in the constructor with defaults and add a getter
add new key here here https://github.com/invertase/react-native-firebase/blob/837f36c01a56440764ccf35932f9df3c0f7f6c19/packages/firestore/lib/index.js#L188
follow pattern of ssl enabled for validation
then before going down to native layer save a copy of settings
then in places where you're parsing field values, get the settings and check if undefined should be ignored?

:thinking:  just a rough sketch, maybe it's useful? if you go in there and discover some reason why that won't work and have a better idea, assume you're right and go for it for a draft as I haven't tried any of my sketch out so it hasn't met reality yet

**Comment by jmif** [comment]
Hey @mikehardy thanks for the guidance here!  Opened a PR https://github.com/invertase/react-native-firebase/pull/5312
