### ISSUE TITLE
[🐛] Bug Report Title - CRUD operations in offline mode - Firestore - Android

### ISSUE THREAD

**Issue by AkshayAdiga1997** [invertase/react-native-firebase#5397]
### Versions used:
1. "react": "16.13.1"
2. "react-native": "0.63.2"
3. "@react-native-firebase/app": "^11.4.1"
4. "@react-native-firebase/firestore": "^11.4.1"

### Issue:
I want to fetch data from a collection from firestore. But each time I fetch, I want to fetch only the delta (added/updated) documents. This is my approach.

I have a field called **modified_date** (shorthand md) and **local_modified_date** (shorthand lmd). The modified_date has the value `firestore.FieldValue.serverTimestamp()` and local_modified_date has the value `firestore.Timestamp.now()`. These values are computed while adding/updating a document.

So first I fetch all the documents from my local cache and store it in redux. Meanwhile I find out the modified_date of the latest document (by comparing modified_data.seconds value). I convert it into date format. Let's call it **last_fetch_timestamp**.

Now I read data from server where md (modified_date) is greater than equal to last_fetch_timestamp.

### Code:
```
let all_data = {};
firestore()
.collection(collection_name)
.where('md', '>=', last_fetch_firestore_timestamp)
.onSnapshot({includeMetadataChanges: true}, (snap) => {
snap.docChanges().forEach((change) => {
    const doc = change.doc;
    const docName = doc.id;
    const docData = doc.data();
    if (!docData.md) {  // Can add doc.metadata.hasPendingWrites as an and condition to this
        docData['md'] = docData['lmd'];
    }
    all_data[docName] = docData;
});

```
The value if docData.md is not null when the internet is on as the server timestamp is created and it returns the document with the timestamp value. This works perfectly on IOS and Android.
But in offline mode, since the value is not set, the md value will be null. Hence I set it to lmd.
This works perfectly on IOS but fails Android. The document added/updated won't be part of snapshot itself. But if I remove the where clause (which is required to fetch delta documents), it works.
Thanks.

**Comment by mikehardy** [comment]
Hi there! Sorry for the delay - also this seems like the sort of thing that will *likely* result in an issue upstream in firebase-android-sdk. I think the first step is to determine exactly which layer the platform difference is in: is it in react-native-firebaase, or the underlying SDK?

Easiest way to do that is to get the testing app set up here (it's actually not too hard to set up: https://github.com/invertase/react-native-firebase/blob/master/tests/README.md) and extend one of the existing tests in `packages/firestore/e2e/**/*.js` to probe this case and also maybe PR a new test that shows it (so it will never happen again once fixed...) or just use your existing case while instrumenting this module's code directly in node_modules to print out in Java what it's getting from firebase-android-sdk we can see if we're getting the values from the SDK we expect or not.

If the SDK turns out to be where the oddity lies then the next step is to open an issue in the firebase-android-sdk with a reproduction at the native level showing the problem - luckily that's usually not difficult either as they provide "quickstart" demos that handle all the scaffolding and allow you to just put in the exact code necessary to show something: https://github.com/firebase/quickstart-android/tree/master/firestore

If the SDK seems fine and it's in react-native-firebase then we'll also have a reproduction (and perhaps a test already) that will pinpoint the issue and we can work up a PR

**Comment by AkshayAdiga1997** [comment]
@mikehardy Thank you so much for this awesome library. I will tell you what problem people like me have. I have 0 knowledge regarding the native IOS/Android. Hence I hardly understand their code and not sure if I will be able to identify the issue :( I know you guys are super busy with your personal work. Not sure how I will be able to solve/debug this issue. No problem. Thanks again.

**Comment by mikehardy** [comment]
Not knowing something is an opportunity to learn. That's how all us maintainers got to the point where we could help. It sounds like you've assumed you won't be able to tell without even trying. Did you actually give it a try? The tests repos and quickstarts all run out of the box so it's a good way to get started.
