### ISSUE TITLE
[🐛] iOS 14.6 setBackgroundMessageHandler not working

### ISSUE THREAD

**Issue by catalsrun** [invertase/react-native-firebase#5416]
## Issue

I updated macOS to Big Sur 11.4 version and Xcode from 12.4 to 12.5.

index.js
```javascript
import { AppRegistry } from 'react-native'
import App from './src/App'
import { name as appName } from './app.json'
import messaging from '@react-native-firebase/messaging';

messaging().setBackgroundMessageHandler(async remoteMessage => {
  // iPhone7 iOS 14.4.2 is working well on both background and quit mode.

  // But, iPhone12 Pro Max iOS 14.6 is not working on both background and quit mode.
});

AppRegistry.registerComponent(appName, () => App)
```

package.json
```json
{
 "dependencies": {
    "react-native": "0.63.4",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/messaging": "^12.1.0"
 }
}
```

**Call remote notification from Node server**

server.js
```javascript
const admin = require('firebase-admin'); // ver 9.9.0
admin.initializeApp({
  credential: admin.credential.cert('xxx.json'),
});

admin.messaging().send({
    data: {
      type: 'test',
      content: 'hello world',
    },
    apns: {
      payload: {
        aps: {
          contentAvailable: 1,
        }
      },
      headers: {
        'apns-push-type': 'background',
        'apns-priority': '5',
        'apns-topic': 'Your Bundle Identifier Here'
      }
    },
    topic: 'TestTopic',
  })
```

In advance, thank you.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
If one phone version is working, that means in general the code here (react-native-firebase) is working.
If another is not working, that means something is different, but it is something to do with the phone, not this module - in other words there likely will not be any change to this module in response to anything from this issue, so I will close it.

However, and much more helpfully! Please examine the Xcode arguments you can supply in order to get more information when launching the app from the Xcode console. The firebase-ios-sdk project documentation has details but in particular I believe you will want `-FIRDebugEnabled` 

You will notice our issue tracker is littered with subtle project-specific / phone-specific issues similar to this, all resolved through investigation and configuration changes on either phone or FCM payload etc https://github.com/invertase/react-native-firebase/issues?q=is%3Aissue+FIRDebugEnabled
