### ISSUE TITLE
iOS as soon as we receive push notification with deep link safari opens up

### ISSUE THREAD

**Issue by bonti370** [invertase/react-native-firebase#5459]
### Discussed in https://github.com/invertase/react-native-firebase/discussions/5458

<div type='discussions-op-text'>

<sup>Originally posted by **bonti370** June 28, 2021</sup>
I am facing one issue on iOS, where as soon as we receive push notification with deep link safari opens up. This is happening even when the user is not even clicking on notification. 

"react-native": "0.63.3",
"@react-native-firebase/dynamic-links": "^12.0.0",</div>

**Comment by mikehardy** [comment]
Hi there!

A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this one is going to be the complete JSON block that triggers this behavior when you send it via the FCM REST API using a command line utility to post it, such as `curl`

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send I think is the docs for that

You were very selective in the information you provided on the template, from a troubleshooting behavior that will potentially lead to poor outcomes

**Comment by raldred** [comment]
We've also had this for ages on our app and have just worked around it. The app always boots silently on iOS from closed state as soon as a notification is received.

**Comment by mikehardy** [comment]
AppState (which works a bit better than isHeadless implemented here, because of #5388 ) seems like the thing to use if you need a workaround, is that your strategy @raldred  ? This sounds like project-specific code executing. Also, do you have any notification extensions or similar running? I wasn't aware the app actually booted when you received nothing but a notification block, that said we do not have the actual FCM JSON here to inspect so it's hard to reason about what exactly is happening
