### ISSUE TITLE
useFunctionsEmulator not working with @react-native-firebase/functions

### ISSUE THREAD

**Issue by francesco-clementi-92** [invertase/react-native-firebase#5462]
## Issue

Describe your issue here
---

As described in your documentation https://rnfirebase.io/functions/usage#using-an-emulator, to connect with the emulator is necessary to call `functions().useFunctionsEmulator('http://localhost:5001')`, but when I try to use `functions().httpsCallable('function name')` I get ERROR NOT_FOUND.

The problem seems to be the region of the functions (europe-west3) which is not default one.

If I start my app with:
```
import firebase from '@react-native-firebase/app';
firebase.app().functions('europe-west3').useFunctionsEmulator('http://localhost:5001');
```

and call the functions like this:
```
import firebase from '@react-native-firebase/app';
firebase.app().functions('europe-west3').httpsCallable('function name')();
```
everything work correctly, but at this point the @react-native-firebase/functions module seems to be useless.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^11.5.0",
"@react-native-firebase/auth": "^11.5.0",
"@react-native-firebase/crashlytics": "^11.5.0",
"@react-native-firebase/firestore": "^11.5.0",
"@react-native-firebase/functions": "^11.5.0",
"@react-native-firebase/messaging": "^11.5.0",
"@react-native-firebase/ml": "^11.5.0",
"@react-native-firebase/storage": "^11.5.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

> at this point the @react-native-firebase/functions module seems to be useless.

"useless" how? What did you then do (show code), what actually happened (show results), vs what did you expect to happen?

Side note: your dependencies are out of date, troubleshooting (that is: logging any issue on any project, this one included) on old versions is inefficient as frequently it means chasing down problems that are already fixed

In particular for your case you might override the firebase-ios-sdk (https://rnfirebase.io/#ios) to be even more current than we have released so far, in order to get this: https://firebase.google.com/support/release-notes/ios#cloud-functions

although you omit entirely the troubleshooting section where we ask about android or ios so I have no idea what platform you have the problem on, or if your project integration in those areas is correct

**Comment by francesco-clementi-92** [comment]
I'm really sorry for my bad attitude. 

Actually I can't update  the dependencies because I need @react-native-firebase/ml -> cloudDocumentTextRecognizerProcessImage.

I didn't followed the template because the problem for me it's solved, but maybe is usefull for other developers after that I spent hours to find out the root cause. 

To fix the problem I need to use the module @react-native-firebase/app, settings the functions emulator with the app instance and call the functions with the app instance. 

I was expecting to use @react-native-firebase/functions to set the emulator and call the functions as written in the documentation, but is not working. 

I'm using windows for android development and Mac OS for iOS development on the same app and the problem is for both the environments.

**Comment by mikehardy** [comment]
> I'm really sorry for my bad attitude.

No worries, this stuff can be very frustrating, and anyway I did not read it as bad attitude, I was really just curious about the details of what *exactly* didn't work as it seemed like it may be a total failure to work (which would certainly be useless...). As it is an import that does not seem to work is a bit useless although it's a good thing there's a different way to access the functionality

> Actually I can't update the dependencies because I need @react-native-firebase/ml -> cloudDocumentTextRecognizerProcessImage.

Ah yes - sorry that's not available externally yet, thanks for your patience

With regard to platforms I think this is more a javascript thing so I agree, the platforms (dev OS, target OS) are not as relevant.

I think this whole area will change and be a lot more understandable + behave as expected when we finish ingesting the "modular" firebase-js-sdk APIs where instead of having the javascript imports add things to app, every package really is separate - https://firebase.google.com/docs/web/learn-more#modular-version

Until then, this information (how to set and use functions emulator + custom region) should help others

**Comment by vargajacint** [comment]
@mikehardy Is it solved or not?

I'm using Cloud functions with emulator, and I'm trying to call `firebase.app().functions("europe-west3").httpsCallable("fnName")` and always returning "Unauthenticated" error. Of course I'm authenticated, and it works correctly on production.

Deps:
"@react-native-firebase/functions": "^13.0.1"
"@react-native-firebase/app": "^13.0.1",

**Comment by mikehardy** [comment]
Looks like it should be working with current firebase-tools package, c.f. https://github.com/firebase/firebase-tools/issues/3418#issuecomment-849568196
