### ISSUE TITLE
Can't navigate to any insite screen when click Noti (App in Quit) using fire-base-V7 ! I Needs Help Now. Tks all

### ISSUE THREAD

**Issue by leductien197** [invertase/react-native-firebase#5499]
- My RootNavigation.js
- ![Screen Shot 2021-07-08 at 17 22 17](https://user-images.githubusercontent.com/61132856/125019286-ea95b100-e0a0-11eb-8032-dc66783f03ee.png)

- FCMServices.js 
![Screen Shot 2021-07-09 at 10 34 56](https://user-images.githubusercontent.com/61132856/125019493-5d9f2780-e0a1-11eb-81ba-7e8d20036216.png)

- App.js
- 
![Screen Shot 2021-07-08 at 17 21 01](https://user-images.githubusercontent.com/61132856/125019678-a820a400-e0a1-11eb-8834-80efdd5e763e.png)

**Comment by mikehardy** [comment]
Ignored the template completely. We have an issue template for a reason and we need the information there in order to help.
Also please please please post *text* ideally within

```javascript
// code blocks like this - check the markup, it's easy
```

so we can read them

Images are not easy to work with.

That said, this will not be a problem with the module, nothing learned here will result in a change here, it will be in your project. For project-specific usage questions, stackoverflow is a better venue
