### ISSUE TITLE
Reactnative app not listening any socket from firebase

### ISSUE THREAD

**Issue by faisalhatila** [invertase/react-native-firebase#5553]
I am working on a react native app, below mentioning of rn firebase versions
"@react-native-firebase/app": "10.0.0", (tried with the version "12.0.0" and "11.0.0")
"@react-native-firebase/messaging": "10.0.0",(tried with the version "12.0.0" and "11.0.0", but)
Testing device: IPhone 6
OS:12.5.4
not receiving any socket logs firing from firebase simulator and postman request.
![s1](https://user-images.githubusercontent.com/43320236/127340517-8a33a419-ed7a-4250-8f51-a115229c8e2e.png)
![s2](https://user-images.githubusercontent.com/43320236/127340538-5789bf0e-ac41-42df-a27c-56fea1a174f6.png)
![s3](https://user-images.githubusercontent.com/43320236/127340541-02cf5a5a-8c94-4660-870f-79c3e7fc46a6.png)

**Comment by mikehardy** [comment]
Hi there! This does not follow issue template and is thus missing a lot of information. I'm going to close it, and if you still have an issue you can reproduce please open a new issue and fill in the information

Some guidelines -
- use current stable versions for reproduction only. No attempt will be made to help on older versions because it may just be referencing the old issues that caused us to release the new versions
- please try to condense your problem down to a simple standalone App.js we can drop in to a clean project (like https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh) so we can avoid unrelated problems (https://stackoverflow.com/help/minimal-reproducible-example)
- please do not post any images. Post the text containing the problem, I will not attempt to read images. Enclose it in triple backticks so it's easy to read, like:

```javascript
// this here is a code block in markdown
```

- If you are having messaging problems please read the official google documentation on how to turn on debugging, for instance I believe you want something like `-FIRDebugEnabled` as a build argument in your scheme, then you need to watch the Xcode console logs when you launch the app on a real device
- for messaging related issues please post the actual JSON you can send via the FCM REST API that triggers the problem, just remove any API keys or device tokens for security

Please note that FCM delivers to APNS, and APNS (from Apple) delivers to the device. You may have an incorrect expectation if you expect sockets to firebase servers, that's not how FCM works. There is a good video on the official firebase youtube channel that explains FCM delivery as well as ways to troubleshoot it, it should be possible to find it with a quick search
