### ISSUE TITLE
[📚] Add comparison with Official Firebase SDK and highlight benefits

### ISSUE THREAD

**Issue by batjko** [invertase/react-native-firebase#5683]
## Documentation Feedback

> Please describe your documentation issue or suggested improvement in detail here and provide links to any pre-existing/relevant documentation and screenshots if necessary:

I would like to suggest adding a section to the top of the docs explaining why one would want to use these packages, as opposed to the official Firebase SDK.
It's not obvious from the docs or the Github repo, and given the amount of work going into keeping this suite of packages up-to-date and bugfixing it, why should a new developer who is starting with Firebase choose react-native-firebase?

Ideally, a few examples could demonstrate the differences and make it easy to see what benefits one gets, but even just a sentence or two explaining the main differences should do it.

**Comment by mikehardy** [comment]
Hi there!

"The official Firebase SDK" - which one? Do you mean firebase-js-sdk? I am going to guess you do - but I make a point of asking because should realize that all we're really doing here is wrapping firebase-android-sdk and firebase-ios-sdk  - also "official Firebase SDKs", and in fact, we are doing so here largely at the behest of Google/Firebase! It's an official thing and we collaborate with them a lot as new APIs go out among the entire ecosystem (the various SDKs, react-native-firebase here, FlutterFire in the Flutter ecosystem) :-)

That said, going with the assumption you mean firebase-js-sdk I can understand the question - and I think there are two good answers:

- there are more modules in the native SDKs than the web SDK because some things only make sense in a mobile / native context (Dynamic Links, App Distribution, Crashlytics), so you can actually do more, and some of it is important for e.g., app virality, like Dynamic Links or quality (crash reporting)
- some of the modules that are both in the web SDK and native SDK have a great deal more functionality when they can harness native APIs, like messaging (with background delivery that can start your app if not running), like App Check where you can tie the attestation to device-level providers, Storage where you can do background downloads, Performance where you can start measurements from boot, etc.

So, you can use the JS SDK, and it does work. And if you don't need any of the native-only or native-better things firebase offers, then JS SDK may be the appropriate choice. But there are real benefits to a binding down to the native SDKs, enough so it makes sense for this project to exist.

Could this be a page on the website itself? Indeed it could, and that's a good idea. I think I've answered your specific question for details but I'll leave this open pending a docs addition.

**Comment by batjko** [comment]
That makes a lot of sense, thank you for the explanation.

You're right I meant the JS SDK, which I had used briefly before and it seemed to do what was needed, so I haven't had a reason to dig into some of the differences between that and the native mobile SDKs, so really wasn't aware there were any significant ones. In fact I (naively) thought they all wrap exactly the same API for consistency.

But it makes sense that mobile devices would allow for more and different goodies.

**Comment by mikehardy** [comment]
Closed in #5950
