### ISSUE TITLE
[🐛] putFile storage very slow

### ISSUE THREAD

**Issue by jeroen-van-dijk** [invertase/react-native-firebase#5705]
I've been trying to upload files using `FirebaseStorageTypes.Reference.putFile`
The upload is really slow! Does anyone have an idea how I can improve the performance?

**Comment by mikehardy** [comment]
WIth apologies - no idea - this may be project or device+network specific? I know that there are no real code limits at least, as our e2e tests use the emulator (which is still "across the network" from the android emulator, and the android emulator itself is typically slower than a normal phone (especially in the github actions macOS runners - they are low performance) and I had to disable certain of our tests in that environment because the upload was so fast. Specifically I was no longer able to do "pause upload" or "pause download" tests because they would always complete faster then the next javascript looper tick, even with 10MB files.

So I'm going to have to put the burden on you to prove this is an issue - if you can produce a https://stackoverflow.com/help/minimal-reproducible-example (say, an App.js that when you push a button uses react-native-fs to dynamically generate a file of sufficient size to cause the problem you see and then attempts to upload it with a timer and then outputs the timing result...) then we can investigate

**Comment by jeroen-van-dijk** [comment]
Mike. Thanks for the quick response. Excuse me for my badly written down issue. I was wondering if there was an issue known to the community but it seems like it was indeed my own setup. I had a very slow upload speed while testing this video. Should have tested that first. 
Thanks again for the quick response and have a nice day!

**Comment by mikehardy** [comment]
No problem - really glad to hear you hadn't discovered a real performance issue in the module, performance issues are so hard to fix... Cheers
