### ISSUE TITLE
[🐛] Android build issue 12 and higher 

### ISSUE THREAD

**Issue by valdio** [invertase/react-native-firebase#5834]
## Issue

Unable to build the android app targeting Android 12 and higher. 

**Manifest Merging Errors:**
my_app.react-native-firebase_analytics manifest Error: android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. my_app.app main manifest (this file) 

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
dependencies {
    "@react-native-firebase/analytics": "^13.0.0",
    "@react-native-firebase/app": "^13.0.0",
    "react": "17.0.2",
    "react-native": "0.66.1",
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy

buildscript {
    ext {
        kotlinVersion = '1.3.50'
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        supportLibVersion = "29.0.0"
        ndkVersion = "21.4.7075529"
    }
    repositories {
        jcenter()
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath 'com.google.gms:google-services:4.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 563.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_272 - /usr/bin/javac

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `13.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `N` 
</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Strange, I'm not able to reproduce this.
The `@react-native-firebase/analytics` package itself does not define any activities or services or receivers that would normally need the android-12-compliance exports added: https://github.com/invertase/react-native-firebase/blob/main/packages/analytics/android/src/main/AndroidManifest.xml

I provide a reproducible example here that demonstrates it working: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

In particular I just made this change and it ran successfully locally:
https://github.com/mikehardy/rnfbdemo/commit/218f551c831c3df4d0034b9783459e833ec880e5

You have not provided all the information from our app template, so I can only suspect your versions are out of date somehow - perhaps you are overriding firebase-android-sdk and not using the current 29.0.0 version of the underlying SDK?

Since I have a reproducible example of it working with current versions, I don't think there's any action to take here. We can reopen if there's some new information pointing at a problem here though of course
