### ISSUE TITLE
Why Firebase Crashlytics  reporting is delayed (it is reporting after reopening app)???

### ISSUE THREAD

**Issue by Vamsi-Rayapati** [invertase/react-native-firebase#5978]
If you have any issue on reporting after app crashed , please mention it here , if i had any solution i will send...

**Comment by mikehardy** [comment]
What's happening is that when your app is crashed it is just crashed, it's not running and can no longer upload anything.
The next time there is any of your code running, meaning, it will have a chance to upload something, is when you restart the app, so that's when it sends

I believe this is documented in the firebase docs upstream?

For the future: https://stackoverflow.com/help/how-to-ask
