### ISSUE TITLE
[🐛] onMessage() not called for for data-only iOS FCM, even on foreground

### ISSUE THREAD

**Issue by Avishayy** [invertase/react-native-firebase#5987]
## Issue

Just like @chrisrollins mentioned in #5908, the iOS data-only messages are broken on v6.

I did read [the documentation on how to send data-only messages](https://rnfirebase.io/messaging/usage#data-only-messages), sending the data-only message along with `content_available: true` does 'fix' it, but the appearing message is missing the `from` and `ttl` keys which were (and still are) present in v5.

In Android, it works just fine, but in v5 and v6. I do understand that there was a big refactor between v5 and v6 but essentially only iOS has these annoying breaking changes while Android does not.

Here's how I have been sending a message so far with [PyFCM](https://github.com/olucurious/PyFCM):
```
from pyfcm import FCMNotification
fcm = FCMNotification(api_key=...)
fcm_token = '...'
data = { 'test': "123" }
fcm.send_device_data_message(registration_id=fcm_token, data_message=data)
```

and this is how the result was intercepted at the app through `messaging.onMessage()` at Android with react-native-firebase v6
```
 {
  "sentTime": 1641320068324,
  "data": {
    "test": "123"
  },
  "messageId": "0:1641320068339137%19549fb6f9fd7ecd",
  "ttl": 2419200,
  "from": "179667159224" // the project number of the firebase app
}
```

Android react-native-firebase v5
```
{
  "_data": {
    "test": "123"
  },
  "_from": "179667159224",
  "_messageId": "0:1641325374068878%19549fb6f9fd7ecd",
  "_sentTime": 1641325374052,
  "_ttl": 3600
}
```
iOS v5 (mind you, **both simulator and a real device**):
```
 {
  "_data": {
    "test": "123"
  },
  "_from": "179667159224",
  "_messageId": "-MsadQR5jZjOZJR915mW",
  "_ttl": 3600
}
```

However, iOS v6 (**real device only**, simulator doesn't work) only works if I do this in PYFcm:
```
fcm.send_device_data_message(registration_id=fcm_token, data_message=data, content_available=True)
```
```
{
  "messageId": "1641319541474655",
  "data": {
    "test": "123"
  },
  "contentAvailable": true
}
```

note  the missing `from` field

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^14.1.0",
    "@react-native-firebase/messaging": "^14.1.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hey @Avishayy ! You've ignored the entire template. I generally need to make sure folks are on current versions prior to spending any time on triage, you'll understand that to do otherwise frequently results in re-chasing closed issues.

Seeing the exact JSON (minus the device token(s) of course) you are sending would be very helpful.
An exact set of steps to reproduce would also be helpful just to make sure, even if it's just "use app on ios version whatever, send app to background, wait 60 seconds for device state to stabilize, send JSON (specified in new comment) via PyFCM to device, examine this that and the other, should be ABC is actually XYZ"

Thinking forward though - you appear to have investigated this quite a bit - have you checked into the .m files that implement this in ios ? It might be a matter of some tiny change - a couple of lines no more - wherein you could patch it in node_modules to make sure your hunch is correct and fixed by whatever the probably obvious changes are, then you could raise a PR?

**Comment by Avishayy** [comment]
Yes, sorry, I've updated it with some more details.

Key difference between iOS v5 and v6:
1. V6 doesn't work without `content_available=True
2. No `from` and no `ttl`
3. I**t doesn't work on a simulator**

I kept searching around and found this issue: https://github.com/firebase/firebase-ios-sdk/issues/9151

Might be an issue of https://github.com/firebase/firebase-ios-sdk, but it's odd that it did work before, oh well..

**Comment by mikehardy** [comment]
Interesting - this may be a bit challenging for me as I became involved in the project at *exactly* that conversion time between v5 and v6+, so I am not really familiar with the v5 codebase - I kept it on lifesupport until v6+ was fully ready for adoption but v6+ is really all I know. For instance, I had no idea data-only messages worked on v5, nor that you did not need content-available JSON key for it.

Unfortunately this may be difficult to isolate as the firebase-ios-sdk itself has changed so much between our v5 here and our v14.2.1 here.

The best path forward if you have the time is to reach into the .m files in node_modules for the messaging module here and do a log output of the entire object that comes in from the underlying SDK to see if the properties you mention (ttl, from) exist in any way that we could bubble up to the javascript layer.

The content-available thing has been a requirement for more than 2 years now so while that is a notable change I'm not sure it's worth pursuing - I believe it is checked on purpose, and also that iOS requires it for data only messages according to their APNS spec ?

That it works on simulators in v5 is pretty handy, but I think this might be more due to the direct channel that firebase used to maintain for FCM prior to one of their firebase-ios-sdk updates where they began to rely completely on APNS to simplify the behavior (and troubleshooting) required to understand messaging delivery. For now I think you can use command line utilities to force a simulator to receive an .apns file as if it were a remote APNS notification?

That leaves the most interesting items as the from and ttl JSON properties I think

**Comment by Avishayy** [comment]
Your comment was very informative @mikehardy, thank you.

I will dump the object and see if it has the needed properties, if not - I'll go and talk with the sdk repo.

Do you have a link on the command line utility you mentioned for using ANPS through the simulator?

Thanks!

**Comment by Avishayy** [comment]
The SDK does pass the key `google.c.sender.id` which is equal to the original `from` key, opening PR to add it :)

**Comment by mikehardy** [comment]
That's fantastic, sincere thanks. I'm working towards a release today so your PR (already merged --> :trophy: ) will be out shortly.

If TTL isn't available, and firebase-ios-sdk no longer does direct connections (meaning simulator FCM simply will not work anymore) I think we may be out of actionable items here, though I do empathize that's a regression in functionality. That would imply it's close-able, but you may still have some investigation avenues to pursue ? What do you think?

**Comment by Avishayy** [comment]
Fortunately, I'm not interested in TTL. As for the simulator, the only thing I have left is to keep hating on Apple, sadly. Not having simulator support is a pain but not a deal breaker. The current state with the new release is good enough for me now, thank you @mikehardy

**Comment by mikehardy** [comment]
`xcrun simctl push .....` is the magic that will help diminish the hating I think, though nothing excuses the Xcode experience haha
https://betterprogramming.pub/how-to-send-push-notifications-to-the-ios-simulator-2988092ba931
or a package (but requires infrastructure, the "Mint" Swift package tool?) https://github.com/AvdLee/Poes
