### ISSUE TITLE
Update typings file to include firestore.

### ISSUE THREAD

**Issue by harisvsulaiman** [invertase/react-native-firebase#599]
### Issue
Typings doesn't include the types for firestore. I would very much appreciate if typings are included as intelisense on vscode depends on it.

### Environment

1. Application Target Platform: 
Both

2. Development Operating System: 
Linux

3. Build Tools: 

4. React Native version: 
50.0.0

5. RNFirebase Version: 
3.1.0

6. Firebase Module: 
Firestore

**Comment by chrisbianca** [comment]
From @Salakar on another issue:

@taljacobson made the original typings and we're not users of typescript ourselves, so it's not something we're overly familiar with or keep updated for that reason.

However, ideally they need a full rewrite, they're 2 major versions out of date and I think this same issue will happen on other modules except for auth and database. So if someone would like to champion this and send in a PR to fully update them that'd be awesome! 👍

Otherwise, we will get to this in due course.

**Comment by harisvsulaiman** [comment]
@chrisbianca I started working on the typings, but I'm busy right now. I hope i can submit a PR in time.

**Comment by chrisbianca** [comment]
See: https://github.com/invertase/react-native-firebase/pull/771
