### ISSUE TITLE
getFirebaseRoot.admob is not a function on React Native

### ISSUE THREAD

**Issue by jossifelefteriadis** [invertase/react-native-firebase#6047]
Creating a react-native app and trying to ad ads through admob and firebase, but getting an error I couldn't find much on. The app works as usual til `showAds` get's called.

Relevant parts of my App.js:

```
...
import {
  InterstitialAd,
  TestIds,
  AdEventType,
} from '@react-native-firebase/admob';
...
showAds = () => {
    let interstitial = InterstitialAd.createForAdRequest(TestIds.INTERSTITIAL);

    let interstitialListener = interstitial.onAdEvent(type => {
      if (type === AdEventType.LOADED) {
        interstitial.show();
      }
    });
    interstitial.load();

    return () => {
      interstitialListener = null;
    };
  };

onEvent = e => {
    if (e.type === 'game-over') {
      this.setState({
        running: false,
      });
      this.showAds();
};
```

<img width="323" alt="Screenshot 2022-02-02 at 20 56 54" src="https://user-images.githubusercontent.com/54796194/152232133-03cb8dee-5c45-491b-8fa9-4d5c337d6d55.png">

**Comment by mikehardy** [comment]
Admob is no longer a part of firebase - it is not supported here and has not been since version v11.5 - what you want is https://github.com/invertase/react-native-google-mobile-ads/ - v4 is stable, it's going to leave beta and be in full / stable release later today, so installing the `@beta` tag means you'll just be the first person with the actual stable version, there won't be any code changes
