### ISSUE TITLE
[📚] Documentation Issue    PAGINATION FIREBASE

### ISSUE THREAD

**Issue by sunset1234321** [invertase/react-native-firebase#6055]
https://rnfirebase.io/firestore/usage-with-flatlists

this doesn't have guidance for doing PAGINATION in firestore.  Could we have it?

**Comment by andersonaddo** [comment]
Since pagination is something pretty implementation specific (and also something you can find loads of guides on over the internet), I doubt its something the core contributors will spend time documenting. It's easy to go online to find many different guides, each with their own method of implementation for specific constraints. You can even use guides that aren't firebase-specific, since many of the implimentations of pagination are backend-agnostic.

It also doesn't help that pagination and infinite scroll are two very different things, and people often confuse/conflate the two.

But hey! It's open-source. If you'd like a guide, feel free to make a PR.
For the sake of good faith, there's how I implemented infinite scroll for my old startup:

https://github.com/emitapp/emit-public/tree/master/src/components/lists
But a

**Comment by yslDevelop** [comment]
If it's still open, can I take a shot?

**Comment by mikehardy** [comment]
YES! 🙏 🙏  I would personally love to see it, and I'm sure it will help anyone in the future

**Comment by yslDevelop** [comment]
Thank you :)
I will work on it asap 😀

**Comment by yslDevelop** [comment]
I hope I made it through.
If I missed anything listed on contributing.md, please let me know 😀

**Comment by mikehardy** [comment]
With huge thanks to @yslDevelop for creating the page and @andersonaddo for sharing his code, we have a pagination document now! :muscle: :nerd_face:  ("nerd power!")

**Comment by yslDevelop** [comment]
This really means a lot to me! thank you 😀
