### ISSUE TITLE
Making project more granular? i.e. Analytics / Crash / Database etc ...

### ISSUE THREAD

**Issue by IljaDaderko** [invertase/react-native-firebase#61]
I've came across one case today where `react-native-firebase` fell short. I wanted to integrate https://github.com/tylermcginnis/re-base into the project and would need to use default firebase js sdk in that case. That lead me to think and ask this question. Would it make sense to make project more granular? i.e. Allow to use auth and database from javascript sdk and turn to `react-native-firebase` for missing features like Analytics / Crash reporting etc.. ?

One similar (less popular and not so well tested) solution I was able to find is: https://github.com/yutin1987/react-native-bridge-firebase maybe it can give some ideas. I think you guys are doing great job so far 👍 giving us a bit more control like this is really welcome in my opinion.

**Comment by chrisbianca** [comment]
Making RNFirebase granular comes with quite a large amount of added complexity. In the same way that the Firebase web SDK is a single module handling everything that the web can do, I think a combined module for RN makes sense.

As RNFirebase is a drop in for the web SDK, a better way of approaching this might be to take a look at the re-base library (which looks quite interesting by the way - thanks for mentioning) and see whether that could be changed to take an initialised Firebase object rather than relying directly on the web SDK.

That way the user could make the decision on whether they want to use the Web version, or the native version.

I hope that makes sense?

**Comment by IljaDaderko** [comment]
@chrisbianca it does, will start an issue there referencing this one, thanks for feedback :)

**Comment by Ehesp** [comment]
One of the issues with using the web SDK, especially with database, is you don't get access to device specific functionality like offline persistence and such. You'll also start getting janky animations while doing large queries on the database too due the JS thread competing.

On the other hand however, rebase does look pretty nice - and currently doing something with Redux/other libs is very DIY. I'll take a look into rebase, see if we can make them place nicely together, somehow.

**Comment by IljaDaderko** [comment]
Sounds awesome, just created issue there as well if you guys want to weight in :)

**Comment by IljaDaderko** [comment]
@chrisbianca @Ehesp Got a reply from them, there is already a pr that will allow usage with custom firebase instance: https://github.com/tylermcginnis/re-base/issues/202#issuecomment-295646684  there is implementation example there, but I don't believe modules can be imported like this from `react-native-firebase` any chance you could suggest how this would look with your library?

**Comment by Ehesp** [comment]
@IljaDaderko once v3 is fully published I can take a look into this, but for now there's no point in trying to integrate into v2. Looking at the code though, it technically should work since it's not actually modifying anything. Will close for the time being.
