### ISSUE TITLE
What is Property 'utmParametersDictionary' not found on object of type 'FIRDynamicLink *' error?

### ISSUE THREAD

**Issue by knevagi** [invertase/react-native-firebase#6106]
I am trying to integrate dynamic links with my react native iOS project. I followed the steps in rnfirebase page for dynamic links but now I am getting this error in Xcode

`Property 'utmParametersDictionary' not found on object of type 'FIRDynamicLink *'`

What does that mean? Thanks in advance.

**Comment by mikehardy** [comment]
I think it is this https://github.com/invertase/react-native-firebase/issues/5773 - duplicate

**Comment by knevagi** [comment]
But all my firebase documents are of the same version and there is no overriding code in Podfile

```
    "@react-native-firebase/analytics": "^14.5.0",
    "@react-native-firebase/app": "^14.5.0",
    "@react-native-firebase/auth": "^14.5.0",
    "@react-native-firebase/dynamic-links": "^14.5.0",
    "@react-native-firebase/firestore": "^14.5.0",
    "@react-native-firebase/messaging": "^14.5.0",
    "@react-native-firebase/storage": "^14.5.0",
```

**Comment by mikehardy** [comment]
@knevagi something is wrong with the firebase-ios-sdk version you are bringing in, or the build system has cached something. Examine Podfile.lock to make sure firebase-ios-sdk is curent stable version (8.12.1) and do `npx react-native-clean-project` to make sure caching is blown out. This is 100% a stale version of firebase-ios-sdk, there is no other technical explanation that fits, since the symbols are there in current versions of firebase-ios-sdk
