### ISSUE TITLE
[📚] firebase.json processing requires Python2 but requirement is not verified or documented

### ISSUE THREAD

**Issue by ttdatt** [invertase/react-native-firebase#6194]
## Documentation Feedback

This package use python 2 script to encode firebase.json configuration and add that base64 string with the key `firebase_json_raw` to Info.plist. But Apple will no longer bundle Python 2.7 with macOS 12.3

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by andersonaddo** [comment]
You could install it though, no? Is this a blocking issue, or do you think its just something we should add to the docs?

**Comment by ttdatt** [comment]
> You could install it though, no? Is this a blocking issue, or do you think its just something we should add to the docs?

Because from MacOS 12.3, Apple remove Python 2.7. And like I said react-native-firebase is using Python2 script, the package cannot read config in `firebase.json` if python2 doesn't exist. This issue drove me crazy, I have to debug to know why the configuration in `firebase.json` didn't work. I think you should add Python2 installation in Getting Started or somewhere in the doc.

**Comment by mikehardy** [comment]
Whatever part of the system is requiring python should verify existence of python2 
The documents should note it

also could a good time to port to python3 really, we're going to have a breaking change release soon probably since it's almost google i/o time and google does them then, might be a good time

Or even better, whatever is happening in python should be ported to javascript since we know we have node available

**Comment by mikehardy** [comment]
I forward ported to python 3 in #6234 and released as v14.9.2
