### ISSUE TITLE
[🐛] Firebase and Google Maps

### ISSUE THREAD

**Issue by dwidc** [invertase/react-native-firebase#6218]
## Issue

Just a heads up. If you use Firebase together with Google Maps, the API key in downloaded `google-services.json` could incorrectly point to google Maps API, not your Firebase API.

This is an issue with Firebase, not the react-native-firebase library. The library works fine. 
Related issue: https://github.com/google/play-services-plugins/issues/151

When executing  `messaging().getToken()` I always got:
```
[Error: [messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR]

FirebaseMessaging: Failed to get FIS auth token
FirebaseMessaging: java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
```
until I realized the API key in `google-services.json` is just plain wrong.

The solution is to simply edit `google-services.json` and change `api_key` with the correct one.
To get correct API key, open your google Cloud console -> APIs & Services -> Credentials -> API Keys, check the one auto created by Firebase.

Hope this helps others with similar issue.
Regards.

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Oh, my, goodness. Thanks for pointing that out, I'm not sure anyone here with older projects that tried to add Maps would know if you didn't help publicize it.

Hopefully you don't mind me closing it because it's not really actionable, but the info is good.

According to that thread, projects created after March 11 2022 or so won't have this problem, but otherwise the info above looks correct - hand-hack your API keys then things will work, or *maybe* you can fix it in the API explorer according to the thread linked above

Thanks @dwidc
