### ISSUE TITLE
[🐛] Expo - ios React Native Firebase - pod install not working

### ISSUE THREAD

**Issue by rahul2992** [invertase/react-native-firebase#6323]
Hi everyone

I am trying to use expo with react native firebase in the config plugin as explained on the link [](https://rnfirebase.io/#installation-1)

The installation is working for android, but for ios I am running in the following error. Any guidance would be helpful. Thank you

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

I have tried running with use_modular_headers! in the PodFile to install the pods. Post which I run into the following issue:

  510 | 
  511 | // They need the definitions of integer types.
> 512 | #include "glog/log_severity.h"
      | ^ import of module 'glog.glog.log_severity' appears within namespace 'google'
  513 | #include "glog/vlog_is_on.h"
  514 | 
  515 | // Initialize google's logging library. You will see the program name

**Comment by rocket13011** [comment]
I solved my problem by putting : 
```pod 'GoogleUtilities', :modular_headers => true``` in podfile so that it updates before FirebaseCoreInternal otherwise there is an error.

**Comment by mikehardy** [comment]
With apologies, please let me set clear expectations

- none of the primary maintainers use Expo
- You must be very specific about *exactly* how to reproduce your problems starting from scratch.
- In general you should expect that Expo-specific problems must be solved by Expo community members.
- If there are deficiencies in the Expo-specific instructions and/or the Expo config plugins they will necessarily require Expo-community members to post PRs to repair them.

We provide a module that is tested thoroughly in a non-Expo environment.
I provide a reproduction script that builds it and runs it from scratch in a non-Expo environment https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

That's our commitment currently as maintainers. We need the Expo community to step up directly for Expo-specific issues, and our commitment is to then *merge* things for Expo folks, but we will likely not be able to actually help you troubleshoot much or create PRs.

**Comment by rahul2992** [comment]
@mikehardy - Thank you. Noted. 
@rocket13011 - Will try the fix you cited.

**Comment by RodolfoGS** [comment]
I created a new issue with the steps to reproduce and a repo: https://github.com/invertase/react-native-firebase/issues/6332

**Comment by mikehardy** [comment]
@RodolfoGS thanks posting a repro!

What happens if you affect this:

https://github.com/RodolfoGS/FirebaseCoreInternal-issue/blob/4c626b5cdcac40ec99a1c2b3fead2ae5db61670e/ios/Podfile#L16

Experiments to run:

1- make that line say *nothing* except `use_frameworks!` (that is: no linkage stuff after)
2- make that line say `use_frameworks! :linkage => :dynamic` (note! This should be same result as experiment 1, dynamic is the default)
3- make that line say `use_frameworks! :linkage => :static`

I'm not sure how exactly you would configure that in `Podfile.properties.json` so that you are doing it The Expo Way but based on the results of the experiments above we may have a working solution for cocoapods, then (assuming we find one that works) we can back that in to Podfile.properties.json

Note that use_frameworks interacts with Hermes and Flipper and react-native 0.69 with varying degrees of success depending on static or dynamic linkage. See https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2924919 In general you should disable hermes and flipper if you use use_frameworks right now, and you should be on react-native 0.68.2 or lower, 0.69.0 won't work. (0.69.1 will have hermes and 0.69.1 working,  but flipper will still not work pending a PR in the area...See https://github.com/reactwg/react-native-releases/discussions/23#discussioncomment-3012014)

**Comment by mikehardy** [comment]
I just realized I'm on a closed issue and your repro is on the new issue, I am going to re-post there and hide my comment here to keep conversation in one spot where possible

**Comment by Aris-ngoy** [comment]
> I solved my problem by putting :
> `pod 'GoogleUtilities', :modular_headers => true` in podfile so that it updates before FirebaseCoreInternal otherwise there is an error.

thanks

**Comment by TowhidKashem** [comment]
> I solved my problem by putting : 
> 
> ```pod 'GoogleUtilities', :modular_headers => true``` in podfile so that it updates before FirebaseCoreInternal otherwise there is an error.

Hey there! I take it you're on the unmanaged workflow? I'm on managed so don't have the iOS folder and associated pod files exposed.

I think the solution needs to be on the config plug-in level for it to work on the managed workflow.
