### ISSUE TITLE
getIsHeadless() always returns false

### ISSUE THREAD

**Issue by ghiculescualexandru** [invertase/react-native-firebase#6429]
Seems like the documentation says that for _react-native-navigaton_ **getIsHeadless()** function can be used to see your app headless state. However, it seems that it always returns false. After some digging, I can see in this merged **PR** (https://github.com/invertase/react-native-firebase/pull/4304) that **isHeadless** is set to **YES** only `if rctRootView is != nil`. But on react-native-navigation the rctRootView is **always** nil. 

I'm only talking about iOS.

Was this tested? Is there any way we can have the headless check available for react-native-navigation?

Thanks in advance

**Comment by mikehardy** [comment]
> Was this tested?

This was not tested with react-native-navigation probably

>  Is there any way we can have the headless check available for react-native-navigation?

Sure - determine some way to check headless state in both react-native-navigation or not-react-native-navigation setups and post a PR and I'll happily merge it. This isn't a use case of mine (or many others I guess? since it hasn't come up over years) so it will have to be community driven

**Comment by billnbell** [comment]
???
