### ISSUE TITLE
I'm getting this error after installing react-native-firebase in my project. I have tried several solutions that I can't even list here

### ISSUE THREAD

**Issue by Ademie** [invertase/react-native-firebase#6505]
`xcodebuild[4439:42557] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore ** BUILD FAILED **`

This error comes up after adding `#import <Firebase.h>` to the top of `AppDelegate.m` file

and `[FIRApp configure];` within existing `didFinishLaunchingWithOptions` method.

I have also added `use_frameworks!` and `$RNFirebaseAsStaticFramework = true` to /ios/Podfile.

Finally I have run these commands `cd ios && pod install --repo-update`

**Comment by mariomurrent-softwaresolutions** [comment]
Same here

**Comment by mikehardy** [comment]
Hi there! You can list the things you have tried. Also, you can refrain from deleting the issue template when logging an issue. Without that information we can't help, and I will close it.

Here's a fully scripted reproducible demo of integrating react-native-firebase with a project from scratch (`npx react-native init...`) - you may see the steps required by examining the comments and looking at the result of running it: https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by reynerdev** [comment]
Same here, RN 61 
![image](https://user-images.githubusercontent.com/58928047/188364530-3aa7baab-5a17-4a54-bcf1-73ed8bc7d8ea.png)

**Comment by mikehardy** [comment]
@reynerdev - a) current releases require Xcode 13.3+, b) Xcode 12.4+ is not usable by react-native lower than 0.64 if I recall correctly, your dependencies are effectively too old to support. Also current releases here only support iOS 11+ (not 8)

That said, I see that message in my builds and it is actually a warning. This issue is misattributing the message described as the source of the failure but it is not, most likely you need to look higher up in the log
