### ISSUE TITLE
[🐛] Error to initialize firebase

### ISSUE THREAD

**Issue by korbonya** [invertase/react-native-firebase#6509]
Hello there you awesome person;

I had this in my custom build expo app 

`Error: You attempted to use a firebase module that's not installed on your Android project by calling firebase.app()`

**Comment by mikehardy** [comment]
Hi there! No information required for troubleshooting has been provided.
Expo projects in particular are troublesome because there are so many varieties of ways to build them, and many of them don't work or require customization, you should carefully specify how to reproduce, and perhaps pursue help in Expo forums among those that have gotten it to work

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/mcve
