### ISSUE TITLE
New Documentation required according to react 18.1.0 version and react native 0.70 version

### ISSUE THREAD

**Issue by keerthipativinaykumar** [invertase/react-native-firebase#6540]
## Documentation Feedback

Documentation which is available is not working properly with new versions of react native and react in mobile apps so please we need to update the firebase documentation accordingly

problem :

When starting new project react native 0.70 version installing firebase package latest version 15.4.0 and then running pod install inside iOS getting error after folioing documentation https://rnfirebase.io/#configure-firebase-with-ios-credentials here we have appDelegate.mm file in new versions and in documentation its not there previously we have appDelegate.m file but now its not presents and by placing according to documentation #import <Firebase.h> on top of appDelegate.mmfile and inside laucnoptions [FIRApp configure]; then installing pod install its getting errors like frameworks errors and then solving those also getting one by one more errors in only new version.

so please update react native firebase documentation or else please suggest us the solutions for that because I was trying solutions for those since 1 week
---

**Comment by mikehardy** [comment]
Hi there! You need to post the frameworks errors you are getting, it is not efficient to guess.

AppDelegate.m vs AppDelegate.mm is a minor difference and surely not the source of the problems.

I have react-native-firebase working with react-native 0.70 here as a full start-to-finish demonstration, and you may read the comments on each line to determine the integration necessary

https://github.com/mikehardy/rnfbdemo/blob/rn0.70/make-demo.sh

If there is something missing in our documentation (other than perhaps saying "in your AppDelegate.m *or your AppDelegate.mm for newer react-native*") let us know

If you are having difficulty because other modules are not compatible with use_frameworks I can understand the difficulty, but you'll need to open issues with those modules and use react-native-firebase v14 until all of your modules are compatible with use_frameworks

**Comment by keerthipativinaykumar** [comment]
yes sure, now I have downgraded to v14 from v15 of react native firebase package and its working fine thanks for your valuable suggestion

**Comment by mikehardy** [comment]
Sure thing @keerthipativinaykumar please note though - if you use modules that are not compatible with use_frameworks you will need to open issues specifying the build errors in those repos, or they won't know they have a problem, and you will be stuck on old versions of  react-native-firebase forever. Eventually that means it won't be compatible with future versions of iOS etc, so it should be worthwhile to at least start exploring use_frameworks compatibility with those repos. Cheers
