### ISSUE TITLE
firebase refs returning stale data even with keepSynced(true)

### ISSUE THREAD

**Issue by dannycochran** [invertase/react-native-firebase#659]
### Issue

With persistence enabled, Firebase is returning stale data on refs when the ref is completely removed from Firebase. Steps to reproduce:

**1. Establish a ref on a resource, e.g:**
```javascript
const appRef = firebaseApp.database().ref();

const getUserData = (uid) => {
  const path = `users/${uid}`;
  appRef.child(path).keepSynced(true);
  return appRef.child(path).once('value');
};
```

Not sure it matters, but the user resource in firebase here has a nested JSON schema:

```javascript
user: {
  profile: {...},
  permissions: {...},
  otherData: {...}
};
```

**2. Delete the users/uid resource from the firebase UI, and refresh the app. The app will return the existing data of the user, instead of null.** 

It's also worth noting that my app appears to be caching way more than 10 MB -- I'm seeing 74MB of storage used by my app, and the app itself is only 23 MB.

Clearing the app storage fixes this issue.

### Environment

1. Application Target Platform:  Android

2. Development Operating System: macOS 10.12.6

3. Build Tools: Nexus_5X_API_23_G120

4. React Native version:  0.49.5

5. RNFirebase Version: 3.1.1

6. Firebase Module: database

**Comment by Salakar** [comment]
@dannycochran thanks for the cleanly written issue :)

-----

> It's also worth noting that my app appears to be caching way more than 10 MB -- I'm seeing 74MB of storage used by my app, and the app itself is only 23 MB.

It's worth noting that when a location is kept synced it does not get evicted from the persistent disk cache, so this is separate from the 10mb as far as I know, screen from official docs:
![image](https://user-images.githubusercontent.com/5347038/33578946-097df526-d940-11e7-9265-ac703236b53b.png)

Having said that 74mb does sound like a lot to be just firebase - are you using external images in your app? React Native automatically caches these using their internal library Fresco - I think, don't quote me on that :)

-----

> With persistence enabled, Firebase is returning stale data on refs when the ref is completely removed from Firebase.

This does sound like an issue with the Firebase Android SDK unfortunately. We don't cache any paths and their data internally - we generally 1 - 1 map directly to the native SDK's, [database/RNFirebaseDatabase.java#L120](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java#L120) & [database/RNFirebaseDatabaseReference.java#L51](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseReference.java#L51) in this case for example.

I'd suggest flagging an issue if possible re the android SDK, you might have better luck than we do flagging this, otherwise we can try flag this ourselves as well.

**Comment by dannycochran** [comment]
roger that, I'll try to find a contact point for this and report back

**Comment by chrisbianca** [comment]
@dannycochran did you ever hear back from Firebase? I'm going to close this as it's not something we have control over, but please do let us know what Firebase have to say...

**Comment by dannycochran** [comment]
@chrisbianca sorry for the slow reply. It's definitely out of your control. I didn't really get a ton of info from the Firebase team. Here's what I think is happening, though:

When the app is closed, and a resource gets deleted remotely (e.g. using the Firebase UI), Firebase still has the data on disk and has not received updated data from the server. When re-opening the app, there's a race condition between firebase establishing a connection to the app instance, and calling for the data using a one-time observer.  In our case, we were trying to retrieve data on app launch before Firebase had established a connection with the app instance, so Firebase was reading from disk instead of trying to connect to the network to retrieve the latest data.

My understanding is that Firebase suggests everyone use "on" listeners instead of "once" listeners, so eventually you'll get the correct data. 

We actually ended up abandoning the offline mode for react-native-firebase altogether in favor of rolling our own with AsyncStorage.
