### ISSUE TITLE
react-native-firebase Typescript support for Multi-factor Auth

### ISSUE THREAD

**Issue by BasBouw** [invertase/react-native-firebase#6672]
I think something is missing in index.d.ts around line 317
Something like :

    /**
     * A multiFactor interface.
     */
    multiFactor(auth: FirebaseAuthTypes.Module): Promise<MultiFactorUser>;

**Comment by mikehardy** [comment]
As discussed on this review thread for a related PR: https://github.com/invertase/react-native-firebase/pull/6683#discussion_r1019052060 we want this to be more firebase-js-sdk compatible

Proposed solution (which I need to implement or someone else can PR if they like) -

1- export a `multiFactor` method on auth instance that takes a *User* argument
2- implement in main auth package javascript file a multiFactor method that
- verifies user argument === currentUser (since native is single user / current user) and errors if not
-  creates a new MultiFactor object with self as argument and returns that
3- deprecate the static multifactor so that people use `auth().multifactor` instead of `auth.multifactor` so the new API becomes the important one, and schedule it for removal in RNFBv17

That will give us compatibility with the JS SDK without a huge reimplementation here

**Comment by mikehardy** [comment]
I would love your opinion @BasBouw (and also @fzuellich)  on #6689 if you get a chance. No rush - it won't be a breaking change or anything, but it reshapes the API as discussed, to hang `multiFactor()` and `getMultiFactorResolver()` off the `auth()` instance (not the static) and switches the arguments to be `multiFactor(user)` and to remove the auth instance from `getMultiFactorResolver()` (since it's off the instance now, that is implied

Both methods will now follow the same mechanical upgrade process to the v9 JS API when we adopt it

**Comment by BasBouw** [comment]
The reason I opened this issue, and the solution proposed, was to be able to use the library as described in the manual for Typescript. I understand the final solution is better, but the project I am working on, depends on Typescript, and working according to the example in documentation. 
I would really like it if that would be available, so at least I can use it for now.

Furthermore the example of a MFA like solution in 
[Phone Auth](https://rnfirebase.io/auth/phone-auth
)in reality makes your application more insecure. Instead of needing 2 keys to open a lock, you create a flow in which it looks, like you need to keys, but a hacker could enter with either a email/password key, or a phone key ..
So I would suggest to change that text at least. ( we lost a week dev time on finding out it was very unsafe )

**Comment by mikehardy** [comment]
@BasBouw you may use the result of my PR already by integrating the patch set built on every PR - https://github.com/invertase/react-native-firebase/actions/runs/3452281620 with patch-package https://github.com/ds300/patch-package

I'm pretty sure the PR will go in about like it is now, or whatever changes happen prior to release won't be too difficult to deal with...
