### ISSUE TITLE
[📚] Documentation Issue Title - Firebase ML section doesn't explain how to use it

### ISSUE THREAD

**Issue by R4Y-repo** [invertase/react-native-firebase#6740]
## Documentation Feedback

Hello everyone!
So I wanted to use Machine learning features in react native firebase but when I checked [the docs](https://rnfirebase.io/ml/usage) there's no description on how to use it or anything. 
How can i use it? and if it's unusable, is it deprecated or will it be updated?

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by wandersonsousa** [comment]
same here, so firebase ml is deprecated?

**Comment by mikehardy** [comment]
firebase.ml has had all of it's previous APIs removed upstream except some very basic ones around downloading ML models.

Everything else moved to Google's MLKit, which (as far as I know?) does not have a react-native module implementation yet - but the last time I checked was maybe a year ago so perhaps someone has made one in the time since

We do not currently have implementations in react-native-firebase of the firebase-android-sdk / firebase-ios-sdk ML model downloading APIs but would welcome any PR that implemented them
