### ISSUE TITLE
Mobile: Getting permission error on android and duplicate data return

### ISSUE THREAD

**Issue by codal-mpawar** [invertase/react-native-firebase#6808]
@Salakar @felixclack @andymatuschak @gilbertl @urajat @jeanregisser 
We are stuck here, please answer me ASAP. and we do not have much time for release.

Facing two issues now.

1. I set/add new data for the first time it's working fine. and when I set/add new data again then it's not working.
The issue on android [Error: [database/permission-denied] Client doesn't have permission to access the desired data.] 

const newPostRef = db
                .ref(`${FIREBASE_BASE_KEY + FirebaseKeys.GET_COMMENTS}${postId}`)
                .push();
            newPostRef
                .set({
                    commentId: newPostRef.key,
                    content: text,
                    postDbId: myDbId,
                    subId: userSub,
                    createdAt: new Date().getTime(),
                    postId: postId,
                    userId: userSub,
                    mentions: uniqueList || []
                }).then().catch()
                
                
3. We have a live stream page and we get comments from firebase once the user enters the screen then we start the interval every 2.5 sec for getting comment data. and after the interval, once we get data and we get any data then we update the timestamp by the last comment - 1 of createdAt, and after that, we increase by 1. but we are not getting proper data  like we get duplicate values which are already returned.

 loadLiveComments = async () => {
        const commentRef = db.ref(
            `${FIREBASE_BASE_KEY + FirebaseKeys.GET_LIVE_STREAMS_COMMENTS}live-stream-${
                this.props.postId
            }`
        );
        const comments = await commentRef
            .orderByChild('createdAt')
            .startAt(this.recentCommentTimestamp)
            .limitToLast(12)
            .once('value')
            .then((s) => s.val());
        const formattedComments = await Promise.all(Object.values(comments || {}));

        this.recentCommentTimestamp =
            formattedComments.length > 0
                ? formattedComments[formattedComments.length - 1]?.createdAt + 1
                : new Date().getTime() - 2 * 1000;

        return formattedComments;
    };

---

#### `package.json`:

```json
"@react-native-firebase/app": "^16.5.0",
"@react-native-firebase/auth": "^16.5.0",
"@react-native-firebase/crashlytics": "^16.5.0",
"@react-native-firebase/database": "^16.5.0",
"@react-native-firebase/messaging": "^16.5.0",
```

I already check with add firebase.json file but no luck

{
  "react-native": {
    "database_persistence_enabled": true
  }
}

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

android.useAndroidX=true
android.enableJetifier=true
jetifier "^1.6.2"

- **Platform that you're experiencing the issue on**:
  - [ x] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
"@react-native-firebase/app": "^16.5.0",
"@react-native-firebase/auth": "^16.5.0",
"@react-native-firebase/crashlytics": "^16.5.0",
"@react-native-firebase/database": "^16.5.0",
"@react-native-firebase/messaging": "^16.5.0",
</p>
</details>

"react-native": "0.64.2",
"react": "16.13.1",

**Comment by codal-mpawar** [comment]
I am also available for call if you need more information

**Comment by mikehardy** [comment]
@codal-mpawar 

> We are stuck here, please answer me ASAP. and we do not have much time for release.

1- This is open source, it sounds like you need to have a support contract with someone if you need help ASAP from unknown people on the internet 🤔 - that's not the way open source works (https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b) - you'll need to note this is a major holiday for most of the world and I'm only checking messages by chance, with no intention of working much today or for the next few days. Even then, it is "best effort" support here where you are expected to do 99% of the effort to resolve issues and report findings (https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example) and I will provide guidance with time available on how to prove there is a module issue or not. If there is a module issue I'll fix it but if it is a project issue, you will discover it and fix it

2- Your error message looks like your database permission rules in the firebase console aren't working the way you want them to. You may examine this hypothesis by setting them to a simple "allow all" type rule **temporarily since it is a massive security hole** just to see if the operation then succeeds. That would prove the database permission rules were the thing blocking you.

3- If you have code etc to paste in github you can format it nicely by putting it in triple backticks with a language specifier like

```javascript
loadLiveComments = async () => {
const commentRef = db.ref(
${FIREBASE_BASE_KEY + FirebaseKeys.GET_LIVE_STREAMS_COMMENTS}live-stream-${ this.props.postId }
);
const comments = await commentRef
.orderByChild('createdAt')
.startAt(this.recentCommentTimestamp)
.limitToLast(12)
.once('value')
.then((s) => s.val());
const formattedComments = await Promise.all(Object.values(comments || {}));

    this.recentCommentTimestamp =
        formattedComments.length > 0
            ? formattedComments[formattedComments.length - 1]?.createdAt + 1
            : new Date().getTime() - 2 * 1000;

    return formattedComments;
};
```

4- react-native 0.64 is out of support and you will have problems with it. You should upgrade immediately to a supported version https://github.com/reactwg/react-native-releases#releases-support-policy

**Comment by codal-mpawar** [comment]
Thanks, @mikehardy got the issue and fix that. Thanks again.
