### ISSUE TITLE
Uninstalling the app doesn't clear data cached by Firebase

### ISSUE THREAD

**Issue by amsul** [invertase/react-native-firebase#694]
### Issue

Uninstalling the app doesn't clear data that Firebase caches - such as the logged in user.

As a result, what ends up happening is when a user removes the app and adds it again, they're already logged in. Not only is this a privacy concern, but it also causes issues such as not having an authorized Facebook session (if that was the authentication method) and so all requests to the Facebook API fail.

Is this intended behavior? If so, is there a way to opt out?

### Environment

1. Application Target Platform: 
iOS

4. React Native version: 
0.50.3

5. RNFirebase Version: 
3.1.0

**Comment by Ehesp** [comment]
I believe this is intended as it's storing the data on key chain. There's
an issue been raised elsewhere which I'll look for once I'm not on the
phone.

**Comment by ergunyasar** [comment]
@amsul I faced same problem and spent a lot of time regarding to that issue. I solve it like this. For ios I set a user default variable(boolean) then change its value after first run. If it is first run I simply sign out the user.
`
[FIRApp configure];
  
  NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
  if (![defaults boolForKey:@"notFirstRun"]) {
    [defaults setBool:YES forKey:@"notFirstRun"];
    [defaults synchronize];
    [[FIRAuth auth] signOut:NULL];
  }
` 
Hope this helps.

**Comment by amsul** [comment]
@ergunyasar thanks! I'll def give that a shot

**Comment by Ehesp** [comment]
Going to close this one as it's something we can't fix.

**Comment by ollieh-m** [comment]
Thanks for your solution @ergunyasar - just wondering if you know whether this is an issue on android as well. And whether it's an issue with firebase database cache. I don't think that's on the keychain so assume it is deleted with app data but I'm not totally sure.

**Comment by cassaram09** [comment]
@ollieh-m I had a similar issue on Android, where the auth state still persisted even after uninstalling the app. I implemented a solution similar to what @ergunyasar suggested, except in React Native, but that didn't work for me. However, disabling backups in `AndroidManifest.xml` seemed to do the trick.

```
// Condensed for clarity.

<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="YOUR.APP.NAME."
    android:versionCode="1"
    android:versionName="0.0.0"
    xmlns:tools="http://schemas.android.com/tools" // added this
    >

    <application
      tools:replace="android:allowBackup" // I added this to override another dependency - you may or may not need this
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@drawable/icon"
      android:theme="@style/AppTheme"
      android:allowBackup="false"  // add to disable backups
    >

**Comment by akiwarheit** [comment]
I had this issue on Android as well - uninstalling the app, then reinstalling showing the old config from Remote Config.

I assumed this was because the old instance was rate limited. Signing out of Google Drive fixed it (so it was definitely a backup issue)

Unfortunately this was a release build so I was unable to debug.

I had to add

```
tools:replace="android:allowBackup"
allowBackup=false`.
```

**Comment by mikehardy** [comment]
Just a note from an Android dev - android works very hard (if the user has configured it with their google account) to back up app data state so if they install the app on another device, or restore their device, all their settings and config are restored seamlessly. This helps with user device upgrades for instance. That's what "allowBackup" is doing - it is saying "this app's data is allowed to be included in google account app user data backups so restores work". You might consider leaving it on because it is a nice feature for users if they have taken time to configure your app, but to gate logins like above on first-run-after-install is a good thing in case of privacy concerns. Just disallowing backup entirely is user-unfriendly though obviously justifiable in certain situations.

**Comment by saumaypaul20** [comment]
> @amsul I faced same problem and spent a lot of time regarding to that issue. I solved it like this. For ios I set a user default variable(boolean) then change its value after first run. If it is first run I simply sign out the user.
> 
> ```
> [FIRApp configure];
>   
>   NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
>   if (![defaults boolForKey:@"notFirstRun"]) {
>     [defaults setBool:YES forKey:@"notFirstRun"];
>     [defaults synchronize];
>     [[FIRAuth auth] signOut:NULL];
>   }
> ```
> 
> Hope this helps.

this also signs out the user if he updates the app. How to prevent that?

**Comment by anhtuank7c** [comment]
For anyone who still looking for this issue for expo project, I have a patch package for you:

1. Create a file `patchs/@react-native-firebase+app+19.0.1.patch` with content below (I'm use rnfirebase version 19.0.1:

```
diff --git a/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js b/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js
index 8cf92f0..7840ebb 100644
--- a/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js
+++ b/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js
@@ -7,7 +7,13 @@ exports.withFirebaseAppDelegate = exports.modifyAppDelegateAsync = exports.modif
 const config_plugins_1 = require("@expo/config-plugins");
 const generateCode_1 = require("@expo/config-plugins/build/utils/generateCode");
 const fs_1 = __importDefault(require("fs"));
-const methodInvocationBlock = `[FIRApp configure];`;
+const methodInvocationBlock = `[FIRApp configure];
+NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
+if (![defaults boolForKey:@"notFirstRun"]) {
+  [defaults setBool:YES forKey:@"notFirstRun"];
+  [defaults synchronize];
+  [[FIRAuth auth] signOut:NULL];
+}`;
 // https://regex101.com/r/mPgaq6/1
 const methodInvocationLineMatcher = /(?:self\.moduleName\s*=\s*@\"([^"]*)\";)|(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[(\[RCTBridge alloc\]|self\.reactDelegate))/g;
 // https://regex101.com/r/nHrTa9/1/
diff --git a/node_modules/@react-native-firebase/app/plugin/src/ios/appDelegate.ts b/node_modules/@react-native-firebase/app/plugin/src/ios/appDelegate.ts
index b4ecbdf..42bdcd5 100644
--- a/node_modules/@react-native-firebase/app/plugin/src/ios/appDelegate.ts
+++ b/node_modules/@react-native-firebase/app/plugin/src/ios/appDelegate.ts
@@ -3,7 +3,13 @@ import { AppDelegateProjectFile } from '@expo/config-plugins/build/ios/Paths';
 import { mergeContents } from '@expo/config-plugins/build/utils/generateCode';
 import fs from 'fs';
 
-const methodInvocationBlock = `[FIRApp configure];`;
+const methodInvocationBlock = `[FIRApp configure];
+NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
+if (![defaults boolForKey:@"notFirstRun"]) {
+  [defaults setBool:YES forKey:@"notFirstRun"];
+  [defaults synchronize];
+  [[FIRAuth auth] signOut:NULL];
+}`;
 // https://regex101.com/r/mPgaq6/1
 const methodInvocationLineMatcher =
   /(?:self\.moduleName\s*=\s*@\"([^"]*)\";)|(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[(\[RCTBridge alloc\]|self\.reactDelegate))/g;

```

2. install patch package: `npm install -D patch-package`
3. add postinstall to your package.json: `"postinstall": "patch-package",`

**Comment by ihor-sviziev** [comment]
@Ehesp, having in mind that there are patches available in the comments, especially for this library, maybe we can make a feature flag for disabling this behavior (can be turned off by default for backward compatibility)?

As an app developer, it feels like more bugs than features when you're reinstalling the app, and it's logging you out. End users also may think that the app isn't secure because of that behavior.

**Comment by mikehardy** [comment]
This is a closed issue and won't receive attention, in general feature flags suffer from discoverability issues but if there were a PR to add a utility method to the app package that could be queried to determine if it was "first run after install" + some documentation indicating in (for example) auth/login area that this could be checked to determine if the user had a login but only because of stored keychain behavior, that could have potential
