### ISSUE TITLE
ERROR Invariant Violation: `new NativeEventEmitter()` when trying to use firebase with react-native

### ISSUE THREAD

**Issue by rotosiruto** [invertase/react-native-firebase#7214]
I wrote the details here
https://stackoverflow.com/questions/76578041/error-invariant-violation-new-nativeeventemitter-when-trying-to-use-firebas

**Comment by HwanHeo** [comment]
did you fix it?

**Comment by rotosiruto** [comment]
@HwanHeo 
@Skipperlla 
I ran the following command once, but I didn't see any improvement or change.

```
watchman watch-del-all && lsof -n -P -i :8081 -t | xargs kill && rm -rf ios/build && rm -rf android/app/build && rm -rf node_modules && yarn install && rm -rf ~/Library/Caches/CocoaPods && rm -rf Pods && rm -rf ~/Library/Developer/Xcode/DerivedData && cd ios && pod deintegrate && pod setup && bundle exec pod install && cd .. && ./node_modules/react-native/scripts/packager.sh --reset-cache
```

**Comment by mikehardy** [comment]
Just as a note, this issue didn't rise to the level of attention in general because no reproduction was provided

On the contrary, I provide a reproduction that does a fully-automated new project init + firebase integration + build test that shows it works. Meaning there is reproduced success and the burden of proof on any build error is strongly on the side of a reproduction being necessary to show build failures - https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
