### ISSUE TITLE
[🐛] IOS - 'Firebase.h' file not found Migrate from v5 to v6

### ISSUE THREAD

**Issue by tcyzz94** [invertase/react-native-firebase#7332]
HI invertase,
https://rnfirebase.io/migrating-to-v6
Please help
i had followed the migration guide above, removed nodemodules, pod update, pod install.. still same result

Error during build : 'Firebase.h' file not found in AppDelegate

Packages
 "react": "16.9.0",
 "react-native": "0.61.2",
"@react-native-firebase/analytics": "^18.3.2",
    "@react-native-firebase/app": "^18.3.2",
    "@react-native-firebase/crashlytics": "^18.3.2",
    "@react-native-firebase/messaging": "^18.3.2",
Thanks

**Comment by mikehardy** [comment]
> "react-native": "0.61.2",

This version of react-native is too old to support, but the likely root cause here is probably failure to do `use_frameworks` correctly or something else

Here's a script that shows how to integrate current versions of react-native-firebase with current versions of react-native step by step (read the script, read the comments) to achieve a successful integration in current styles https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
