### ISSUE TITLE
[🔥🐛]  Xcode 15 "An attribute list cannot appear here" (iOS)

### ISSUE THREAD

**Issue by abdi4** [invertase/react-native-firebase#7366]
## Issue

I updated Xcode to v15 and got this error in a Firestore settings file:  "An attribute list cannot appear here"

Describe your issue here

- Can run on xcode 14 with no issues

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

iOS
<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - v14.11.1
- **`Firebase` module(s) you're using that has the issue:**
  - Firestore
- **Are you using `TypeScript`?**
  - Y & v4.8.5

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
It would help to include any information at all to troubleshoot this. I am running Xcode 15 in all my local dev environments without problem on my demonstration build script (https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh), and am already testing it in CI, it builds fine there

Closing this as non-reproducible as no information to reproduce supplied / local attempts work

**Comment by Meegan** [comment]
Could it be related to this? 
https://developer.apple.com/forums/thread/735747

**Comment by abdi4** [comment]
Yeah I think it's the same issue @Meegan, opened the issue here because i couldn't find a solution in that thread.

@mikehardy I've now added the missing info. Can you please reopen this issue as multiple people are experiencing it?

**Comment by abdi4** [comment]
This issue was also raised [here](https://github.com/firebase/firebase-ios-sdk/issues/11840). Would be good to know if there was a solution (other than upgrading to the latest version) for those of us who can't upgrade atm.

**Comment by mikehardy** [comment]
I'm not sure there will be a valid workaround here, Xcode 15 did a number of things (like, "hey, let's implement a completely new linker! with breaking changes!") that simply *will* require new versions of software in order to work correctly.

Stated differently: if you want your software to work on Xcode 15 you need to be prepared to upgrade.

I see this in the updated details (thank you!):

```json

    "@react-native-firebase/analytics": "^14.11.1",
    "@react-native-firebase/app": "^14.11.1",
    "@react-native-firebase/firestore": "^14.12.0",
    "@react-native-firebase/installations": "^14.11.1",
    "@react-native-firebase/messaging": "^14.11.1",
    "@react-native-firebase/remote-config": "^14.11.1",
    "@react-native-firebase/storage": "^14.11.1",
```

That's old software. And it contains code that will not work with Xcode 15.

Currently there are no reproducers running on current software so this will not be reopened as - based on what I see with my test script and current versions - there is nothing left to fix, and there will be no actual change in this repository in order for things to work.

I appreciate that upgrading software is the equivalent of "sideways" (that is: not forward...) motion / activity from the perspective of getting features your clients care about shipped, however Apple forces this on us basically once a year, and so does Google with Android updates. Mobile development is a sea of churn and updating has to have regular time + budget allocated for it
