### ISSUE TITLE
[🐛] FCM message handler methods are firing when notifications are turned OFF for the app in device settings (both iOS and Android).

### ISSUE THREAD

**Issue by jp-23** [invertase/react-native-firebase#7528]
## Issue

FCM message handler methods are firing when notifications are turned OFF for the app in device settings (both iOS and Android).

My expectation is that the below methods will NOT fire when notifications are turned OFF for the device:
- getInitialNotification
- onMessage - **_the remoteMessage parameter is populated as well_**

However, they are firing.

When I say `turned OFF for the device` - I'm referring to going into the device's Settings app, going to the Notifications page for the app, and toggling OFF notifications.  e.g. on iOS the toggle is called `Allow Notifications`.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `16.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/messaging`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
1) There are device-local user-visible "notifications"

And there is 

2) firebase messaging ('FCM') which is little bits of JSON going from the server to the device

FCM - item 2 - *may or may not* trigger item 1 and create a user visible device local notification. Or it may not, depends on the FCM contents

There is no reason that FCM - item 2 - will be denied just because the user has toggled off device-local user-visible notifications (item 1)

So this is working as expected I believe. FCM is working. Handlers will invoke. But the user may or may not see anything depending on whether they have granted device-local user-visible notification permission

**Comment by jp-23** [comment]
Thank you for the explanation @mikehardy .  End-users don't realize there are these 2 "types" of notifications though.  So when toggling off the `Allow Notifications` in iOS, I feel like the user expects zero notifications at that point.  Unless I'm mistaken, this is the user experience in a lot of apps.  Is there a way to replicate that with FCM - i.e. completely shut-off the firing of those handlers?  Or would we just have to ignore the messages when they come in if `Allow Notifications` is turned off?

**Comment by mikehardy** [comment]
The systems are separate from a firebase perspective.

If you want to bind them, use react-native-permissions (or Notifee) so you can understand the user permission status, and if they turn off notifications, purge their FCM token from your cloud systems so you no longer send messages I think (or so if messages are sent you don't react to them)

There are various ways to put these building blocks / components together but it's going to be project-specific. There can't be a tighter coupling between FCM and device-local/user-visible notification status or valid use cases that rely on FCM with no expectation of user-visible messages will be broken.

**Comment by jp-23** [comment]
@mikehardy is there any reason to use `react-native-permissions` instead of the `hasPermission` & `requestPermission` methods in FCM?  Or is it more preference / project-specific?

**Comment by mikehardy** [comment]
Good question - I have always used react-native-permissions because I *personally* have a lot of permissions to manage and I like one API / module to do so in a normalized fashion. So I think it's a matter of taste

That said, I'm not sure that react-native-firebase permission checking is fully up to date with the latest notification permissions in android and iOS, that device-local notification API surface area moves quickly (which is why it all got moved out to the notifee.app package in the first place)

All I can say for certain is that react-native-permissions works well for me

**Comment by rjuevesano** [comment]
I used notifee and I allowed push notifications. My question is, is there a way to turn-off push notifications (even if I allowed it) if the app is active/open? I want to show in-app notification and disable push notifications if the app is active/open and vice versa.

Thanks!
