### ISSUE TITLE
Deprecation: Calling 'initializeApp()' for apps that are already initialised natively is unnecessary, use 'firebase.app()' instead to access the already initialized default app instance.

### ISSUE THREAD

**Issue by ryota-murakami** [invertase/react-native-firebase#755]
### Issue
I'm facing `Deprecation: Calling 'initializeApp()' for apps that are already initialised natively is unnecessary, use 'firebase.app()' instead to access the already initialized default app instance.` warning.

![screen shot 2018-01-16 at 14 15 34](https://user-images.githubusercontent.com/5501268/34972886-dd9d0dee-fac7-11e7-9baa-a4ed0f53ed44.png)

that looks like following message into the repository.
https://github.com/invertase/react-native-firebase/blob/80cb54ee6d79e36b783de54b626ffd50fad6a971/lib/utils/internals.js#L68-L70

If i can fix it, how to add or edit any configuration?

thank you so much:bow:

### Environment

1. Application Target Platform: Both

2. Development Operating System: macOS Sierra

3. Build Tools: Xcode

4. React Native version: 0.52.0

5. RNFirebase Version: 3.2.2

**Comment by IljaDaderko** [comment]
Your firebase config is handled by files you download from them and place into your native projects i.e. Google-info.plist and google-services.json (I think they are called this way). react-native-firebase initialises an instant based on these in native during app bootstrap, so you don't have to do it. If you want to edit the configs you can do so easily in xCode / Android studio or even editor like code, by editing those files or you can use firebase to generate new ones.

I think all you need to do in order to get rid of that error is to use 


```
import firebase from "react-native-firebase";

firebase.app().auth().signIn ....
```

I am not sure why `app()` bit is not used more extensively in the documentation however.

**Comment by chrisbianca** [comment]
@IljaDaderko explained this perfectly - since v3 it has not been necessary to initialise the default app as this is handled completely on the native side.

One thing I would point out, it isn't necessary to do `firebase.app().auth()`, you should just be able to run `firebase.auth()` which automatically returns the auth instance for the default application.

@IljaDaderko are you using Typescript? I'm assuming that the typings aren't correct - none of us core maintainers use Typescript so it often gets a bit left behind, something that we're hoping to address!

**Comment by IljaDaderko** [comment]
@chrisbianca yep, using typescript. Main reason for me using `firebase.app()` is that it has correct typings i.e. `firebase.app().auth()` passes ts, where as `firebase.auth()` doesn't

**Comment by Ehesp** [comment]
@IljaDaderko That's strange though, this line (https://github.com/invertase/react-native-firebase/blob/master/lib/index.d.ts#L30) suggests you should be able to access the `auth` by calling `auth()`

**Comment by IljaDaderko** [comment]
@Ehesp I see, it doesn't seem to work for me ts wise, here is demonstration of what I am seeing currently, hope it gives more context

![Preview](https://media.giphy.com/media/26gN0vDpPe6SbMl32/giphy.gif)

**Comment by dimlksin2** [comment]
Тоже столкнулся с данной проблемой, кто знает решение?

**Comment by udarts** [comment]
Dimlksin2, can you write in English please?

**Comment by dimlksin2** [comment]
> Димлксин2, можешь написать на английском пожалуйста?

Also faced with this problem, who knows the solution?

**Comment by tiu93** [comment]
У меня  была такая ошибка когда инициализация уже была произведена, было сделано следующее:

import firebase from 'react-native-firebase';

if (!firebase.apps.length) {
    firebase.initializeApp(config);
}
