### ISSUE TITLE
[🐛] Upgrading from native (ios/android) to react native, auth doesn't persist

### ISSUE THREAD

**Issue by senghuotlay** [invertase/react-native-firebase#7559]
I am currently working on a react-native project, which is a complete rewrite from native(ios/android). However, when I am doing an upgrade, the auth state didn't seem to persist, which requires the user to reauthenticate.

**Comment by mikehardy** [comment]
That's unexpected - not many people do this though so perhaps it is just unreported.
The underlying SDKs (firebase-android-sdk and firebase-ios-sdk) are the same though, so it should be persisted the same assuming that the bundle id / package is the same so that they maintain access to the local data storage / security keychains etc for the app

react-native-firebase does not do anything with authentication state storage, that is *all* handled by the underlying SDKs so if they were in use before they should maintain the same status

There is no reproduction attached here or information on versions so I'm not sure what else I can do other than describe the theory as up above.
