### ISSUE TITLE
Image issue in Push notification when app is in background or kill

### ISSUE THREAD

**Issue by agrawalshubham1012** [invertase/react-native-firebase#7562]
i am not able to get the image in background mode but in foreground i am able to see the image can you help me out in react native

**Comment by mikehardy** [comment]
Hi there, sorry, I can't help without more information. https://stackoverflow.com/help/how-to-ask

What image? What JSON are you sending via the FCM REST API so we can reproducibly test it?
What platform?
What versions?

Additionally, it may be that in background mode what you hope for is something that is not possible, and you may need notifee.app in order to style background notifications.
