### ISSUE TITLE
IOS Build Issue in Azure Pipeline after updating macos Version to 13 and xcode Version to 15.

### ISSUE THREAD

**Issue by Mohanraj-Rangasamy** [invertase/react-native-firebase#7647]
After updating **macos version to 13** and **xcode version to 15** in my laptop(m1-chip), Without any issues, I am able to run simulator, ios real device in debug mode. I am able to generate manual release build using Xcode. But when I push code changes to Azure Devops after updating **macos version to 13** and **xcode version to 15** in pipeline, Xcode build is failing with some Run script build phase error. I hope the error is belongs to React-Native-Firebase. Please refer the below points for warnings and errors. And help me to fix the issues. 

Please file a bug at https://feedbackassistant.apple.com/ with this warning message and any useful information you can provide.
    **Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'myProject' from project 'myProject')**
    **Run script build phase '[CP-User] [RNFB] Crashlytics Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'myProject' from project 'myProject')**
    **Run script build phase '[CP-User] Config codegen' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'react-native-config' from project 'Pods')**
** BUILD FAILED **

**##[error]Error: /usr/bin/xcodebuild failed with return code: 65**

**Comment by mikehardy** [comment]
Hi there! You have ignored our issue template and the information provided does not indicate react-native-firebase is the root cause at all, so I will close this

I have a script that reliably builds react-native-firebase into a project created from scratch in order to test things and it works fine on macos-13 and Xcode 15 https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

My guess with error code 65 is that some shell script failed, perhaps you are missing a build utility in your new pipeline versions or are running outdated versions of react-native-firebase or react-native so you don't have the necessary fixes to run on modern macOS with modern Xcode

**Comment by ngorgiev** [comment]
Now sure why this issue is close, I am just facing the same one. My app is built with Expo and I am building it on Azure, after prebuilding the app. No matter what you try, the task xCode@5 fails, 60 seconds after it starts with error code:65. I have managed to build the app without the Xcode task, but now when check my IPA it says my app is not signed, and I don't receive push notification on my devices:

`
codesign -d --entitlements :- myApp.ipa
myApp.ipa.ipa: code object is not signed at all
`

I have written an article on medium on how I was able to build the app, I guess you can check it [here](https://medium.com/@nikolagorgievmkd/azure-pipelines-hates-when-expo-dates-firebase-3845f07b3a85).

**Comment by mikehardy** [comment]
@ngorgiev the issue is closed for all the reasons I stated. No template. No indication it's react-native-firebase that's the problem. Error 65 is almost always "your build process didn't find the node binary" although per your article it may also mean "you haven't configured Xcode correctly". You might like fastlane, it's built for this purpose - takes a little while to set up (mostly because the Apple tools are terrible and fastlane just has to deal with that) but afterwards, bliss. https://fastlane.tools/

**Comment by ngorgiev** [comment]
> @ngorgiev the issue is closed for all the reasons I stated. No template. No indication it's react-native-firebase that's the problem. Error 65 is almost always "your build process didn't find the node binary" although per your article it may also mean "you haven't configured Xcode correctly". You might like fastlane, it's built for this purpose - takes a little while to set up (mostly because the Apple tools are terrible and fastlane just has to deal with that) but afterwards, bliss. https://fastlane.tools/

I think there is some issue either with the firebase npm packages or its something on azure side.
In the past few days, I have tried to replicate the Azure build machine on my local one, literally install the same versions of everything, from macOs, Xcode, Node, cocoapods, ruby etc, then remove everything from keychain on my side and just install the p12 I am providing to azure. So the outcome is, locally everything is working fine, no matter if I build the app with Xcode, or use the same scripts I am using in the pipelines explained in the article above, so as soon as you try to sign the app either on xcode@5 task or in the script to pass CODE_SIGNING_ALLOWED=YES to the command, locally it works absolutely fine, while on Azure it gives error 65. 
To try it out, just install the react-native-firebase/app and react-native-firebase/messaging and don't do anything else in the project, before that the pipeline works, as soon as you install the packages the pipeline will fail with error code 65.

One last thing, I have downloaded the entire repo from azure after the build failed, made the needed changes in the paths so I can build the project locally, and magically it works, on azure it does not, so the point is, Azure has issues signing my app when I add your packages.

Ps. we are talking about Expo, so I don't control iOS/android projects directly, I am assuming there is no issue when using react native without expo, but since expo is now recommended by meta, I bet this is something that you need to take care of, because there are some clients that won't like using expo services :)

**Comment by rparmarev** [comment]
I am facing same issue in azure pipeline. it starts only after i use firebase (analytics and crashlytics).
Getting this error:
**Error: /usr/bin/xcodebuild failed with return code: 65**

although when i set [CODE_SIGNING_ALLOWED] = 'no'. it doesn't work but that will not work in prod as code signing is not there.

**Comment by rparmarev** [comment]
@ngorgiev are you still facing the same ? or any possible workarounds?

**Comment by ngorgiev** [comment]
> @ngorgiev are you still facing the same ? or any possible workarounds?

yes, there is no solution, so you canot build it on azure with Firebase Push Notifications working, only with local build you are going to be able to test the PN.

**Comment by rparmarev** [comment]
I am only using Analytics and Crashlytics, but I think code signing is also required for them to work.

**Comment by mikehardy** [comment]
> I don't use Expo and I don't use Azure so I won't be able to help here.

Sorry, no, my previous comment still applies

**Comment by Mohanraj-Rangasamy** [comment]
Hi All,

Xcode 15 no longer supports iPhone 8 in the Xcode build path.
(For example, in the Xcode build command:
/usr/bin/xcodebuild -sdk, name=iPhone 16 build CODE_SIGN_STYLE=Manual)

I changed name=iPhone 8 to name=iPhone 16, and the issue was resolved — the build succeeded.

Thank you.

**Comment by joran-allego** [comment]
For those finding this later: for us, the suggestion in the previous comment wasn't working. Here the issue was that Firebase added code signing capabilities to the pods, which they couldn't use. So I solved it with disabling code signings for pods again:
```
installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
    config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
    config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
  end
end
```
Of course, as always with the elusive 'error 65', for others it might be hiding a different issue. But if you come here looking for a solution it's worth try. If this didn't work for you.. good luck.
