### ISSUE TITLE
Remove Crashlytics or set this module optional

### ISSUE THREAD

**Issue by 6pm** [invertase/react-native-firebase#772]
After update from 3.1.0 to 3.2.2 I facing with build error - `This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
                                                    install an Android build tool and ask a team member to invite you to this app's organization.`

I don't want use this analytics service because I prefer sentry.
Please remove it or set optionally

Thank you

**Comment by Salakar** [comment]
@6pm can we see your build gradle? If you added the `transitive = false` as per docs you shouldn't be having Crashlytics included as part of your build.

![image](https://user-images.githubusercontent.com/5347038/35243487-f884c092-ffb4-11e7-926d-719244788424.png)

**Comment by chrisbianca** [comment]
Closing due to lack of response. Please re-open with the information requested if it's still an issue.

**Comment by brunolemos** [comment]
Adding `transitive` code fixed for me!

---

This could be more clear in the docs. We use `react-native link` so we expect this part to be correct already. The docs even says `This should be here already` instead of `Add the transitive line below` so our eyes end up skipping this part :)

<img width="860" alt="image" src="https://user-images.githubusercontent.com/619186/37618047-991ff1e8-2b93-11e8-8c93-da830384b7fa.png">

**Comment by rambabusaravanan** [comment]
Thanks @brunolemos 

Seriously our eyes skip this one in docs. Changed and working well.

------------------------
The file "build.gradle" will have 
```
compile project(':react-native-firebase')
```
Which needs to be changed to
```
compile(project(':react-native-firebase')) {
    transitive = false
}
```

**Comment by chrisbianca** [comment]
If you run `react-native link react-native-firebase` then this should be taken care of for you automaticallly?

**Comment by brunolemos** [comment]
@chrisbianca IIRC I did use link and it did not add the transitive part
