### ISSUE TITLE
Unable to resolve "../../../../.." (likely related to expo-router + babel-plugin-module-resolver babel.config setting)

### ISSUE THREAD

**Issue by steveacalabro-indevets** [invertase/react-native-firebase#7728]
Hi! 👋 

I am creating a expo react native application using expo-router. Expo router has us using the metro bundler. When I simply add `@react-native-firebase/analytics` to the application I get the following error

```
Unable to resolve "../../../../.." from "node_modules/@react-native-firebase/analytics/lib/modular/index.js"
[DevIndeVets] Metro has encountered an error: While trying to resolve module `../../../../..` from file
`/Users/{my-user}/{my-git-folder-directory}/{my-project-name}/node_modules/@react-native-firebase/analytics/lib/modular/index.js`, the package
`/Users/{my-user}/{my-git-folder-directory}/{my-project-name}/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved
(`/Users/{my-user}/{my-git-folder-directory}/{my-project-name}/expo-router/entry`. Indeed, none of these files exist:

*
/Users/{my-user}/{my-git-folder-directory}/{my-project-name}/expo-router/entry(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css|.ios.css|.native.css|.css|.ios.mjs|.native.mjs|.mjs)
* /Users/{my-user}/{my-git-folder-directory}/{my-project-name}/expo-router/entry/index(.native|.ios.ts|.nat<…>
› Stopped server
✨  Done in 68.49s.
```

I investigated the files used in the `node_modules` directory and was able to use [patch-package](https://github.com/ds300/patch-package) to patch `@react-native-firebase/analytics@19.1.1`

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@react-native-firebase/analytics/lib/modular/index.js b/node_modules/@react-native-firebase/analytics/lib/modular/index.js
index 1b96573..bcb0f3f 100644
--- a/node_modules/@react-native-firebase/analytics/lib/modular/index.js
+++ b/node_modules/@react-native-firebase/analytics/lib/modular/index.js
@@ -1,4 +1,4 @@
-import { firebase } from '..';
+import { firebase } from '@react-native-firebase/app';
 
 /**
  * @typedef {import("..").FirebaseApp} FirebaseApp
@@ -648,15 +648,15 @@ export function isSupported() {
 }
 
 /**
- * Sets the applicable end user consent state for this app.
- * references once Firebase Analytics is initialized.
+ * Sets the applicable end user consent state for this web app across all gtag
+ * references once Firebase Analytics is initialized. Web only.
  * @param analytics Analytics instance.
  * @param consentSettings See {@link analytics.ConsentSettings}.
- * @returns {Promise<void>}
+ * @returns {void}
  */
 // eslint-disable-next-line
-export function setConsent(analytics, consentSettings) {
-  return analytics.setConsent(consentSettings);
+export function setConsent(consentSettings) {
+  // Returns nothing until Web implemented.
 }
 
 /**
```

As you can see changing 
```
import { firebase } from '..';
```

To 
```
import { firebase } from '@react-native-firebase/app';
```

will let it actually resolve. I'm worried I didn't configure thing correctly. Could this be an actual issue or just me?

**Comment by bjornevik** [comment]
Hi,

I was having a similar problem when migrating from `react-navigation` to `expo-router`.

This was caused by a fault in my `babel.config.js` I had defined the root as `"./src"` where my `src/screens` is but since expo router uses `app/` from root level as it's entry point it wasn't able to find the entry point.

After changing `babel.config.js` I deleted patches, removed and reinstalled `node_modules`, and ran `yarn start --clear` to clear the bundler. It seems to have resolved the issue for me.

Why this happens when using `@react-native-firebase/analytics` I'm more unsure of.

```diff
diff --git a/babel.config.js b/babel.config.js
index f8b0d586..e07b7372 100644
--- a/babel.config.js
+++ b/babel.config.js
@@ -6,7 +6,7 @@ module.exports = function (api) {
       [
         'module-resolver',
         {
-          root: ['./src'],
+          root: ['./'],
           extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
           alias: {
             '@src': './src',
```

**Comment by tandler5** [comment]
same issue

**Comment by msasinowski** [comment]
same issue

**Comment by npv2k1** [comment]
same issue when i use package `@react-native-firebase/messaging` version `19.0.1`

**Comment by jervis446** [comment]
same issue

**Comment by thoth-seshat** [comment]
Having the same issue too

**Comment by jonjts** [comment]
Same issue too

**Comment by elyobo** [comment]
still requires attention

**Comment by mikehardy** [comment]
- still requires attention because you receive the same error from the same package?
- does the patch work?
- the second comment mentions a misconfiguration that - when fixed and everything cleaned out / rebuilt - fixes things, does that work?

I don't think there is enough information here, nor is there a reproduction so it's hard to know what to do with this

**Comment by mikehardy** [comment]
The call chain here is interesting.

`firebase` from `..` is the constant `firebase` exported via `getFirebaseRoot`, which will be the object created here: https://github.com/invertase/react-native-firebase/blob/3780d671b65333cebee0887f7cd30faa0055945b/packages/app/lib/internal/registry/namespace.js#L244-L267

So it should be a valid firebase object, however the resolution of that is failing, perhaps the sub-error messages shed some light:

```
However, this package itself specifies a `main` module field that could not be resolved
(`/Users/{my-user}/{my-git-folder-directory}/{my-project-name}/expo-router/entry`. Indeed, none of these files exist:

*
/Users/{my-user}/{my-git-folder-directory}/{my-project-name}/expo-router/entry(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css|.ios.css|.native.css|.css|.ios.mjs|.native.mjs|.mjs)
* /Users/{my-user}/{my-git-folder-directory}/{my-project-name}/expo-router/entry/index(.native|.ios.ts|.nat<…>
* ```

What's going on with looking for expo-router/entry from a main field in package.json ?

This makes little sense

**Comment by elyobo** [comment]
Attempting to create a minimal reproduction via `npx create-expo-app@latest` and then going through the standard install steps for `@react-native-firebase/app` and `@react-native-firebase/analytics` and I don't run into the same issue when running on ios. So it evidently does work in some cases.

The steps I've gone through are the same in each case so perhaps it's some sort of version incompatibilities or somehow due to other plugins or packages installed... I'll keep poking and update here if I find anything.

**Comment by elyobo** [comment]
Looking at the differences between the create expo app and our own, it seems that it's the babel `module-resolver` problem causing the problem. I can reproduce the `Unable to resolve "../../../../../.." from "node_modules/@react-native-firebase/analytics/lib/modular/index.js"` issue (although slightly less verbose for some reason) after making the following change to the `babel.config.js`.

<img width="418" alt="image" src="https://github.com/user-attachments/assets/f2b96373-4fad-4241-b46c-c8e7b227295f">

This makes sense; the `..` import in `node_modules/@react-native-firebase/analytics/lib/modular/index.js` is now being resolved relative to `./` (the location of `babel.config.js`), which ends up being `../../../../../..` (one directory up from `babel.config.js` relative to `node_modules/@react-native-firebase/analytics/lib/modular/index.js`). It also explains why putting in the explicit import to `@react-native-firebase/app` avoids the issue.

I didn't think that `babel` normally operated on `nodule_modules` but evidently in the expo / metro bundler / expo router world it is, even in the minimal example.

In our case I don't _think_ we need the `root` option at all (I didn't originally set this up), it's just for the `alias` and so removing it resolves the issue in my case. If you _did_ need the `root` with expo then I don't know what the workaround is.

Regardless, this doesn't look like a `react-native-firebase` issue so I think you can close again.

**Comment by mikehardy** [comment]
perhaps there is a way to blocklist something in particular or by regexp ? to surgically avoid it doing that inside node_modules/react-native-firebase ?

**Comment by mikehardy** [comment]
Before closing this could perhaps go in the tips-n-tricks page 🤔

**Comment by elyobo** [comment]
Possibly worth mentioning as a gotcha somewhere (although presumably people will also eventually find this issue, as I did 😓). `expo` + `babel-plugin-module-resolver` w/`root` option is incompatible.

I couldn't find a way to avoid it in the `module-resolver` plugin; I did see comments noting that generally babel isn't run on `node_modules`, which is my experience, but evidently expo or metro bundler are doing so so maybe the issue is with one of those.

It's working for me now though, because we really don't need the `root` option, we just use the `alias` and someone through the `root` option in there when they set it up.

**Comment by elyobo** [comment]
@steveacalabro-indevets @tandler5 @msasinowski @npv2k1 @jervis446 @thoth-seshat @jonjts are you all also using the same sort of setup - `expo` + `babel-plugin-module-resolver` with the `root` option?

**Comment by mikehardy** [comment]
I don't think this is a neat fit in the tips and tricks section vs just leaving it well documented here so I'm going to do that
I really appreciate the research and I updated the title to reflect the likely cause (likely for others - definite for you)
