### ISSUE TITLE
[React Native][iOS] Consent mode v2

### ISSUE THREAD

**Issue by SindiAscendix** [invertase/react-native-firebase#7758]
### Discussed in https://github.com/invertase/react-native-firebase/discussions/7752

<div type='discussions-op-text'>

<sup>Originally posted by **SindiAscendix** April 17, 2024</sup>
hey there 👋
I'm facing some issues on my React Native app in which I use react-native-firebase and currently, we have enabled Google Analytics through it.

Some time ago we got all tracking not working anymore because of consent mode v2. I was using "@react-native-firebase/analytics": "^17.3.0"
Android is working out of the box without making any changes. Now I have upgraded to "@react-native-firebase/analytics": "^19.0.1" (as mentioned here everything was released on this version https://github.com/invertase/react-native-firebase/discussions/6636#discussioncomment-8547364) but still we don't see any changes in the console, analytics still not working for iOS.
Can someone please share with me if they made anything different to support this on iOS too?
Your feedback is very valuable!
</div>

**Comment by alparbartok** [comment]
Hi, I'm having a similar issue but after Consent Mode V2 integration all my analytics calls are blocker if the user denies the tracking.

Note: we are using Usercentrics as consent mediation tool.

I didn't find anything in the documentation, how can we achieve "Advanced Consent mode v2" (even if the user denies the tracking we are still tracking but anonymously)

```
"@react-native-firebase/analytics": "^20.1.0",
"@react-native-firebase/app": "^20.1.0",
"@react-native-firebase/crashlytics": "^20.1.0",
"@react-native-firebase/messaging": "^20.1.0", 
```

We are using the `@react-native-firebase` sdk as the documentation said.
Note**: we are using `setConsent` function so enable consent, otherwise they are disabled from the native file: ad_storage, ...

Thanks in advance.
