### ISSUE TITLE
[🐛] pod install issue after added library

### ISSUE THREAD

**Issue by thanatas** [invertase/react-native-firebase#7775]
I added firebase for messaging purposes. All functionality is working well on android. 

On ios part, I strictly follow the documentation. 

in ios folder =>  pod install rises the following error. 

[!] Invalid `Podfile` file: cannot load such file -- /Users/<user>/Projects/MobileApp/node_modules/react-native/scripts/react_native_pods.rb
Debugger attached.
Waiting for the debugger to disconnect....

from/Users/<user>/Projects/MobileApp/ios/Podfile:2
 -------------------------------------------
 Resolve react_native_pods.rb with node to allow for hoisting
 >  require Pod::Executable.execute_command('node', ['-p',
 'require.resolve(
-------------------------------------------

Here is the my package.json
{
  "name": "XXXXX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start --reset-cache",
    "test": "jest"
  },
  "dependencies": {
    "@notifee/react-native": "^7.8.2",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-firebase/app": "^17.5.0",
    "@react-native-firebase/messaging": "^17.5.0",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "axios": "^1.6.8",
    "iconsax-react-native": "^0.0.8",
    "log-timestamp": "^0.3.0",
    "react": "18.2.0",
    "react-hook-form": "^7.51.3",
    "react-native": "0.74.0",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-paper": "^5.12.3",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "react-native-snackbar": "^2.6.2",
    "react-native-svg": "^15.2.0",
    "util": "^0.12.5",
    "utils": "^0.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/preset-react": "^7.24.1",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.81",
    "@react-native/eslint-config": "0.74.81",
    "@react-native/metro-config": "0.74.81",
    "@react-native/typescript-config": "0.74.81",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-native-dotenv": "^3.4.11",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

Any Suggestions?

**Comment by thanatas** [comment]
Any suggestions ?

**Comment by mikehardy** [comment]
A question - why are you using an old version of react-native-firebase? It doesn't make sense to use version 17 now, it won't even be allowed on the app store because of Privacy Manifest requirements, which are only fully satisfied in the latest versions. You should examine the versions closely and make sure you have react-native-firebase up to date

For your error:

> [!] Invalid Podfile file: cannot load such file -- /Users//Projects/MobileApp/node_modules/react-native/scripts/react_native_pods.rb

I'm not sure, it looks like something is really not correct in your environment. That's a react-native file, not react-native-firebase

You've deleted the rest of our template so I can't offer more help, which means I need to close this.

But I can tell you that this build demonstrator starts from nothing and creates a new app then integrates everything and it works every time - you may use it as an example of how to get things working https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
