### ISSUE TITLE
Missing Item fields for GA4 in Analytics

### ISSUE THREAD

**Issue by mtebele** [invertase/react-native-firebase#7806]
Item needs extra fields for logging, particularly for Purchase and Begin Checkout.

https://developers.google.com/analytics/devguides/collection/ga4/reference/events?client_type=gtag#begin_checkout_item
https://rnfirebase.io/reference/analytics/item

Please find below the differences between GA4 and rnfirebase:

| AnalyticsEventItem  | RNFirebase Item |
| ------------- | ------------- |
| affiliation |  |
| coupon |  |
| creativeName |  |
| creativeSlot |  |
| currency |  |
| discount |  |
| hashCode |  |
| index |  |
| itemBrand | itemBrand |
| itemCategory | itemCategory |
| itemCategory2 |  itemCategory2 |
| itemCategory3 | itemCategory3 | 
| itemCategory4 | itemCategory4 | 
| itemCategory5 | itemCategory5 | 
| itemId | itemId | 
| itemListId | itemListId |
| itemListName | itemListName |
| itemName | itemName | 
| itemVariant | itemVariant |
| locationId |  |
| price | price | |
| promotionId |  |
| promotionName |  |
| quantity | quantity |

_Originally posted by @twocs in https://github.com/invertase/react-native-firebase/discussions/6964_

**Comment by twocs** [comment]
> We are also not able to log `index` on GA4. any workaround

Personally, the analytics typescript interfaces in react native firebase are not fit for purpose, since they were all written for now dead Universal Analytics. Therefore, we have just not bothered with any of the functions like `logBeginCheckout`

been handcrafting everything using `logEvent`, since it isn't picky about what fields are sent. This has been working, and you can make your own custom item interface if you like.

```typescript
  await analytics().logEvent("begin_checkout", {
    currency: "USD",
    value: 30.03,
    coupon: "SUMMER_FUN",
    items: [{
      item_id: "SKU_12345",
      item_name: "Stan and Friends Tee",
      index: 5,
    }],
  });
```


One day if I have spare time I would just go through the analytics types in https://github.com/invertase/react-native-firebase/blob/main/packages/analytics/lib/index.d.ts#L53 and bring them up-to-date with https://firebase.google.com/docs/reference/js/analytics

**Comment by mikehardy** [comment]
I would *love* a PR that did as you mention @twocs ! Your reference links for firebase-js-sdk are exactly the correct ones as an authoritative source for typings, and getting up to parity with them would be great

**Comment by twocs** [comment]
> I would *love* a PR that did as you mention @twocs ! Your reference links for firebase-js-sdk are exactly the correct ones as an authoritative source for typings, and getting up to parity with them would be great

Is it practical to import firebase-js-sdk for the types, or would it be better to just have the similar code in rn-fire base?

**Comment by mikehardy** [comment]
We cannot assume people have firebase-js-sdk so we internalize types - good question
