### ISSUE TITLE
Type Change Clarification/Justification

### ISSUE THREAD

**Issue by chinomnsoawazie** [invertase/react-native-firebase#7815]
I noticed the change below primarily because it is now throwing type errors (where there was none previously).
https://github.com/invertase/react-native-firebase/blob/b6079dd09ed1f6e47dc782df0d98c5479bfc0cd4/packages/functions/lib/index.d.ts#L363

Yes, I could get rid of the errors by specifying the `RequestData` and `ResponseData` data types, but is this really necessary? I get the point of making it possible to type those items, but forcing them by defaulting the type to `unknown`, I'm not sure what the benefits really are. At I am _yet_ to see failures (both in dev and prod) because of this, but still. Setting the default type to `any` I believe will make the purpose of giving the option to type those items available **_and_** create a quasi backward compatibility.

**Comment by skam22** [comment]
This change was made to match the upstream library which has the type that you referenced above; inherently that forces you to explicitly define the request and response data types. 

Your point is valid though. The previous release did not match the upstream library and allowed for the possibility of errors without type protection.  

I’m not sure it would be beneficial to divert from the upstream library to explicitly support scenarios where then request and response data types are not defined.

**Comment by skam22** [comment]
As a clarification: I wrote the PR that created the change. 

My initial PR did have the type set to “any”. 

Upon further review / feedback I made the changes to match the upstream library. 

You can view the discussion and the initial PR in the closed tab.

**Comment by mikehardy** [comment]
We have to follow the firebase-js-sdk typings where they exist as our explicit goal is interoperability in all ways possible

I *think* we are doing that now, so while I understand the frustration (it bit me in my projects as well!) cleaning things up so that it has fidelity with firebase-js-sdk was something I begrudgingly did and moved on, as an app developer

as a maintainer I can't really deviate from firebase-js-sdk typings so unless the types are actually different now I don't think I can take any action here
