### ISSUE TITLE
File upload to storage on Android doesn't return correct name metadata

### ISSUE THREAD

**Issue by gvillenave** [invertase/react-native-firebase#785]
This might very well be an issue with the underlying Android SDK, but I'm starting here just to make sure.

When uploading a file to storage, the resolved file object contains metadata such as the name and bucket of the file. However, what I found was that on Android the `name` property only contains the file name, as opposed to the full path within the bucket. Example:
```
firebase.storage().ref('foo/bar.jpg').putFile(uri).then(file => {
  console.log(file.metadata.name);
});
```
The above prints out `foo/bar.jpg` on iOS but `bar.jpg` on Android.

Is RNFirebase handling the metadata differently on Android, or does that point to an issue in the native SDK?

Thanks!

### Environment
1. Application Target Platform: Android
2. Development Operating System: macOS
4. React Native version: 0.51
5. RNFirebase Version: 3.2.2
6. Firebase Module: storage

**Comment by Salakar** [comment]
@gvillenave can confirm that this is a firebase iOS SDK issue, the correct behaviour should be returning just the name without path according to the firebase web & android sdk's - `fullPath`/`getPath` already provides the path with file name.

**iOS SDK** usage in **RNFirebase**: https://github.com/invertase/react-native-firebase/blob/master/ios/RNFirebase/storage/RNFirebaseStorage.m#L362

**Android SDK** usage in **RNFirebase**: https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java#L511

**Web SDK** docs for **name**: https://firebase.google.com/docs/reference/js/firebase.storage.FullMetadata#name

![image](https://user-images.githubusercontent.com/5347038/35466778-f12e3a10-02fe-11e8-8b2a-da6255a9e361.png)

Could you raise an issue on https://github.com/firebase/firebase-ios-sdk if possible and tag in this one please so we can track it.

If you need the path behaviour I'd recommend using `.fullPath` otherwise in the meantime here's a temporary workaround function to force iOS to be correct if you need it:

```js
function fixName(name = '') {
    if (name.includes('/')) return name.split('/').pop().split('/').pop();
    return name;
}

// usage:
firebase.storage().ref('foo/bar.jpg').putFile(uri).then(file => {
    console.log(fixName(file.metadata.name));
});
```

**Comment by gvillenave** [comment]
Thanks! Looks like fullPath is what I need.

**Comment by Salakar** [comment]
@gvillenave Ok thanks, let us know how you get on.
