### ISSUE TITLE
Crashlytics for Android are all bunched under io.invertase.firebase.fabric.crashlytics.RNFirebaseCrashlytics.recordError

### ISSUE THREAD

**Issue by JonnyLinja** [invertase/react-native-firebase#790]
### Issue

Crashlytics for Android are all bunched under io.invertase.firebase.fabric.crashlytics.RNFirebaseCrashlytics.recordError.

![image](https://user-images.githubusercontent.com/684861/35529372-da2b8f1e-04fe-11e8-9fd4-f0bade03ba3d.png)

### Expectation

It should split them up properly by error type and error code in the manner that iOS does it. Note that as it's React Native, the implementation is the same for both iOS and Android.

![image](https://user-images.githubusercontent.com/684861/35529376-dfb9aeb6-04fe-11e8-93a1-1002c784cede.png)

**Comment by chrisbianca** [comment]
@JonnyLinja Unfortunately, I'm not sure that there's much we can do here due to the underlying native SDK.  The Android SDK only exposes a single `Crashlytics.logException()` method which takes an exception object.

There's no way of specifying the error type or code specifically unlike on iOS where they are properties of the underlying Exception.

In a standard Android application, this wouldn't be an issue as the exceptions would be logged from different classes / lines, but with RN this becomes a problem.

Check out this SO post which reports a similar issue.  The first response is from a Fabric/Firebase Crashlytics dev and unfortunately says there isn't a workaround for this. https://stackoverflow.com/questions/47654410/how-to-effectively-group-non-fatal-exceptions-in-crashlytics-fabrics
