### ISSUE TITLE
[🐛] Bug Report Title - On accept the notification App crashes in Android 14

### ISSUE THREAD

**Issue by Tanuja-A** [invertase/react-native-firebase#7968]
Hi Team,

We are using the react native 0.72 version and recently we changed the TargetSDK to 34 on latest release update by Google play store. Upon changing the TargetSDK, we see that the app is crashed on acceptance of the push notification which is integrated with the firebase. We attached the package.json for the reference and also please let us know if any further information is needed from our end.

[package.json](https://github.com/user-attachments/files/16595354/package.json)

Thanks in advance

**Comment by russellwheatley** [comment]
I would open an issue and fill out all relevant aspects. What is expected behaviour vs what is actually happening. I am also pretty skeptical that updating the target SDK + pressing push notification causes the crash. We use target 34 in [our test app](https://github.com/invertase/react-native-firebase/blob/main/tests/android/build.gradle#L5)
