### ISSUE TITLE
index.js.flow has not types and will take precedence over a libdef

### ISSUE THREAD

**Issue by leonp1991** [invertase/react-native-firebase#830]
### Issue
Currently the distributed version of this lib has an index.js.flow file. This file also does not currently  provide any types. This is an issue because if anyone wants to create a libdef for the library, flow uses <import_name>.js.flow over the libdef.

### More info
flow-bin: tested on 56.0, 65.0

I apologise if the issue does not appear to conform to the issue template, but the issue does not have anything to do with the functionality or the react-native target

### Workaround
add this to your .flowconfig

```
[ignore]
.*/node_modules/react-native-firebase/dist/index.js.flow
```

Happy to submit a PR, if this is deemed a go

**Comment by chrisbianca** [comment]
@leonp1991 We've been aware of this for a little while, but this has finally prompted me to add some exported types to the `index.js.flow` file for App, Auth, Database and Firestore: https://github.com/invertase/react-native-firebase/commit/4e81527246f6c9c9bde2da598bc89ab88d103669

The rest of the types are a little all over the place, but will be added as we tidy them up.

We'll get these release today / tomorrow.

Out of interest, do you have a libdef that you've created?  We're debating whether we should consider using a libdef rather than exporting the .js.flow files.

**Comment by leonp1991** [comment]
Thats great news about the new release!

I have only just added messaging to a project Im working on so I have only added a few types at this point.

Personally I think <module_name>.js.flow would be the ideal Developer Experience. I am more than happy to contribute to the types of the messaging section if that would help.

**Comment by chrisbianca** [comment]
How would you envisage `<module_name>.js.flow` working?

In terms of messaging, this is being completely rewritten as part of #595 and I'm making sure the Flow types are done as part of this, but thank you for the offer!  If you're interested in helping, then storage could do with a bit of attention on the Flow types side of thing?
