### ISSUE TITLE
Messaging ( Push Notification ) 

### ISSUE THREAD

**Issue by Kottidev** [invertase/react-native-firebase#987]
Can we add this features with Firebase Cloud Messaging ? 

For iOS 
 * Background/Managed notifications (notifications that can be cleared from the server, like Facebook messenger and Whatsapp web)
 * PushKit API (for VoIP and other background messages)
 * Interactive notifications (allows you to provide additional functionality to your users outside of your 
  application such as action buttons)

For Android
 * Built-in notification drawer management
 * High degree of code extensibility to allow for advanced custom layouts and any specific notifications behavior as available by Android's API
 
@chrisbianca  Please check the packages : 
https://github.com/wix/react-native-notifications
https://github.com/ianlin/react-native-voip-push-notification

Can We merge there code and contribute with him , if yeah , your package will  support all notifications features on Android and iOS

### Environment

Both

1. Application Target Platform:

macOS Sierra

2. Development Operating System:

 iOS or Android SDK version 

3. Build Tools:

0.55.x

4. React Native version:

2.1.3)

5. RNFirebase Version:

messaging

6. Firebase Module:

**Comment by chrisbianca** [comment]
@Kottidev Thanks for your suggestions.  I'll respond to each of them in term:

For iOS:
- **Background / managed notifications**
This is already supported.
We have purposefully kept the core API used by FCM rather than introducing custom attributes that the `react-native-firebase` library interprets.  Instead, we've ensured that the library allows background notifications on both iOS and Android to have the full set of functionality which means that the developer has complete control over what they'd like to do, e.g. showing a local notification, or clearing current notifications.
- **PushKit API**
This is an interesting suggestion but we're unlikely to support it in the short term as FCM has no support for Apple's PushKit or VOIP.
- **Interactive notifications**
This is currently in progress: https://github.com/invertase/react-native-firebase/tree/ios-notification-categories

For Android:
- **Built-in notification drawer management**
This is already supported through the `firebase.notifications()` instance: https://rnfirebase.io/docs/v4.0.x/notifications/reference/Notifications
- **Custom notifications**
We already support big picture and big text style notifications from JS rather than having to use native Android code. We have a feature request for inbox notifications here: https://react-native-firebase.canny.io/feature-requests/p/inbox-style-notifications-for-android which we'll be adding in the near future along with any other style notifications that the Android API supports.  All of this will be available from JS so you don't need to write any native Android code.

I hope this answers all your points.  We want to be as fully featured as possible within what's supported by FCM itself and will continue to include features as discussed over the coming weeks and months.

**Comment by marvinkome** [comment]
> Custom notifications
We already support big picture and big text style notifications from JS rather than having to use native Android code. We have a feature request for inbox notifications here: https://react-native-firebase.canny.io/feature-requests/p/inbox-style-notifications-for-android which we'll be adding in the near future along with any other style notifications that the Android API supports. All of this will be available from JS so you don't need to write any native Android code.

This hasn't been implemented yet? can't find it in the docs

**Comment by venux92** [comment]
@marvinkome you can find it here.
https://rnfirebase.io/docs/v5.x.x/notifications/reference/AndroidNotification#setBigPicture
https://rnfirebase.io/docs/v5.x.x/notifications/reference/AndroidNotification#setBigText

But it only works for local notification.
I haven't found a way to have the picture on the notification when the app is in the background or killed.
I'm using FCM HTTP V1

So in case you succeed please share ;)

**Comment by windydang26** [comment]
setBigText not working for me.
